#!/bin/ksh
# -------------------------------------------------------
# MARS request to read data used in the ifs2icon utility.
# run as: mars4icon_smi_32r2- 2006123100 255 1/to/91
#
# versions:
#   mars4icon_smi_32r3+:      conversion of SWVL to soil moisture index SMI
#                             for horizontal interpolation (assuming post 32r3
#                             soil model input - 6 soil types)
#   mars4icon_smi_32r2-:      assuming model input from pre 32r3 cycles
#                             (single soil type)
#   mars4icon_smi_ERAinterim: using ERA-Interim data 
#                             (31r1 model with 36r4 land model data)
#                             2 options:
#                             exp=fiv7: ERA-Interim forced land model
#                             exp=fiv8: ERA-Interim + GPCP corrected precip
#
# attention: 
#   * requires data routine "datconv" by J. Foerster
#   * at DWD requires ECMWF login by eccert
#   * requires mars version 1.9.9
#     (. ${GRIB_API}/bin/grib_api-setenv -r -V1.9.9)
#   * since cy36r4 (2010/11/09) there is rain and snow, which is required by IFS2ICON
#     (optionally turn on/off crwc/csw)
#   * ERAinterm: only works until 2010! (fiv8 not available afterwards)
#   * !!!!!!ATTENTION: Even though SWVL is converted to soil moisture index SMI, 
#     this is not reflected within the corresponding metadata. Metadata still belong 
#     to SWVL. !!!!!!!!!
#
# history:
#   Helmut Frank    201107  adopted from GME equivalent
#   Martin Koehler  201108  SMI soil moisture index
# -------------------------------------------------------

# --- argument list ---

pdatin=${1:-g12}          # or "${1: 2010070100 2010070200}"
res="${2:-255}"
levelist=${3:-1/to/91}

# --- data output ---

datadir=/e/uwork/${USER}/icon/ifs.data
mkdir -p $datadir
tempdir=${TMPDIR}

# --- date processing ---

cymdg=$(datconv -Cy ${pdatin})
typeset -L8 cymd=${cymdg}
typeset -R2 hh=${cymdg}

# --- read ---

case ${res} in
    255) grd=128 ;;
    799) grd=400 ;;
   1279) grd=640 ;;
esac
grib_file=${datadir}/ifs_oper_T${res}_${cymdg}.grb

cat > ${tempdir}/MARS_IN.$$ << MARS_IFS2ICON_EOF.$$
# MARS request for ifs2icon
retrieve,
        padding  = 0,
        accuracy = 16,
        class    = od,
        expver   = 1,
        domain   = g,
        stream   = oper,
        type     = an,
        date     = ${cymd},
        time     = ${hh},
        step     = 0,
        target   = "${grib_file}",
        param    = u/v/w/t/q/clwc/ciwc/o3, # /crwc/cswc/ rain,snow on/off
        repres   = sh,                     # spherical harmonics,
        resol    = ${res},
        grid     = ${grd},
        gaussian = regular,
        levtype  = ml,                     # model levels,
        levelist = ${levelist}
retrieve,
        param    = lnsp/z,
        levelist = 1
retrieve,
        param    = tsn/skt/stl1/stl2/stl3/stl4/sd/rsn/src/ci,
        repres   = gg, 
        resol    = off, 
        levtype  = surface

# Retrieve the Volumetric Soil Water Layer 1-4 fieldset swvl
# and compute the soil moisture index SMI.
retrieve,
        param    = SWVL1/SWVL2/SWVL3/SWVL4,
        gaussian = reduced,
        target   = "${datadir}/swvl.grb"
read,   source   = "${datadir}/swvl.grb",
        param    = SWVL1,
        fieldset = swvl
compute,fieldset = smi1,
        formula  = "(swvl-0.171)/(0.323-0.171)"

read,   source   = "${datadir}/swvl.grb",
        param    = SWVL2,
        fieldset = swvl
compute,fieldset = smi2,
        formula  = "(swvl-0.171)/(0.323-0.171)"

read,   source   = "${datadir}/swvl.grb",
        param    = SWVL3,
        fieldset = swvl
compute,fieldset = smi3,
        formula  = "(swvl-0.171)/(0.323-0.171)"

read,   source   = "${datadir}/swvl.grb",
        param    = SWVL4,
        fieldset = swvl
compute,fieldset = smi4,
        formula  = "(swvl-0.171)/(0.323-0.171)"

# Write SMI 1-4 (convert from reduced Gaussian to regular Gaussian)
write,  fieldset = smi1, target = "${datadir}/smi.grb"
write,  fieldset = smi2, target = "${datadir}/smi.grb"
write,  fieldset = smi3, target = "${datadir}/smi.grb"
write,  fieldset = smi4, target = "${datadir}/smi.grb"
read,   param = SWVL1, fieldset = smi1, source = "${datadir}/smi.grb", 
        gaussian=regular, grid=${grd}
read,   param = SWVL2, fieldset = smi2, source = "${datadir}/smi.grb", 
        gaussian=regular, grid=${grd}
read,   param = SWVL3, fieldset = smi3, source = "${datadir}/smi.grb", 
        gaussian=regular, grid=${grd}
read,   param = SWVL4, fieldset = smi4, source = "${datadir}/smi.grb", 
        gaussian=regular, grid=${grd}
write,  fieldset = smi1, target = "${grib_file}"
write,  fieldset = smi2, target = "${grib_file}"
write,  fieldset = smi3, target = "${grib_file}"
write,  fieldset = smi4, target = "${grib_file}"

retrieve,
        type     = an,
        step     = 0,
        repres   = gg,                  # gaussian grid,
        resol    = off,
        levtype  = surface,
        gaussian = regular,
        param    = lsm/sr/cvl/cvh/sdor/isor/anor/slor,
        target   = "${grib_file}"
MARS_IFS2ICON_EOF.$$

mars ${tempdir}/MARS_IN.$$
rc_mars=$?

if [ $rc_mars -ne 0 ]; then
    { print -- "Error $rc_mars executing mars"
      print -- "Input file to MARS:"
      cat ${tempdir}/MARS_IN.$$
    } >&2
    rm ${tempdir}/MARS_IN.$$
    exit $rc_mars
fi

print ""
print "Retrieved operational analysis for ${cymdg}. resol=${res} grid=${grd} levels=${levelist}"

ls -al ${grib_file}
rm -f ${tempdir}/MARS_IN.$$

exit 0
