#!/bin/bash

export PATH=/hpc/sw/gcc-9.1.0/VH/bin:$PATH

export LD_LIBRARY_PATH=/hpc/sw/gcc-9.1.0/VH/lib64:/hpc/sw/gcc-9.1.0/VH/lib:/hpc/sw/mpfr-4.0.2/VH/lib:$LD_LIBRARY_PATH

./configure \
   --with-fortran=gcc \
   --with-grib_api=/hpc/sw/grib_api-1.23.1/VH \
   --disable-jsbach --disable-ocean --disable-testbed \
   --without-yac \
   VERBOSE=1 \
   NMPI_F90_VH=gfortran \
   NMPI_CC_VH=gcc \
   NMPI_CC=gcc \
   NMPI_F90=gfortran

# set some special compile lines 
sed -i \
   "/^mo_input_container.o:/!b;
   :a;
   n;
   /./ba;
   i\\\t\$(FC) \$(FFLAGS) -fopenmp -c $<" \
   build/x86_64-unknown-linux-gnu/src/Makefile

   mv config.log config.log.x86
   if [ -f Makefile ] ; then
      mv Makefile Makefile.x86
   else
      exit 1;
   fi 

# Configure for aurora vector engine
./configure \
   --with-fortran=nec \
   --with-grib_api=/hpc/sw/grib_api-1.23.1/VE \
   --disable-jsbach --disable-ocean --disable-testbed \
   --without-yac \
   --host=aurora

# set some special compile lines 
sed -i \
   "/^mo_intp_rbf_coeffs.o:/!b;
   :a;
   n;
   /./ba;
   i\\\t\$(FC) \$(FFLAGS) -finline-max-function-size=1000 -finline-max-depth=3 -c $<" \
   build/aurora-nec-linux-gnu/src/Makefile
sed -i \
   "/^mo_flake.o:/!b;
   :a;
   n;
   /./ba;
   i\\\t\$(FC) \$(FFLAGS) -finline-max-function-size=1000 -finline-max-depth=3 -c $<" \
   build/aurora-nec-linux-gnu/src/Makefile
# this is to reduce the compile time of a large module that does no computational work
sed -i \
   "/^mo_srtm_kgb_routines.o:/!b;
   :a;
   n;
   /./ba;
   i\\\t\$(FC) \$(FFLAGS) -O1 -fno-inline-functions -c $<" \
   build/aurora-nec-linux-gnu/src/Makefile

   mv config.log config.log.sx
   if [ -f Makefile ] ; then
      mv Makefile Makefile.sx
   else
      exit 1;
   fi

cat << EOF > Makefile
.PHONY: build_x86 build_sx

all: build_x86 build_sx

build_x86: 
	\$(MAKE) -f Makefile.x86

build_sx:
	\$(MAKE) -f Makefile.sx

.PHONY: clean distlcean

clean:
	\$(MAKE) clean -f Makefile.x86
	\$(MAKE) clean -f Makefile.sx

distclean:
	\$(MAKE) distclean -f Makefile.x86
	\$(MAKE) distclean -f Makefile.sx
	-rm -f Makefile.x86 Makefile.sx
	-rm -f config.log.x86 config.log.sx
EOF
