#!/bin/ksh
#==============================================================================
# Creates the ICON postprocessing scripts
# Leonidas Linardakis, MPI-M, 2011-25-1
#==============================================================================

#==============================================================================
echo "-----------------------------------------------------------"
base_folder=$(pwd)
input_folder=run
#==============================================================================
. $base_folder/config/set-up.info
if [[ x$use_shell == x ]] ; then
  use_shell="/bin/ksh"
fi
# The $make_runscript command directs to the ./config/make_target_runscript
make_runscript="$use_shell ./config/make_target_runscript"
#==============================================================================

#==============================================================================
# Create the postprocessing scripts
#
# NOTE: The postprocessing scripts are all sequential, so we define:
#    with_mpi="no" with_openmp="no"
#==============================================================================
cd $input_folder
file_list=`ls post.*`
cd $base_folder
for filename in $file_list
do
  if [[ $filename != *.run && $filename != *~ &&  $filename != *.status ]] ; then
    $make_runscript in_folder=$input_folder in_script=${filename} out_script=${filename}.run with_mpi="no" with_openmp="no" cpu_time="01:00:00"
  fi
done


echo "-----------------------------------------------------------"
