#!/bin/bash
set -x

universe=$1
#universe=fluent
experiments_list="test_ocean_omip_10days"

make_target_reference()
{
  compile_folder=$1
  target=$2

  cd $compile_folder
  rm -rf build
  ./build_local
  
cat > run_parameters << EOF
queue=develop
run=true
use_submit=\$use_sync_submit
EOF
  cp scripts/run_scripts/make_my_runscript make_target_script

  mkdir -p $ocean_reference/$target

  for experiment in ${experiments_list}; do
    rm -rf experiments/$experiment
    ./make_target_script $experiment
    sleep 20
    cp -r experiments/$experiment $ocean_reference/$target  
  done

  cd -
}



# thunder
ocean_base=/scratch/mpi/CC/mh0287/oes/$universe
ocean_reference=$ocean_base/reference
ocean_reference_old=${ocean_reference}.old
# rm -rf $ocean_reference_old
# mv $ocean_reference $ocean_reference_old
# make_target_reference gcc_yMnO thunder_gcc
make_target_reference intel_yMyO thunder_intel
make_target_reference nag_yMnO   thunder_nag
