#!/bin/ksh
#=============================================================================
# =====================================
# mistral batch job parameters
#-----------------------------------------------------------------------------
#SBATCH --account=mh0287
#SBATCH --job-name=exp.plainText.run
#SBATCH --partition=compute
##SBATCH --workdir=/home/mpim/m300064/work/src/cimd/icon-cimd/run
#SBATCH --nodes=1
#SBATCH --threads-per-core=1
#SBATCH --output=LOG.exp.plain.run.%j.o
#SBATCH  --error=LOG.exp.plain.run.%j.o
#SBATCH --exclusive
#SBATCH --time=00:01:00

#=============================================================================
#
  date
  hostname
  echo "Plain Text Scripts dummy"
  date

#-----------------------------------------------------------------------------

	
# exit 0
#
# vim:ft=sh
#-----------------------------------------------------------------------------
