!--------------------------------------------------------------------
!
! Serialization routine for NWP turbtran
!
!--------------------------------------------------------------------

MODULE mo_ser_nwp_tutra

  USE mo_kind,               ONLY: wp
  USE mo_exception,          ONLY: warning, finish
  USE mo_ser_common,         ONLY: init
  USE mtime,                 ONLY: datetimeToString, MAX_DATETIME_STR_LEN
  USE mo_time_config,        ONLY: time_config
  USE mo_nonhydro_types,     ONLY: t_nh_prog, t_nh_diag, t_nh_metrics
  USE mo_nwp_phy_types,      ONLY: t_nwp_phy_diag
  USE mo_nwp_lnd_types,      ONLY: t_lnd_prog, t_wtr_prog, t_lnd_diag
  USE mo_run_config,         ONLY: iqv, iqc
  USE mo_ext_data_types,     ONLY: t_external_data
  USE mo_ser_nml,            ONLY: ser_turbtrans_interface

  IMPLICIT NONE

  INTEGER, PARAMETER :: selected_block = 1

  PUBLIC :: serialize_turbtrans_interface_input
  PUBLIC :: serialize_turbtrans_interface_output

  CONTAINS

  SUBROUTINE serialize_turbtrans_interface_input(jg, nproma, nlev, &
                                                 p_metrics, p_prog, p_prog_rcf, p_diag, prm_diag, &
                                                 lnd_prog_new, lnd_diag, wtr_prog_new, ext_data)
    INTEGER, INTENT(IN)    :: jg, nproma, nlev
    TYPE(t_nh_metrics),       INTENT(IN) :: p_metrics
    TYPE(t_nh_prog),  TARGET, INTENT(INOUT) :: p_prog          !<the prog vars
    TYPE(t_nh_prog),          INTENT(INOUT) :: p_prog_rcf      !< current time levels
    TYPE(t_nh_diag),  TARGET, INTENT(INOUT) :: p_diag
    TYPE(t_nwp_phy_diag),     INTENT(INOUT) :: prm_diag        !< atm phys vars
    TYPE(t_lnd_prog),         INTENT(INOUT) :: lnd_prog_new    !< prog vars for sfc
    TYPE(t_lnd_diag),         INTENT(INOUT) :: lnd_diag        !< diag vars for sfc
    TYPE(t_wtr_prog),         INTENT(IN)    :: wtr_prog_new    !< prog vars for wtr
    TYPE(t_external_data),    INTENT(IN)    :: ext_data        !< external data

    CHARACTER(LEN=MAX_DATETIME_STR_LEN) :: date
    INTEGER, SAVE :: ser_count = 0

    !$ser verbatim ser_count = ser_count + 1
    !$ser verbatim IF(ser_count <= ser_turbtrans_interface) THEN
    !$ser verbatim   CALL warning('SER:mo_ser_nwp_tutra:turbtrans_interface-input','Serialization is active!')
#if defined( _OPENACC )
    !$ser verbatim   CALL warning('GPU:mo_ser_nwp_tutra:turbtrans_interface-input','GPU HOST synchronization forced by serialization!')
    !$ser verbatim  !$ACC UPDATE HOST( p_metrics%z_mc ) IF( ASSOCIATED(p_metrics%z_mc) )
    !$ser verbatim  !$ACC UPDATE HOST( p_metrics%z_ifc ) IF( ASSOCIATED(p_metrics%z_ifc) )
    !$ser verbatim  !$ACC UPDATE HOST( p_metrics%geopot_agl ) IF( ASSOCIATED(p_metrics%geopot_agl) )
    !$ser verbatim  !$ACC UPDATE HOST( p_metrics%geopot_agl_ifc ) IF( ASSOCIATED(p_metrics%geopot_agl_ifc) )
    !$ser verbatim  !$ACC UPDATE HOST( p_metrics%mask_mtnpoints_g ) IF( ASSOCIATED(p_metrics%mask_mtnpoints_g) )
    !$ser verbatim  !$ACC UPDATE HOST( p_prog%exner ) IF( ASSOCIATED(p_prog%exner) )
    !$ser verbatim  !$ACC UPDATE HOST( p_prog_rcf%tracer ) IF( ASSOCIATED(p_prog_rcf%tracer) )
    !$ser verbatim  !$ACC UPDATE HOST( p_prog_rcf%tke ) IF( ASSOCIATED(p_prog_rcf%tke) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%temp ) IF( ASSOCIATED(p_diag%temp) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%pres ) IF( ASSOCIATED(p_diag%pres) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%pres_sfc ) IF( ASSOCIATED(p_diag%pres_sfc) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%pres_ifc ) IF( ASSOCIATED(p_diag%pres_ifc) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%u ) IF( ASSOCIATED(p_diag%u) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%v ) IF( ASSOCIATED(p_diag%v) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%gz0 ) IF( ASSOCIATED(prm_diag%gz0) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%gz0_t ) IF( ASSOCIATED(prm_diag%gz0_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tcm_t ) IF( ASSOCIATED(prm_diag%tcm_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tch_t ) IF( ASSOCIATED(prm_diag%tch_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvm_t ) IF( ASSOCIATED(prm_diag%tvm_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvh_t ) IF( ASSOCIATED(prm_diag%tvh_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tcm ) IF( ASSOCIATED(prm_diag%tcm) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tch ) IF( ASSOCIATED(prm_diag%tch) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvm ) IF( ASSOCIATED(prm_diag%tvm) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvh ) IF( ASSOCIATED(prm_diag%tvh) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tfm ) IF( ASSOCIATED(prm_diag%tfm) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tfh ) IF( ASSOCIATED(prm_diag%tfh) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tfv_t ) IF( ASSOCIATED(prm_diag%tfv_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkr_t ) IF( ASSOCIATED(prm_diag%tkr_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tfv ) IF( ASSOCIATED(prm_diag%tfv) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkr ) IF( ASSOCIATED(prm_diag%tkr) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkvm ) IF( ASSOCIATED(prm_diag%tkvm) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkvm_s_t ) IF( ASSOCIATED(prm_diag%tkvm_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkvh_s_t ) IF( ASSOCIATED(prm_diag%tkvh_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkvh ) IF( ASSOCIATED(prm_diag%tkvh) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%rcld ) IF( ASSOCIATED(prm_diag%rcld) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%ktop_envel ) IF( ASSOCIATED(prm_diag%ktop_envel) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%shfl_s_t ) IF( ASSOCIATED(prm_diag%shfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%qhfl_s_t ) IF( ASSOCIATED(prm_diag%qhfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%umfl_s_t ) IF( ASSOCIATED(prm_diag%umfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%vmfl_s_t ) IF( ASSOCIATED(prm_diag%vmfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%lhfl_s_t ) IF( ASSOCIATED(prm_diag%lhfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%u_10m ) IF( ASSOCIATED(prm_diag%u_10m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%v_10m ) IF( ASSOCIATED(prm_diag%v_10m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%u_10m_t ) IF( ASSOCIATED(prm_diag%u_10m_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%v_10m_t ) IF( ASSOCIATED(prm_diag%v_10m_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tmax_2m ) IF( ASSOCIATED(prm_diag%tmax_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tmin_2m ) IF( ASSOCIATED(prm_diag%tmin_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%t_2m ) IF( ASSOCIATED(prm_diag%t_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%qv_2m ) IF( ASSOCIATED(prm_diag%qv_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%td_2m ) IF( ASSOCIATED(prm_diag%td_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%rh_2m ) IF( ASSOCIATED(prm_diag%rh_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvs_s_t ) IF( ASSOCIATED(prm_diag%tvs_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%t_2m_land ) IF (ASSOCIATED(prm_diag%t_2m_land))
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%td_2m_land ) IF (ASSOCIATED(prm_diag%td_2m_land))
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%rh_2m_land ) IF (ASSOCIATED(prm_diag%rh_2m_land))
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%dyn_gust ) IF (ASSOCIATED(prm_diag%dyn_gust))
    !$ser verbatim  !$ACC UPDATE HOST( wtr_prog_new%h_ice ) IF (ASSOCIATED(wtr_prog_new%h_ice))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_prog_new%t_g ) IF (ASSOCIATED(lnd_prog_new%t_g))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_prog_new%t_g_t ) IF (ASSOCIATED(lnd_prog_new%t_g_t))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_diag%qv_s ) IF (ASSOCIATED(lnd_diag%qv_s))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_diag%qv_s_t ) IF (ASSOCIATED(lnd_diag%qv_s_t))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_diag%snowfrac_t ) IF (ASSOCIATED(lnd_diag%snowfrac_t))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_diag%snowfrac_lc_t ) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%idx_lst_t ) IF (ASSOCIATED(ext_data%atm%idx_lst_t))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%gp_count_t ) IF (ASSOCIATED(ext_data%atm%gp_count_t))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%lc_class_t ) IF (ASSOCIATED(ext_data%atm%lc_class_t))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%z0_lcc_min ) IF (ASSOCIATED(ext_data%atm%z0_lcc_min))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%z0_lcc ) IF (ASSOCIATED(ext_data%atm%z0_lcc))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%sso_stdh_raw ) IF (ASSOCIATED(ext_data%atm%sso_stdh_raw))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%frac_t ) IF (ASSOCIATED(ext_data%atm%frac_t))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%plcov_t ) IF (ASSOCIATED(ext_data%atm%plcov_t))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%sai_t ) IF (ASSOCIATED(ext_data%atm%sai_t))
    !$ser verbatim  !$ACC UPDATE HOST( ext_data%atm%fr_land ) IF (ASSOCIATED(ext_data%atm%fr_land))
#endif
    !$ser verbatim   CALL datetimeToString(time_config%tc_current_date, date)
    !$ser verbatim   CALL init('icon')
    !$ser savepoint nwp_turbtrans_interface-input jg=jg nproma=nproma nlev=nlev date=TRIM(date)
#if defined(SERIALIZE_CREATE_REFERENCE)
    !$ser mode       write
#elif defined(SERIALIZE_READ_REFERENCE)
    !$ser mode       read
#elif defined(SERIALIZE_PERTURB_REFERENCE)
    !$ser mode       read-perturb
#else
    !$ser verbatim   CALL finish('nwp_turbtrans_interface-input', 'SERIALIZATION MODE IS NOT SET')
#endif
    !$ser data turbtrans_interface_p_metrics_mc=p_metrics%z_mc(:,:,:) IF (ASSOCIATED(p_metrics%z_mc))
    !$ser data turbtrans_interface_p_metrics_ifc=p_metrics%z_ifc(:,:,:) IF (ASSOCIATED(p_metrics%z_ifc))
    !$ser data turbtrans_interface_p_metrics_agl=p_metrics%geopot_agl(:,:,:) IF (ASSOCIATED(p_metrics%geopot_agl))
    !$ser data turbtrans_interface_p_metrics_agl_ifc=p_metrics%geopot_agl_ifc(:,:,:) IF (ASSOCIATED(p_metrics%geopot_agl_ifc))
    !$ser data turbtrans_interface_p_metrics_mask_mtnpoints_g=p_metrics%mask_mtnpoints_g(:,:) IF (ASSOCIATED(p_metrics%mask_mtnpoints_g))
    !$ser data turbtrans_interface_p_prog_exner=p_prog%exner(:,:,:) IF (ASSOCIATED(p_prog%exner))
    !$ser data turbtrans_interface_p_prog_rcf_tracer_iqv=p_prog_rcf%tracer(:,:,:,iqv) IF (ASSOCIATED(p_prog_rcf%tracer))
    !$ser data turbtrans_interface_p_prog_rcf_tracer_iqc=p_prog_rcf%tracer(:,:,:,iqc) IF (ASSOCIATED(p_prog_rcf%tracer))
    !$ser data turbtrans_interface_p_prog_rcf_tke=p_prog_rcf%tke(:,:,:) IF (ASSOCIATED(p_prog_rcf%tke))
    !$ser data turbtrans_interface_p_diag_temp=p_diag%temp(:,:,:) IF (ASSOCIATED(p_diag%temp))
    !$ser data turbtrans_interface_p_diag_pres=p_diag%pres(:,:,:) IF (ASSOCIATED(p_diag%pres))
    !$ser data turbtrans_interface_p_diag_pres_sfc=p_diag%pres_sfc(:,:) IF (ASSOCIATED(p_diag%pres_sfc))
    !$ser data turbtrans_interface_p_diag_pres_ifc=p_diag%pres_ifc(:,:,:) IF (ASSOCIATED(p_diag%pres_ifc))
    !$ser data turbtrans_interface_p_diag_u=p_diag%u(:,:,:) IF (ASSOCIATED(p_diag%u))
    !$ser data turbtrans_interface_p_diag_v=p_diag%v(:,:,:) IF (ASSOCIATED(p_diag%v))
    !$ser data turbtrans_interface_prm_diag_gz0=prm_diag%gz0(:,:) IF (ASSOCIATED(prm_diag%gz0))
    !$ser data turbtrans_interface_prm_diag_gz0_t=prm_diag%gz0_t(:,:,:) IF (ASSOCIATED(prm_diag%gz0_t))
    !$ser data turbtrans_interface_prm_diag_tcm_t=prm_diag%tcm_t(:,:,:) IF (ASSOCIATED(prm_diag%tcm_t))
    !$ser data turbtrans_interface_prm_diag_tch_t=prm_diag%tch_t(:,:,:) IF (ASSOCIATED(prm_diag%tch_t))
    !$ser data turbtrans_interface_prm_diag_tvm_t=prm_diag%tvm_t(:,:,:) IF (ASSOCIATED(prm_diag%tvm_t))
    !$ser data turbtrans_interface_prm_diag_tvh_t=prm_diag%tvh_t(:,:,:) IF (ASSOCIATED(prm_diag%tvh_t))
    !$ser data turbtrans_interface_prm_diag_tcm=prm_diag%tcm(:,:) IF (ASSOCIATED(prm_diag%tcm))
    !$ser data turbtrans_interface_prm_diag_tch=prm_diag%tch(:,:) IF (ASSOCIATED(prm_diag%tch))
    !$ser data turbtrans_interface_prm_diag_tvm=prm_diag%tvm(:,:) IF (ASSOCIATED(prm_diag%tvm))
    !$ser data turbtrans_interface_prm_diag_tvh=prm_diag%tvh(:,:) IF (ASSOCIATED(prm_diag%tvh))
    !$ser data turbtrans_interface_prm_diag_tfm=prm_diag%tfm(:,:) IF (ASSOCIATED(prm_diag%tfm))
    !$ser data turbtrans_interface_prm_diag_tfh=prm_diag%tfh(:,:) IF (ASSOCIATED(prm_diag%tfh))
    !$ser data turbtrans_interface_prm_diag_tfv_t=prm_diag%tfv_t(:,:,:) IF (ASSOCIATED(prm_diag%tfv_t))
    !$ser data turbtrans_interface_prm_diag_tkr_t=prm_diag%tkr_t(:,:,:) IF (ASSOCIATED(prm_diag%tkr_t))
    !$ser data turbtrans_interface_prm_diag_tkvm=prm_diag%tkvm(:,:,:) IF (ASSOCIATED(prm_diag%tkvm))
    !$ser data turbtrans_interface_prm_diag_tkvm_t=prm_diag%tkvm_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tkvm_s_t))
    !$ser data turbtrans_interface_prm_diag_tkvh_t=prm_diag%tkvh_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tkvh_s_t))
    !$ser data turbtrans_interface_prm_diag_tkvh=prm_diag%tkvh(:,:,:) IF (ASSOCIATED(prm_diag%tkvh))
    !$ser data turbtrans_interface_prm_diag_rcld=prm_diag%rcld(:,:,:) IF (ASSOCIATED(prm_diag%rcld))
    !$ser data turbtrans_interface_prm_diag_ktop_envel=prm_diag%ktop_envel(:,:) IF (ASSOCIATED(prm_diag%ktop_envel))
    !$ser data turbtrans_interface_prm_diag_shfl_s_t=prm_diag%shfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%shfl_s_t))
    !$ser data turbtrans_interface_prm_diag_qhfl_s_t=prm_diag%qhfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%qhfl_s_t))
    !$ser data turbtrans_interface_prm_diag_umfl_s_t=prm_diag%umfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%umfl_s_t))
    !$ser data turbtrans_interface_prm_diag_vmfl_s_t=prm_diag%vmfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%vmfl_s_t))
    !$ser data turbtrans_interface_prm_diag_lhfl_s_t=prm_diag%lhfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%lhfl_s_t))
    !$ser data turbtrans_interface_prm_diag_shfl_s=prm_diag%shfl_s(:,:) IF (ASSOCIATED(prm_diag%shfl_s))
    !$ser data turbtrans_interface_prm_diag_qhfl_s=prm_diag%qhfl_s(:,:) IF (ASSOCIATED(prm_diag%qhfl_s))
    !$ser data turbtrans_interface_prm_diag_umfl_s=prm_diag%umfl_s(:,:) IF (ASSOCIATED(prm_diag%umfl_s))
    !$ser data turbtrans_interface_prm_diag_vmfl_s=prm_diag%vmfl_s(:,:) IF (ASSOCIATED(prm_diag%vmfl_s))
    !$ser data turbtrans_interface_prm_diag_lhfl_s=prm_diag%lhfl_s(:,:) IF (ASSOCIATED(prm_diag%lhfl_s))
    !$ser data turbtrans_interface_prm_diag_u_10m=prm_diag%u_10m(:,:) IF (ASSOCIATED(prm_diag%u_10m))
    !$ser data turbtrans_interface_prm_diag_v_10m=prm_diag%v_10m(:,:) IF (ASSOCIATED(prm_diag%v_10m))
    !$ser data turbtrans_interface_prm_diag_u_10m_t=prm_diag%u_10m_t(:,:,:) IF (ASSOCIATED(prm_diag%u_10m_t))
    !$ser data turbtrans_interface_prm_diag_v_10m_t=prm_diag%v_10m_t(:,:,:) IF (ASSOCIATED(prm_diag%v_10m_t))
    !$ser data turbtrans_interface_prm_diag_tmax_2m=prm_diag%tmax_2m(:,:) IF (ASSOCIATED(prm_diag%tmax_2m))
    !$ser data turbtrans_interface_prm_diag_tmin_2m=prm_diag%tmin_2m(:,:) IF (ASSOCIATED(prm_diag%tmin_2m))
    !$ser data turbtrans_interface_prm_diag_t_2m=prm_diag%t_2m(:,:) IF (ASSOCIATED(prm_diag%t_2m))
    !$ser data turbtrans_interface_prm_diag_qv_2m=prm_diag%qv_2m(:,:) IF (ASSOCIATED(prm_diag%qv_2m))
    !$ser data turbtrans_interface_prm_diag_td_2m=prm_diag%td_2m(:,:) IF (ASSOCIATED(prm_diag%td_2m))
    !$ser data turbtrans_interface_prm_diag_rh_2m=prm_diag%rh_2m(:,:) IF (ASSOCIATED(prm_diag%rh_2m))
    !$ser data turbtrans_interface_prm_diag_tvs_s_t=prm_diag%tvs_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tvs_s_t))
    !$ser data turbtrans_interface_prm_diag_tfv=prm_diag%tfv(:,:) IF (ASSOCIATED(prm_diag%tfv))
    !$ser data turbtrans_interface_prm_diag_tkr=prm_diag%tkr(:,:) IF (ASSOCIATED(prm_diag%tkr))
    !$ser data turbtrans_interface_prm_diag_t_2m_land=prm_diag%t_2m_land(:,:) IF (ASSOCIATED(prm_diag%t_2m_land))
    !$ser data turbtrans_interface_prm_diag_td_2m_land=prm_diag%td_2m_land(:,:) IF (ASSOCIATED(prm_diag%td_2m_land))
    !$ser data turbtrans_interface_prm_diag_rh_2m_land=prm_diag%rh_2m_land(:,:) IF (ASSOCIATED(prm_diag%rh_2m_land))
    !$ser data turbtrans_interface_prm_diag_dyn_gust=prm_diag%dyn_gust(:,:) IF (ASSOCIATED(prm_diag%dyn_gust))
    !$ser data turbtrans_interface_wtr_prog_new_h_ice=wtr_prog_new%h_ice(:,:) IF (ASSOCIATED(wtr_prog_new%h_ice))
    !$ser data turbtrans_interface_lnd_prog_new_t_g=lnd_prog_new%t_g(:,:) IF (ASSOCIATED(lnd_prog_new%t_g))
    !$ser data turbtrans_interface_lnd_prog_new_t_g_t=lnd_prog_new%t_g_t(:,:,:) IF (ASSOCIATED(lnd_prog_new%t_g_t))
    !$ser data turbtrans_interface_lnd_diag_qv_s=lnd_diag%qv_s(:,:) IF (ASSOCIATED(lnd_diag%qv_s))
    !$ser data turbtrans_interface_lnd_diag_qv_s_t=lnd_diag%qv_s_t(:,:,:) IF (ASSOCIATED(lnd_diag%qv_s_t))
    !$ser data turbtrans_interface_lnd_diag_snowfrac_t=lnd_diag%snowfrac_t(:,:,:) IF (ASSOCIATED(lnd_diag%snowfrac_t))
    !$ser data turbtrans_interface_lnd_diag_snowfrac_lc_t=lnd_diag%snowfrac_lc_t(:,:,:) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t))
    !$ser data turbtrans_interface_ext_data_idx_lst_t=ext_data%atm%idx_lst_t IF (ASSOCIATED(ext_data%atm%idx_lst_t))
    !$ser data turbtrans_interface_ext_data_gp_count_t=ext_data%atm%gp_count_t IF (ASSOCIATED(ext_data%atm%gp_count_t))
    !$ser data turbtrans_interface_ext_data_lc_class_t=ext_data%atm%lc_class_t IF (ASSOCIATED(ext_data%atm%lc_class_t))
    !$ser data turbtrans_interface_ext_data_z0_lcc_min=ext_data%atm%z0_lcc_min IF (ASSOCIATED(ext_data%atm%z0_lcc_min))
    !$ser data turbtrans_interface_ext_data_z0_lcc=ext_data%atm%z0_lcc IF (ASSOCIATED(ext_data%atm%z0_lcc))
    !$ser data turbtrans_interface_ext_data_sso_stdh_raw=ext_data%atm%sso_stdh_raw IF (ASSOCIATED(ext_data%atm%sso_stdh_raw))
    !$ser data turbtrans_interface_ext_data_frac_t=ext_data%atm%frac_t IF (ASSOCIATED(ext_data%atm%frac_t))
    !$ser data turbtrans_interface_ext_data_plcov_t=ext_data%atm%plcov_t IF (ASSOCIATED(ext_data%atm%plcov_t))
    !$ser data turbtrans_interface_ext_data_sai_t=ext_data%atm%sai_t IF (ASSOCIATED(ext_data%atm%sai_t))
    !$ser data turbtrans_interface_ext_data_fr_land=ext_data%atm%fr_land IF (ASSOCIATED(ext_data%atm%fr_land))
#if defined( _OPENACC )
#if defined(SERIALIZE_READ_REFERENCE) || defined(SERIALIZE_PERTURB_REFERENCE)
    !$ser verbatim CALL warning('GPU:mo_ser_nwp_tutra:turbtrans_interface-input','GPU DEVICE synchronization forced by serialization!')
    !$ser verbatim  !$ACC UPDATE DEVICE( p_metrics%z_mc ) IF( ASSOCIATED(p_metrics%z_mc) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_metrics%z_ifc ) IF( ASSOCIATED(p_metrics%z_ifc) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_metrics%geopot_agl ) IF( ASSOCIATED(p_metrics%geopot_agl) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_metrics%geopot_agl_ifc ) IF( ASSOCIATED(p_metrics%geopot_agl_ifc) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_metrics%mask_mtnpoints_g ) IF( ASSOCIATED(p_metrics%mask_mtnpoints_g) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_prog%exner ) IF( ASSOCIATED(p_prog%exner) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_prog_rcf%tracer ) IF( ASSOCIATED(p_prog_rcf%tracer) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_prog_rcf%tke ) IF( ASSOCIATED(p_prog_rcf%tke) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_diag%temp ) IF( ASSOCIATED(p_diag%temp) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_diag%pres ) IF( ASSOCIATED(p_diag%pres) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_diag%pres_sfc ) IF( ASSOCIATED(p_diag%pres_sfc) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_diag%pres_ifc ) IF( ASSOCIATED(p_diag%pres_ifc) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_diag%u ) IF( ASSOCIATED(p_diag%u) )
    !$ser verbatim  !$ACC UPDATE DEVICE( p_diag%v ) IF( ASSOCIATED(p_diag%v) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%gz0 ) IF( ASSOCIATED(prm_diag%gz0) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%gz0_t ) IF( ASSOCIATED(prm_diag%gz0_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tcm_t ) IF( ASSOCIATED(prm_diag%tcm_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tch_t ) IF( ASSOCIATED(prm_diag%tch_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tvm_t ) IF( ASSOCIATED(prm_diag%tvm_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tvh_t ) IF( ASSOCIATED(prm_diag%tvh_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tcm ) IF( ASSOCIATED(prm_diag%tcm) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tch ) IF( ASSOCIATED(prm_diag%tch) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tvm ) IF( ASSOCIATED(prm_diag%tvm) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tvh ) IF( ASSOCIATED(prm_diag%tvh) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tfm ) IF( ASSOCIATED(prm_diag%tfm) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tfh ) IF( ASSOCIATED(prm_diag%tfh) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tfv_t ) IF( ASSOCIATED(prm_diag%tfv_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tkr_t ) IF( ASSOCIATED(prm_diag%tkr_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tfv ) IF( ASSOCIATED(prm_diag%tfv) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tkr ) IF( ASSOCIATED(prm_diag%tkr) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tkvm ) IF( ASSOCIATED(prm_diag%tkvm) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tkvm_s_t ) IF( ASSOCIATED(prm_diag%tkvm_s_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tkvh_s_t ) IF( ASSOCIATED(prm_diag%tkvh_s_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tkvh ) IF( ASSOCIATED(prm_diag%tkvh) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%rcld ) IF( ASSOCIATED(prm_diag%rcld) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%ktop_envel ) IF( ASSOCIATED(prm_diag%ktop_envel) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%shfl_s_t ) IF( ASSOCIATED(prm_diag%shfl_s_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%qhfl_s_t ) IF( ASSOCIATED(prm_diag%qhfl_s_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%umfl_s_t ) IF( ASSOCIATED(prm_diag%umfl_s_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%vmfl_s_t ) IF( ASSOCIATED(prm_diag%vmfl_s_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%lhfl_s_t ) IF( ASSOCIATED(prm_diag%lhfl_s_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%u_10m ) IF( ASSOCIATED(prm_diag%u_10m) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%v_10m ) IF( ASSOCIATED(prm_diag%v_10m) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%u_10m_t ) IF( ASSOCIATED(prm_diag%u_10m_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%v_10m_t ) IF( ASSOCIATED(prm_diag%v_10m_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tmax_2m ) IF( ASSOCIATED(prm_diag%tmax_2m) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tmin_2m ) IF( ASSOCIATED(prm_diag%tmin_2m) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%t_2m ) IF( ASSOCIATED(prm_diag%t_2m) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%qv_2m ) IF( ASSOCIATED(prm_diag%qv_2m) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%td_2m ) IF( ASSOCIATED(prm_diag%td_2m) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%rh_2m ) IF( ASSOCIATED(prm_diag%rh_2m) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%tvs_s_t ) IF( ASSOCIATED(prm_diag%tvs_s_t) )
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%t_2m_land ) IF (ASSOCIATED(prm_diag%t_2m_land))
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%td_2m_land ) IF (ASSOCIATED(prm_diag%td_2m_land))
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%rh_2m_land ) IF (ASSOCIATED(prm_diag%rh_2m_land))
    !$ser verbatim  !$ACC UPDATE DEVICE( prm_diag%dyn_gust ) IF (ASSOCIATED(prm_diag%dyn_gust))
    !$ser verbatim  !$ACC UPDATE DEVICE( wtr_prog_new%h_ice ) IF (ASSOCIATED(wtr_prog_new%h_ice))
    !$ser verbatim  !$ACC UPDATE DEVICE( lnd_prog_new%t_g ) IF (ASSOCIATED(lnd_prog_new%t_g))
    !$ser verbatim  !$ACC UPDATE DEVICE( lnd_prog_new%t_g_t ) IF (ASSOCIATED(lnd_prog_new%t_g_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( lnd_diag%qv_s ) IF (ASSOCIATED(lnd_diag%qv_s))
    !$ser verbatim  !$ACC UPDATE DEVICE( lnd_diag%qv_s_t ) IF (ASSOCIATED(lnd_diag%qv_s_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( lnd_diag%snowfrac_t ) IF (ASSOCIATED(lnd_diag%snowfrac_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( lnd_diag%snowfrac_lc_t ) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%idx_lst_t ) IF (ASSOCIATED(ext_data%atm%idx_lst_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%gp_count_t ) IF (ASSOCIATED(ext_data%atm%gp_count_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%lc_class_t ) IF (ASSOCIATED(ext_data%atm%lc_class_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%z0_lcc_min ) IF (ASSOCIATED(ext_data%atm%z0_lcc_min))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%z0_lcc ) IF (ASSOCIATED(ext_data%atm%z0_lcc))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%sso_stdh_raw ) IF (ASSOCIATED(ext_data%atm%sso_stdh_raw))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%frac_t ) IF (ASSOCIATED(ext_data%atm%frac_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%plcov_t ) IF (ASSOCIATED(ext_data%atm%plcov_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%sai_t ) IF (ASSOCIATED(ext_data%atm%sai_t))
    !$ser verbatim  !$ACC UPDATE DEVICE( ext_data%atm%fr_land ) IF (ASSOCIATED(ext_data%atm%fr_land))
#endif
#endif
    !$ser verbatim ENDIF

  END SUBROUTINE serialize_turbtrans_interface_input

  SUBROUTINE serialize_turbtrans_interface_output(jg, nproma, nlev, &
                                                  p_prog, p_prog_rcf, p_diag, prm_diag, &
                                                  lnd_prog_new, lnd_diag)
    INTEGER, INTENT(IN)    :: jg, nproma, nlev
    TYPE(t_nh_prog),  TARGET, INTENT(INOUT) :: p_prog          !<the prog vars
    TYPE(t_nh_prog),          INTENT(INOUT) :: p_prog_rcf      !< current time levels
    TYPE(t_nh_diag),  TARGET, INTENT(INOUT) :: p_diag
    TYPE(t_nwp_phy_diag),     INTENT(INOUT) :: prm_diag        !< atm phys vars
    TYPE(t_lnd_prog),         INTENT(INOUT) :: lnd_prog_new    !< prog vars for sfc
    TYPE(t_lnd_diag),         INTENT(INOUT) :: lnd_diag        !< diag vars for sfc

    CHARACTER(LEN=MAX_DATETIME_STR_LEN) :: date
    INTEGER, SAVE :: ser_count = 0

    !$ser verbatim ser_count = ser_count + 1
    !$ser verbatim IF(ser_count <= ser_turbtrans_interface) THEN
    !$ser verbatim   CALL warning('SER:mo_ser_nwp_tutra:turbtrans_interface-output','Serialization is active!')
#if defined( _OPENACC )
    !$ser verbatim   CALL warning('GPU:mo_ser_nwp_tutra:turbtrans_interface-output','GPU HOST synchronization forced by serialization!')
    !$ser verbatim  !$ACC UPDATE HOST( p_prog%exner ) IF( ASSOCIATED(p_prog%exner) )
    !$ser verbatim  !$ACC UPDATE HOST( p_prog_rcf%tracer ) IF( ASSOCIATED(p_prog_rcf%tracer) )
    !$ser verbatim  !$ACC UPDATE HOST( p_prog_rcf%tke ) IF( ASSOCIATED(p_prog_rcf%tke) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%temp ) IF( ASSOCIATED(p_diag%temp) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%pres ) IF( ASSOCIATED(p_diag%pres) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%pres_sfc ) IF( ASSOCIATED(p_diag%pres_sfc) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%pres_ifc ) IF( ASSOCIATED(p_diag%pres_ifc) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%u ) IF( ASSOCIATED(p_diag%u) )
    !$ser verbatim  !$ACC UPDATE HOST( p_diag%v ) IF( ASSOCIATED(p_diag%v) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%gz0 ) IF( ASSOCIATED(prm_diag%gz0) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%gz0_t ) IF( ASSOCIATED(prm_diag%gz0_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tcm_t ) IF( ASSOCIATED(prm_diag%tcm_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tch_t ) IF( ASSOCIATED(prm_diag%tch_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvm_t ) IF( ASSOCIATED(prm_diag%tvm_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvh_t ) IF( ASSOCIATED(prm_diag%tvh_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tcm ) IF( ASSOCIATED(prm_diag%tcm) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tch ) IF( ASSOCIATED(prm_diag%tch) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvm ) IF( ASSOCIATED(prm_diag%tvm) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvh ) IF( ASSOCIATED(prm_diag%tvh) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tfm ) IF( ASSOCIATED(prm_diag%tfm) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tfh ) IF( ASSOCIATED(prm_diag%tfh) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tfv_t ) IF( ASSOCIATED(prm_diag%tfv_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkr_t ) IF( ASSOCIATED(prm_diag%tkr_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tfv ) IF( ASSOCIATED(prm_diag%tfv) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkr ) IF( ASSOCIATED(prm_diag%tkr) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkvm ) IF( ASSOCIATED(prm_diag%tkvm) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkvm_s_t ) IF( ASSOCIATED(prm_diag%tkvm_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkvh_s_t ) IF( ASSOCIATED(prm_diag%tkvh_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tkvh ) IF( ASSOCIATED(prm_diag%tkvh) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%rcld ) IF( ASSOCIATED(prm_diag%rcld) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%ktop_envel ) IF( ASSOCIATED(prm_diag%ktop_envel) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%shfl_s_t ) IF( ASSOCIATED(prm_diag%shfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%qhfl_s_t ) IF( ASSOCIATED(prm_diag%qhfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%umfl_s_t ) IF( ASSOCIATED(prm_diag%umfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%vmfl_s_t ) IF( ASSOCIATED(prm_diag%vmfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%lhfl_s_t ) IF( ASSOCIATED(prm_diag%lhfl_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%u_10m ) IF( ASSOCIATED(prm_diag%u_10m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%v_10m ) IF( ASSOCIATED(prm_diag%v_10m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%u_10m_t ) IF( ASSOCIATED(prm_diag%u_10m_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%v_10m_t ) IF( ASSOCIATED(prm_diag%v_10m_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tmax_2m ) IF( ASSOCIATED(prm_diag%tmax_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tmin_2m ) IF( ASSOCIATED(prm_diag%tmin_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%t_2m ) IF( ASSOCIATED(prm_diag%t_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%qv_2m ) IF( ASSOCIATED(prm_diag%qv_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%td_2m ) IF( ASSOCIATED(prm_diag%td_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%rh_2m ) IF( ASSOCIATED(prm_diag%rh_2m) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%tvs_s_t ) IF( ASSOCIATED(prm_diag%tvs_s_t) )
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%t_2m_land ) IF (ASSOCIATED(prm_diag%t_2m_land))
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%td_2m_land ) IF (ASSOCIATED(prm_diag%td_2m_land))
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%rh_2m_land ) IF (ASSOCIATED(prm_diag%rh_2m_land))
    !$ser verbatim  !$ACC UPDATE HOST( prm_diag%dyn_gust ) IF (ASSOCIATED(prm_diag%dyn_gust))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_prog_new%t_g ) IF (ASSOCIATED(lnd_prog_new%t_g))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_prog_new%t_g_t ) IF (ASSOCIATED(lnd_prog_new%t_g_t))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_diag%qv_s ) IF (ASSOCIATED(lnd_diag%qv_s))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_diag%qv_s_t ) IF (ASSOCIATED(lnd_diag%qv_s_t))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_diag%snowfrac_t ) IF (ASSOCIATED(lnd_diag%snowfrac_t))
    !$ser verbatim  !$ACC UPDATE HOST( lnd_diag%snowfrac_lc_t ) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t))
#endif
    !$ser verbatim   CALL datetimeToString(time_config%tc_current_date, date)
    !$ser verbatim   CALL init('icon')
    !$ser savepoint nwp_turbtrans_interface-output jg=jg nproma=nproma nlev=nlev date=TRIM(date)
    !$ser mode write
    !$ser data turbtrans_interface_p_prog_exner=p_prog%exner(:,:,:) IF (ASSOCIATED(p_prog%exner))
    !$ser data turbtrans_interface_p_prog_rcf_tracer_iqv=p_prog_rcf%tracer(:,:,:,iqv) IF (ASSOCIATED(p_prog_rcf%tracer))
    !$ser data turbtrans_interface_p_prog_rcf_tracer_iqc=p_prog_rcf%tracer(:,:,:,iqc) IF (ASSOCIATED(p_prog_rcf%tracer))
    !$ser data turbtrans_interface_p_prog_rcf_tke=p_prog_rcf%tke(:,:,:) IF (ASSOCIATED(p_prog_rcf%tke))
    !$ser data turbtrans_interface_p_diag_temp=p_diag%temp(:,:,:) IF (ASSOCIATED(p_diag%temp))
    !$ser data turbtrans_interface_p_diag_pres=p_diag%pres(:,:,:) IF (ASSOCIATED(p_diag%pres))
    !$ser data turbtrans_interface_p_diag_pres_sfc=p_diag%pres_sfc(:,:) IF (ASSOCIATED(p_diag%pres_sfc))
    !$ser data turbtrans_interface_p_diag_pres_ifc=p_diag%pres_ifc(:,:,:) IF (ASSOCIATED(p_diag%pres_ifc))
    !$ser data turbtrans_interface_p_diag_u=p_diag%u(:,:,:) IF (ASSOCIATED(p_diag%u))
    !$ser data turbtrans_interface_p_diag_v=p_diag%v(:,:,:) IF (ASSOCIATED(p_diag%v))
    !$ser data turbtrans_interface_prm_diag_gz0=prm_diag%gz0(:,:) IF (ASSOCIATED(prm_diag%gz0))
    !$ser data turbtrans_interface_prm_diag_gz0_t=prm_diag%gz0_t(:,:,:) IF (ASSOCIATED(prm_diag%gz0_t))
    !$ser data turbtrans_interface_prm_diag_tcm_t=prm_diag%tcm_t(:,:,:) IF (ASSOCIATED(prm_diag%tcm_t))
    !$ser data turbtrans_interface_prm_diag_tch_t=prm_diag%tch_t(:,:,:) IF (ASSOCIATED(prm_diag%tch_t))
    !$ser data turbtrans_interface_prm_diag_tvm_t=prm_diag%tvm_t(:,:,:) IF (ASSOCIATED(prm_diag%tvm_t))
    !$ser data turbtrans_interface_prm_diag_tvh_t=prm_diag%tvh_t(:,:,:) IF (ASSOCIATED(prm_diag%tvh_t))
    !$ser data turbtrans_interface_prm_diag_tcm=prm_diag%tcm(:,:) IF (ASSOCIATED(prm_diag%tcm))
    !$ser data turbtrans_interface_prm_diag_tch=prm_diag%tch(:,:) IF (ASSOCIATED(prm_diag%tch))
    !$ser data turbtrans_interface_prm_diag_tvm=prm_diag%tvm(:,:) IF (ASSOCIATED(prm_diag%tvm))
    !$ser data turbtrans_interface_prm_diag_tvh=prm_diag%tvh(:,:) IF (ASSOCIATED(prm_diag%tvh))
    !$ser data turbtrans_interface_prm_diag_tfm=prm_diag%tfm(:,:) IF (ASSOCIATED(prm_diag%tfm))
    !$ser data turbtrans_interface_prm_diag_tfh=prm_diag%tfh(:,:) IF (ASSOCIATED(prm_diag%tfh))
    !$ser data turbtrans_interface_prm_diag_tfv_t=prm_diag%tfv_t(:,:,:) IF (ASSOCIATED(prm_diag%tfv_t))
    !$ser data turbtrans_interface_prm_diag_tkr_t=prm_diag%tkr_t(:,:,:) IF (ASSOCIATED(prm_diag%tkr_t))
    !$ser data turbtrans_interface_prm_diag_tkvm=prm_diag%tkvm(:,:,:) IF (ASSOCIATED(prm_diag%tkvm))
    !$ser data turbtrans_interface_prm_diag_tkvm_t=prm_diag%tkvm_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tkvm_s_t))
    !$ser data turbtrans_interface_prm_diag_tkvh_t=prm_diag%tkvh_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tkvh_s_t))
    !$ser data turbtrans_interface_prm_diag_tkvh=prm_diag%tkvh(:,:,:) IF (ASSOCIATED(prm_diag%tkvh))
    !$ser data turbtrans_interface_prm_diag_rcld=prm_diag%rcld(:,:,:) IF (ASSOCIATED(prm_diag%rcld))
    !$ser data turbtrans_interface_prm_diag_ktop_envel=prm_diag%ktop_envel(:,:) IF (ASSOCIATED(prm_diag%ktop_envel))
    !$ser data turbtrans_interface_prm_diag_shfl_s_t=prm_diag%shfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%shfl_s_t))
    !$ser data turbtrans_interface_prm_diag_qhfl_s_t=prm_diag%qhfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%qhfl_s_t))
    !$ser data turbtrans_interface_prm_diag_umfl_s_t=prm_diag%umfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%umfl_s_t))
    !$ser data turbtrans_interface_prm_diag_vmfl_s_t=prm_diag%vmfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%vmfl_s_t))
    !$ser data turbtrans_interface_prm_diag_lhfl_s_t=prm_diag%lhfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%lhfl_s_t))
    !$ser data turbtrans_interface_prm_diag_shfl_s=prm_diag%shfl_s(:,:) IF (ASSOCIATED(prm_diag%shfl_s))
    !$ser data turbtrans_interface_prm_diag_qhfl_s=prm_diag%qhfl_s(:,:) IF (ASSOCIATED(prm_diag%qhfl_s))
    !$ser data turbtrans_interface_prm_diag_umfl_s=prm_diag%umfl_s(:,:) IF (ASSOCIATED(prm_diag%umfl_s))
    !$ser data turbtrans_interface_prm_diag_vmfl_s=prm_diag%vmfl_s(:,:) IF (ASSOCIATED(prm_diag%vmfl_s))
    !$ser data turbtrans_interface_prm_diag_lhfl_s=prm_diag%lhfl_s(:,:) IF (ASSOCIATED(prm_diag%lhfl_s))
    !$ser data turbtrans_interface_prm_diag_u_10m=prm_diag%u_10m(:,:) IF (ASSOCIATED(prm_diag%u_10m))
    !$ser data turbtrans_interface_prm_diag_v_10m=prm_diag%v_10m(:,:) IF (ASSOCIATED(prm_diag%v_10m))
    !$ser data turbtrans_interface_prm_diag_u_10m_t=prm_diag%u_10m_t(:,:,:) IF (ASSOCIATED(prm_diag%u_10m_t))
    !$ser data turbtrans_interface_prm_diag_v_10m_t=prm_diag%v_10m_t(:,:,:) IF (ASSOCIATED(prm_diag%v_10m_t))
    !$ser data turbtrans_interface_prm_diag_tmax_2m=prm_diag%tmax_2m(:,:) IF (ASSOCIATED(prm_diag%tmax_2m))
    !$ser data turbtrans_interface_prm_diag_tmin_2m=prm_diag%tmin_2m(:,:) IF (ASSOCIATED(prm_diag%tmin_2m))
    !$ser data turbtrans_interface_prm_diag_t_2m=prm_diag%t_2m(:,:) IF (ASSOCIATED(prm_diag%t_2m))
    !$ser data turbtrans_interface_prm_diag_qv_2m=prm_diag%qv_2m(:,:) IF (ASSOCIATED(prm_diag%qv_2m))
    !$ser data turbtrans_interface_prm_diag_td_2m=prm_diag%td_2m(:,:) IF (ASSOCIATED(prm_diag%td_2m))
    !$ser data turbtrans_interface_prm_diag_rh_2m=prm_diag%rh_2m(:,:) IF (ASSOCIATED(prm_diag%rh_2m))
    !$ser data turbtrans_interface_prm_diag_tvs_s_t=prm_diag%tvs_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tvs_s_t))
    !$ser data turbtrans_interface_prm_diag_tfv=prm_diag%tfv(:,:) IF (ASSOCIATED(prm_diag%tfv))
    !$ser data turbtrans_interface_prm_diag_tkr=prm_diag%tkr(:,:) IF (ASSOCIATED(prm_diag%tkr))
    !$ser data turbtrans_interface_prm_diag_t_2m_land=prm_diag%t_2m_land(:,:) IF (ASSOCIATED(prm_diag%t_2m_land))
    !$ser data turbtrans_interface_prm_diag_td_2m_land=prm_diag%td_2m_land(:,:) IF (ASSOCIATED(prm_diag%td_2m_land))
    !$ser data turbtrans_interface_prm_diag_rh_2m_land=prm_diag%rh_2m_land(:,:) IF (ASSOCIATED(prm_diag%rh_2m_land))
    !$ser data turbtrans_interface_prm_diag_dyn_gust=prm_diag%dyn_gust(:,:) IF (ASSOCIATED(prm_diag%dyn_gust))
    !$ser data turbtrans_interface_lnd_prog_new_t_g=lnd_prog_new%t_g(:,:) IF (ASSOCIATED(lnd_prog_new%t_g))
    !$ser data turbtrans_interface_lnd_prog_new_t_g_t=lnd_prog_new%t_g_t(:,:,:) IF (ASSOCIATED(lnd_prog_new%t_g_t))
    !$ser data turbtrans_interface_lnd_diag_qv_s=lnd_diag%qv_s(:,:) IF (ASSOCIATED(lnd_diag%qv_s))
    !$ser data turbtrans_interface_lnd_diag_qv_s_t=lnd_diag%qv_s_t(:,:,:) IF (ASSOCIATED(lnd_diag%qv_s_t))
    !$ser data turbtrans_interface_lnd_diag_snowfrac_t=lnd_diag%snowfrac_t(:,:,:) IF (ASSOCIATED(lnd_diag%snowfrac_t))
    !$ser data turbtrans_interface_lnd_diag_snowfrac_lc_t=lnd_diag%snowfrac_lc_t(:,:,:) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t))

    !$ser verbatim ENDIF

  END SUBROUTINE serialize_turbtrans_interface_output

END MODULE mo_ser_nwp_tutra
