!--------------------------------------------------------------------
!
! Serialization routine for NWP physics
!
!--------------------------------------------------------------------

MODULE mo_ser_nh_interface_nwp

  USE mo_kind,               ONLY: vp, wp
  USE mo_exception,          ONLY: warning, finish
  USE mo_ser_common,         ONLY: init
  USE mtime,                 ONLY: datetimeToString, MAX_DATETIME_STR_LEN
  USE mo_time_config,        ONLY: time_config
  USE mo_nonhydro_types,     ONLY: t_nh_prog, t_nh_diag, t_nh_metrics
  USE mo_nwp_phy_types,      ONLY: t_nwp_phy_diag, t_nwp_phy_tend
  USE mo_nwp_lnd_types,      ONLY: t_lnd_prog, t_wtr_prog, t_lnd_diag
  USE mo_run_config,         ONLY: iqv, iqc, iqi, iqnc, iqni, iqns, iqs, &
                                   iqtke, iqr, iqni_nuc, iqg, iqh, iqnr, &
                                   iqng, iqnh
  USE mo_advection_config,   ONLY: advection_config
  USE mo_ext_data_types,     ONLY: t_external_data
  USE mo_atm_phy_nwp_config, ONLY: atm_phy_nwp_config, iprog_aero
  USE mo_ser_nml,            ONLY: ser_interface_nwp
  IMPLICIT NONE

  PUBLIC :: serialize_nh_interface_nwp_input
  PUBLIC :: serialize_nh_interface_nwp_output

  CONTAINS

  SUBROUTINE serialize_nh_interface_nwp_input(jg, nproma, nlev, pt_prog, &
                                              pt_prog_rcf, pt_prog_now_rcf, pt_diag, p_metrics, &
                                              prm_diag, prm_nwp_tend, wtr_prog_now, wtr_prog_new, &
                                              lnd_prog_now, lnd_prog_new, lnd_diag, ext_data, lcpu_only)
    INTEGER, INTENT(IN)    :: jg, nproma, nlev
    TYPE(t_nh_prog), TARGET, INTENT(INOUT) :: pt_prog 
    TYPE(t_nh_prog), TARGET, INTENT(INOUT) :: pt_prog_rcf
    TYPE(t_nh_prog), TARGET, INTENT(IN) :: pt_prog_now_rcf
    TYPE(t_nh_diag), TARGET, INTENT(INOUT) :: pt_diag
    TYPE(t_nh_metrics), INTENT(IN) :: p_metrics
    TYPE(t_nwp_phy_diag), INTENT(INOUT) :: prm_diag
    TYPE(t_nwp_phy_tend), TARGET, INTENT(INOUT) :: prm_nwp_tend
    TYPE(t_wtr_prog), INTENT(INOUT) :: wtr_prog_now, wtr_prog_new
    TYPE(t_lnd_prog), INTENT(INOUT) :: lnd_prog_now, lnd_prog_new
    TYPE(t_lnd_diag), INTENT(INOUT) :: lnd_diag
    TYPE(t_external_data), INTENT(INOUT) :: ext_data
    LOGICAL, INTENT(IN) :: lcpu_only

    CHARACTER(LEN=MAX_DATETIME_STR_LEN) :: date
    INTEGER, PARAMETER :: nser = 1
    INTEGER, SAVE :: ser_count = 0

    LOGICAL :: ltke_adv
    LOGICAL :: lnumber
    !$ser verbatim ltke_adv = advection_config(jg)%iadv_tke > 0
    !$ser verbatim lnumber = atm_phy_nwp_config(jg)%icpl_aero_gscp > 0 .and. iprog_aero > 0
    
    !$ser verbatim ser_count = ser_count + 1
    !$ser verbatim IF(ser_count <= ser_interface_nwp) THEN
    !$ser verbatim   CALL warning('SER:mo_ser_nh_interface_nwp:serialize_nh_interface_nwp_input','Serialization is active!')
#if defined(_OPENACC)
    !$ser verbatim   CALL warning('GPU:mo_ser_nh_interface_nwp:serialize_nh_interface_nwp_input','GPU HOST synchronization forced by serialization!')
    !$ser verbatim IF(.not. lcpu_only) THEN
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%w ) IF( ASSOCIATED(pt_prog%w) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%rho ) IF( ASSOCIATED(pt_prog%rho) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%exner ) IF( ASSOCIATED(pt_prog%exner) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%vn ) IF( ASSOCIATED(pt_prog%vn) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%theta_v ) IF( ASSOCIATED(pt_prog%theta_v) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%dpres_mc ) IF( ASSOCIATED(pt_diag%dpres_mc) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%pres_sfc ) IF( ASSOCIATED(pt_diag%pres_sfc) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%u ) IF( ASSOCIATED(pt_diag%u) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%v ) IF( ASSOCIATED(pt_diag%v) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%temp ) IF( ASSOCIATED(pt_diag%temp) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%pres ) IF( ASSOCIATED(pt_diag%pres) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%hdef_ic ) IF( ASSOCIATED(pt_diag%hdef_ic) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%div_ic ) IF( ASSOCIATED(pt_diag%div_ic) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%dwdx ) IF( ASSOCIATED(pt_diag%dwdx) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%dwdy ) IF( ASSOCIATED(pt_diag%dwdy) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%ddt_tracer_adv ) IF( ltke_adv)
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%pres_ifc ) IF( ASSOCIATED(pt_diag%pres_ifc) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%tempv ) IF( ASSOCIATED(pt_diag%tempv) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%temp_ifc ) IF( ASSOCIATED(pt_diag%temp_ifc) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%exner_dyn_incr ) IF( ASSOCIATED(pt_diag%exner_dyn_incr) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%airmass_now ) IF( ASSOCIATED(pt_diag%airmass_now) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%airmass_new ) IF( ASSOCIATED(pt_diag%airmass_new) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%wgtfac_c ) IF( ASSOCIATED(p_metrics%wgtfac_c) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%z_ifc ) IF( ASSOCIATED(p_metrics%z_ifc) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%geopot_agl ) IF( ASSOCIATED(p_metrics%geopot_agl) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%geopot_agl_ifc ) IF( ASSOCIATED(p_metrics%geopot_agl_ifc) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%z_mc ) IF( ASSOCIATED(p_metrics%z_mc) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%mask_mtnpoints_g ) IF( ASSOCIATED(p_metrics%mask_mtnpoints_g) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%ddqz_z_full ) IF ( ASSOCIATED(p_metrics%ddqz_z_full) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog_rcf%tracer ) IF( ASSOCIATED(pt_prog_rcf%tracer) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog_now_rcf%tke ) IF( ASSOCIATED(pt_prog_now_rcf%tke) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%gz0 ) IF( ASSOCIATED(prm_diag%gz0) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvm ) IF( ASSOCIATED(prm_diag%tvm) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvh ) IF( ASSOCIATED(prm_diag%tvh) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkvm ) IF( ASSOCIATED(prm_diag%tkvm) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkvh ) IF( ASSOCIATED(prm_diag%tkvh) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%shfl_s ) IF( ASSOCIATED(prm_diag%shfl_s) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qhfl_s ) IF( ASSOCIATED(prm_diag%qhfl_s) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%pat_len ) IF( ASSOCIATED(prm_diag%pat_len) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tropics_mask ) IF( ASSOCIATED(prm_diag%tropics_mask) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%innertropics_mask ) IF( ASSOCIATED(prm_diag%innertropics_mask) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkred_sfc ) IF( ASSOCIATED(prm_diag%tkred_sfc) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%gz0_t ) IF( ASSOCIATED(prm_diag%gz0_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tcm_t ) IF( ASSOCIATED(prm_diag%tcm_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tch_t ) IF( ASSOCIATED(prm_diag%tch_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvm_t ) IF( ASSOCIATED(prm_diag%tvm_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvh_t ) IF( ASSOCIATED(prm_diag%tvh_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tcm ) IF( ASSOCIATED(prm_diag%tcm) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tch ) IF( ASSOCIATED(prm_diag%tch) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tfm ) IF( ASSOCIATED(prm_diag%tfm) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tfh ) IF( ASSOCIATED(prm_diag%tfh) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tfv_t ) IF( ASSOCIATED(prm_diag%tfv_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkr_t ) IF( ASSOCIATED(prm_diag%tkr_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tfv ) IF( ASSOCIATED(prm_diag%tfv) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkr ) IF( ASSOCIATED(prm_diag%tkr) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkvm_s_t ) IF( ASSOCIATED(prm_diag%tkvm_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkvh_s_t ) IF( ASSOCIATED(prm_diag%tkvh_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rcld ) IF( ASSOCIATED(prm_diag%rcld) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%ktop_envel ) IF( ASSOCIATED(prm_diag%ktop_envel) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%shfl_s_t ) IF( ASSOCIATED(prm_diag%shfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qhfl_s_t ) IF( ASSOCIATED(prm_diag%qhfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%umfl_s_t ) IF( ASSOCIATED(prm_diag%umfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%vmfl_s_t ) IF( ASSOCIATED(prm_diag%vmfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%lhfl_s_t ) IF( ASSOCIATED(prm_diag%lhfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%u_10m ) IF( ASSOCIATED(prm_diag%u_10m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%v_10m ) IF( ASSOCIATED(prm_diag%v_10m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%u_10m_t ) IF( ASSOCIATED(prm_diag%u_10m_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%v_10m_t ) IF( ASSOCIATED(prm_diag%v_10m_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tmax_2m ) IF( ASSOCIATED(prm_diag%tmax_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tmin_2m ) IF( ASSOCIATED(prm_diag%tmin_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%t_2m ) IF( ASSOCIATED(prm_diag%t_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qv_2m ) IF( ASSOCIATED(prm_diag%qv_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%td_2m ) IF( ASSOCIATED(prm_diag%td_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rh_2m ) IF( ASSOCIATED(prm_diag%rh_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvs_s_t ) IF( ASSOCIATED(prm_diag%tvs_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%t_2m_land ) IF (ASSOCIATED(prm_diag%t_2m_land) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%td_2m_land ) IF (ASSOCIATED(prm_diag%td_2m_land) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rh_2m_land ) IF (ASSOCIATED(prm_diag%rh_2m_land) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%dyn_gust ) IF (ASSOCIATED(prm_diag%dyn_gust) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%cloud_num(:,:) ) IF ( ASSOCIATED(prm_diag%cloud_num) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tt_lheat ) IF ( ASSOCIATED(prm_diag%tt_lheat) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rain_gsp_rate ) IF ( ASSOCIATED(prm_diag%rain_gsp_rate) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%snow_gsp_rate ) IF ( ASSOCIATED(prm_diag%snow_gsp_rate) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%graupel_gsp_rate  ) IF ( ASSOCIATED(prm_diag%graupel_gsp_rate) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qrs_flux ) IF ( ASSOCIATED(prm_diag%qrs_flux) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rain_gsp ) IF ( ASSOCIATED(prm_diag%rain_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%ice_gsp ) IF ( ASSOCIATED(prm_diag%ice_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%snow_gsp ) IF ( ASSOCIATED(prm_diag%snow_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%hail_gsp ) IF ( ASSOCIATED(prm_diag%hail_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%graupel_gsp ) IF ( ASSOCIATED(prm_diag%graupel_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%prec_gsp ) IF ( ASSOCIATED(prm_diag%prec_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qcfl_s) IF ( ASSOCIATED(prm_diag%qcfl_s) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tracer_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_tracer_turb) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tke ) IF( ASSOCIATED(prm_nwp_tend%ddt_tke) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tke_pconv ) IF( ASSOCIATED(prm_nwp_tend%ddt_tke_pconv) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tke_hsh ) IF( ASSOCIATED(prm_nwp_tend%ddt_tke_hsh) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_u_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_u_turb) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_v_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_v_turb) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_temp_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_temp_turb) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_u_sso ) IF( ASSOCIATED(prm_nwp_tend%ddt_u_sso) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_v_sso ) IF( ASSOCIATED(prm_nwp_tend%ddt_v_sso) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_temp_gscp ) IF ( ASSOCIATED(prm_nwp_tend%ddt_temp_gscp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tracer_gscp ) IF ( ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp) )
    !$ser verbatim   !$ACC UPDATE HOST( wtr_prog_now%t_ice ) IF( ASSOCIATED(wtr_prog_now%t_ice) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_prog_now%t_g ) IF( ASSOCIATED(lnd_prog_now%t_g) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_prog_now%t_snow_t ) IF( ASSOCIATED(lnd_prog_now%t_snow_t) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_diag%qv_s ) IF( ASSOCIATED(lnd_diag%qv_s) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_diag%qv_s_t ) IF (ASSOCIATED(lnd_diag%qv_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_diag%snowfrac_t ) IF (ASSOCIATED(lnd_diag%snowfrac_t) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_diag%snowfrac_lc_t ) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t) )
    !$ser verbatim   !$ACC UPDATE HOST( wtr_prog_new%h_ice ) IF (ASSOCIATED(wtr_prog_new%h_ice) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_prog_new%t_g_t ) IF (ASSOCIATED(lnd_prog_new%t_g_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%idx_lst_t ) IF (ASSOCIATED(ext_data%atm%idx_lst_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%gp_count_t ) IF (ASSOCIATED(ext_data%atm%gp_count_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%lc_class_t ) IF (ASSOCIATED(ext_data%atm%lc_class_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%z0_lcc_min ) IF (ASSOCIATED(ext_data%atm%z0_lcc_min) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%z0_lcc ) IF (ASSOCIATED(ext_data%atm%z0_lcc) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%sso_stdh_raw ) IF (ASSOCIATED(ext_data%atm%sso_stdh_raw) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%frac_t ) IF (ASSOCIATED(ext_data%atm%frac_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%plcov_t ) IF (ASSOCIATED(ext_data%atm%plcov_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%sai_t ) IF (ASSOCIATED(ext_data%atm%sai_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%sai ) IF (ASSOCIATED(ext_data%atm%sai) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%fr_land ) IF (ASSOCIATED(ext_data%atm%fr_land) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%depth_lk ) IF (ASSOCIATED(ext_data%atm%depth_lk) )
    !$ser verbatim END IF

#endif
    !$ser verbatim   CALL datetimeToString(time_config%tc_current_date, date)
    !$ser verbatim   CALL init('icon')
    !$ser savepoint nh_interface_nwp-input jg=jg nproma=nproma nlev=nlev date=TRIM(date)
#if defined(SERIALIZE_CREATE_REFERENCE)
    !$ser mode       write
#elif defined(SERIALIZE_READ_REFERENCE)
    !$ser mode       read
#elif defined(SERIALIZE_PERTURB_REFERENCE)
    !$ser mode       read-perturb
#else
    !$ser verbatim   CALL finish('nh_interface_nwp-input', 'SERIALIZATION MODE IS NOT SET')
#endif
    !$ser data nh_interface_nwp_pt_prog_w=pt_prog%w(:,:,:) IF (ASSOCIATED(pt_prog%w))
    !$ser data nh_interface_nwp_pt_prog_vn=pt_prog%vn(:,:,:) IF (ASSOCIATED(pt_prog%vn))
    !$ser data nh_interface_nwp_pt_prog_rho=pt_prog%rho(:,:,:) IF (ASSOCIATED(pt_prog%rho))
    !$ser data nh_interface_nwp_pt_prog_exner=pt_prog%exner(:,:,:) IF (ASSOCIATED(pt_prog%exner))
    !$ser data nh_interface_nwp_pt_prog_theta_v=pt_prog%theta_v(:,:,:) IF (ASSOCIATED(pt_prog%theta_v))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqv=pt_prog_rcf%tracer(:,:,:,iqv) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqc=pt_prog_rcf%tracer(:,:,:,iqc) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqs=pt_prog_rcf%tracer(:,:,:,iqs) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqi=pt_prog_rcf%tracer(:,:,:,iqi) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqnc=pt_prog_rcf%tracer(:,:,:,iqnc) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqnr=pt_prog_rcf%tracer(:,:,:,iqnr) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqni=pt_prog_rcf%tracer(:,:,:,iqni) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqns=pt_prog_rcf%tracer(:,:,:,iqns) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqng=pt_prog_rcf%tracer(:,:,:,iqng) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqr=pt_prog_rcf%tracer(:,:,:,iqr) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqg=pt_prog_rcf%tracer(:,:,:,iqg) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_now_rcf=pt_prog_now_rcf%tke(:,:,:) IF (ASSOCIATED(pt_prog_now_rcf%tke))
    !$ser data nh_interface_nwp_pt_diag_u=pt_diag%u(:,:,:) IF (ASSOCIATED(pt_diag%u))
    !$ser data nh_interface_nwp_pt_diag_v=pt_diag%v(:,:,:) IF (ASSOCIATED(pt_diag%v))
    !$ser data nh_interface_nwp_pt_diag_temp=pt_diag%temp(:,:,:) IF (ASSOCIATED(pt_diag%temp))
    !$ser data nh_interface_nwp_pt_diag_pres=pt_diag%pres(:,:,:) IF (ASSOCIATED(pt_diag%pres))
    !$ser data nh_interface_nwp_pt_diag_hdef_ic=pt_diag%hdef_ic(:,:,:) IF (ASSOCIATED(pt_diag%hdef_ic))
    !$ser data nh_interface_nwp_pt_diag_div_ic=pt_diag%div_ic(:,:,:) IF (ASSOCIATED(pt_diag%div_ic))
    !$ser data nh_interface_nwp_pt_diag_dwdx=pt_diag%dwdx(:,:,:) IF (ASSOCIATED(pt_diag%dwdx))
    !$ser data nh_interface_nwp_pt_diag_dwdy=pt_diag%dwdy(:,:,:) IF (ASSOCIATED(pt_diag%dwdy))
    !$ser data nh_interface_nwp_pt_diag_ddt_tracer_adv_iqtke=pt_diag%ddt_tracer_adv(:,:,:,iqtke) IF (ltke_adv)
    !$ser data nh_interface_nwp_pt_diag_dpres_mc=pt_diag%dpres_mc(:,:,:) IF (ASSOCIATED(pt_diag%dpres_mc))
    !$ser data nh_interface_nwp_pt_diag_pres_sfc=pt_diag%pres_sfc(:,:) IF (ASSOCIATED(pt_diag%pres_sfc))
    !$ser data nh_interface_nwp_pt_diag_tempv=pt_diag%tempv(:,:,:) IF (ASSOCIATED(pt_diag%tempv))
    !$ser data nh_interface_nwp_p_metrics_wgtfac_c=p_metrics%wgtfac_c(:,:,:) IF (ASSOCIATED(p_metrics%wgtfac_c))
    !$ser data nh_interface_nwp_p_metrics_z_ifc=p_metrics%z_ifc(:,:,:) IF (ASSOCIATED(p_metrics%z_ifc))
    !$ser data nh_interface_nwp_p_metrics_geopot_agl=p_metrics%geopot_agl(:,:,:) IF (ASSOCIATED(p_metrics%geopot_agl))
    !$ser data nh_interface_nwp_p_metrics_geopot_agl_ifc=p_metrics%geopot_agl_ifc(:,:,:) IF (ASSOCIATED(p_metrics%geopot_agl_ifc))
    !$ser data nh_interface_nwp_p_metrics_z_mc=p_metrics%z_mc(:,:,:) IF (ASSOCIATED(p_metrics%z_mc))
    !$ser data nh_interface_nwp_p_metrics_ddqz_z_full=p_metrics%ddqz_z_full(:,:,:) IF (ASSOCIATED(p_metrics%ddqz_z_full))
    !$ser data nh_interface_nwp_p_metrics_mask_mtnpoints_g=p_metrics%mask_mtnpoints_g(:,:) IF (ASSOCIATED(p_metrics%mask_mtnpoints_g))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_turb_iqv=prm_nwp_tend%ddt_tracer_turb(:,:,:,iqv) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_turb_iqc=prm_nwp_tend%ddt_tracer_turb(:,:,:,iqc) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_turb_iqi=prm_nwp_tend%ddt_tracer_turb(:,:,:,iqi) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_temp_gscp=prm_nwp_tend%ddt_temp_gscp(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_temp_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqv=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqv) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqc=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqc) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqi=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqi) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqr=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqr) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqs=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqs) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tke=prm_nwp_tend%ddt_tke(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_tke))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tke_pconv=prm_nwp_tend%ddt_tke_pconv(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_tke_pconv))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tke_hsh=prm_nwp_tend%ddt_tke_hsh(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_tke_hsh))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_u_turb=prm_nwp_tend%ddt_u_turb(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_u_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_v_turb=prm_nwp_tend%ddt_v_turb(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_v_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_temp_turb=prm_nwp_tend%ddt_temp_turb(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_temp_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_u_sso=prm_nwp_tend%ddt_u_sso(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_u_sso))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_v_sso=prm_nwp_tend%ddt_v_sso(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_v_sso))
    !$ser data nh_interface_nwp_prm_wtr_prog_now_t_ice=wtr_prog_now%t_ice(:,:) IF (ASSOCIATED(wtr_prog_now%t_ice))
    !$ser data nh_interface_nwp_lnd_prg_now_t_g=lnd_prog_now%t_g(:,:) IF (ASSOCIATED(lnd_prog_now%t_g))
    !$ser data nh_interface_nwp_lnd_prg_now_t_snow_t=lnd_prog_now%t_snow_t(:,:,:) IF (ASSOCIATED(lnd_prog_now%t_snow_t))
    !$ser data nh_interface_nwp_lnd_diag_qv_s=lnd_diag%qv_s(:,:) IF (ASSOCIATED(lnd_diag%qv_s))
    !$ser data nh_interface_nwp_p_diag_pres_ifc=pt_diag%pres_ifc(:,:,:) IF (ASSOCIATED(pt_diag%pres_ifc))
    !$ser data nh_interface_nwp_prm_diag_gz0_t=prm_diag%gz0_t(:,:,:) IF (ASSOCIATED(prm_diag%gz0_t))
    !$ser data nh_interface_nwp_prm_diag_tcm_t=prm_diag%tcm_t(:,:,:) IF (ASSOCIATED(prm_diag%tcm_t))
    !$ser data nh_interface_nwp_prm_diag_tch_t=prm_diag%tch_t(:,:,:) IF (ASSOCIATED(prm_diag%tch_t))
    !$ser data nh_interface_nwp_prm_diag_tvh_t=prm_diag%tvh_t(:,:,:) IF (ASSOCIATED(prm_diag%tvh_t))
    !$ser data nh_interface_nwp_prm_diag_tcm=prm_diag%tcm(:,:) IF (ASSOCIATED(prm_diag%tcm))
    !$ser data nh_interface_nwp_prm_diag_tch=prm_diag%tch(:,:) IF (ASSOCIATED(prm_diag%tch))
    !$ser data nh_interface_nwp_prm_diag_tfm=prm_diag%tfm(:,:) IF (ASSOCIATED(prm_diag%tfm))
    !$ser data nh_interface_nwp_prm_diag_tfh=prm_diag%tfh(:,:) IF (ASSOCIATED(prm_diag%tfh))
    !$ser data nh_interface_nwp_prm_diag_tfv_t=prm_diag%tfv_t(:,:,:) IF (ASSOCIATED(prm_diag%tfv_t))
    !$ser data nh_interface_nwp_prm_diag_tkr_t=prm_diag%tkr_t(:,:,:) IF (ASSOCIATED(prm_diag%tkr_t))
    !$ser data nh_interface_nwp_prm_diag_tkvm_t=prm_diag%tkvm_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tkvm_s_t))
    !$ser data nh_interface_nwp_prm_diag_tkvh_t=prm_diag%tkvh_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tkvh_s_t))
    !$ser data nh_interface_nwp_prm_diag_rcld=prm_diag%rcld(:,:,:) IF (ASSOCIATED(prm_diag%rcld))
    !$ser data nh_interface_nwp_prm_diag_ktop_envel=prm_diag%ktop_envel(:,:) IF (ASSOCIATED(prm_diag%ktop_envel))
    !$ser data nh_interface_nwp_prm_diag_shfl_s_t=prm_diag%shfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%shfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_qhfl_s_t=prm_diag%qhfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%qhfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_umfl_s_t=prm_diag%umfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%umfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_vmfl_s_t=prm_diag%vmfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%vmfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_lhfl_s_t=prm_diag%lhfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%lhfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_umfl_s=prm_diag%umfl_s(:,:) IF (ASSOCIATED(prm_diag%umfl_s))
    !$ser data nh_interface_nwp_prm_diag_vmfl_s=prm_diag%vmfl_s(:,:) IF (ASSOCIATED(prm_diag%vmfl_s))
    !$ser data nh_interface_nwp_prm_diag_lhfl_s=prm_diag%lhfl_s(:,:) IF (ASSOCIATED(prm_diag%lhfl_s))
    !$ser data nh_interface_nwp_prm_diag_u_10m=prm_diag%u_10m(:,:) IF (ASSOCIATED(prm_diag%u_10m))
    !$ser data nh_interface_nwp_prm_diag_v_10m=prm_diag%v_10m(:,:) IF (ASSOCIATED(prm_diag%v_10m))
    !$ser data nh_interface_nwp_prm_diag_u_10m_t=prm_diag%u_10m_t(:,:,:) IF (ASSOCIATED(prm_diag%u_10m_t))
    !$ser data nh_interface_nwp_prm_diag_v_10m_t=prm_diag%v_10m_t(:,:,:) IF (ASSOCIATED(prm_diag%v_10m_t))
    !$ser data nh_interface_nwp_prm_diag_tmax_2m=prm_diag%tmax_2m(:,:) IF (ASSOCIATED(prm_diag%tmax_2m))
    !$ser data nh_interface_nwp_prm_diag_tmin_2m=prm_diag%tmin_2m(:,:) IF (ASSOCIATED(prm_diag%tmin_2m))
    !$ser data nh_interface_nwp_prm_diag_t_2m=prm_diag%t_2m(:,:) IF (ASSOCIATED(prm_diag%t_2m))
    !$ser data nh_interface_nwp_prm_diag_qv_2m=prm_diag%qv_2m(:,:) IF (ASSOCIATED(prm_diag%qv_2m))
    !$ser data nh_interface_nwp_prm_diag_td_2m=prm_diag%td_2m(:,:) IF (ASSOCIATED(prm_diag%td_2m))
    !$ser data nh_interface_nwp_prm_diag_rh_2m=prm_diag%rh_2m(:,:) IF (ASSOCIATED(prm_diag%rh_2m))
    !$ser data nh_interface_nwp_prm_diag_tvs_s_t=prm_diag%tvs_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tvs_s_t))
    !$ser data nh_interface_nwp_prm_diag_tfv=prm_diag%tfv(:,:) IF (ASSOCIATED(prm_diag%tfv))
    !$ser data nh_interface_nwp_prm_diag_tkr=prm_diag%tkr(:,:) IF (ASSOCIATED(prm_diag%tkr))
    !$ser data nh_interface_nwp_prm_diag_t_2m_land=prm_diag%t_2m_land(:,:) IF (ASSOCIATED(prm_diag%t_2m_land))
    !$ser data nh_interface_nwp_prm_diag_td_2m_land=prm_diag%td_2m_land(:,:) IF (ASSOCIATED(prm_diag%td_2m_land))
    !$ser data nh_interface_nwp_prm_diag_rh_2m_land=prm_diag%rh_2m_land(:,:) IF (ASSOCIATED(prm_diag%rh_2m_land))
    !$ser data nh_interface_nwp_prm_diag_dyn_gust=prm_diag%dyn_gust(:,:) IF (ASSOCIATED(prm_diag%dyn_gust))
    !$ser data nh_interface_nwp_prm_diag_cloud_num=prm_diag%cloud_num(:,:) IF (ASSOCIATED(prm_diag%cloud_num))
    !$ser data nh_interface_nwp_prm_diag_tt_lheat=prm_diag%tt_lheat(:,:,:) IF (ASSOCIATED(prm_diag%tt_lheat))
    !$ser data nh_interface_nwp_prm_diag_rain_gsp_rate=prm_diag%rain_gsp_rate(:,:) IF (ASSOCIATED(prm_diag%rain_gsp_rate))
    !$ser data nh_interface_nwp_prm_diag_snow_gsp_rate=prm_diag%snow_gsp_rate(:,:) IF (ASSOCIATED(prm_diag%snow_gsp_rate))
    !$ser data nh_interface_nwp_prm_diag_graupel_gsp_rate=prm_diag%graupel_gsp_rate (:,:) IF (ASSOCIATED(prm_diag%graupel_gsp_rate))
    !$ser data nh_interface_nwp_prm_diag_qrs_flux=prm_diag%qrs_flux(:,:,:) IF (ASSOCIATED(prm_diag%qrs_flux))
    !$ser data nh_interface_nwp_prm_diag_rain_gsp=prm_diag%rain_gsp(:,:) IF (ASSOCIATED(prm_diag%rain_gsp))
    !$ser data nh_interface_nwp_prm_diag_ice_gsp=prm_diag%ice_gsp(:,:) IF (ASSOCIATED(prm_diag%ice_gsp))
    !$ser data nh_interface_nwp_prm_diag_snow_gsp=prm_diag%snow_gsp(:,:) IF (ASSOCIATED(prm_diag%snow_gsp))
    !$ser data nh_interface_nwp_prm_diag_hail_gsp=prm_diag%hail_gsp(:,:) IF (ASSOCIATED(prm_diag%hail_gsp))
    !$ser data nh_interface_nwp_prm_diag_graupel_gsp=prm_diag%graupel_gsp(:,:) IF (ASSOCIATED(prm_diag%graupel_gsp))
    !$ser data nh_interface_nwp_prm_diag_prec_gsp=prm_diag%prec_gsp(:,:) IF (ASSOCIATED(prm_diag%prec_gsp))
    !$ser data nh_interface_nwp_prm_diag_qcfl_s=prm_diag%qcfl_s(:,:) IF (ASSOCIATED(prm_diag%qcfl_s))
    !$ser data nh_interface_nwp_prm_diag_gz0=prm_diag%gz0(:,:) IF (ASSOCIATED(prm_diag%gz0))
    !$ser data nh_interface_nwp_prm_diag_tvm=prm_diag%tvm(:,:) IF (ASSOCIATED(prm_diag%tvm))
    !$ser data nh_interface_nwp_prm_diag_tvh=prm_diag%tvh(:,:) IF (ASSOCIATED(prm_diag%tvh))
    !$ser data nh_interface_nwp_prm_diag_tkvm=prm_diag%tkvm(:,:,:) IF (ASSOCIATED(prm_diag%tkvm))
    !$ser data nh_interface_nwp_prm_diag_tkvh=prm_diag%tkvh(:,:,:) IF (ASSOCIATED(prm_diag%tkvh))
    !$ser data nh_interface_nwp_prm_diag_shfl_s=prm_diag%shfl_s(:,:) IF (ASSOCIATED(prm_diag%shfl_s))
    !$ser data nh_interface_nwp_prm_diag_qhfl_s=prm_diag%qhfl_s(:,:) IF (ASSOCIATED(prm_diag%qhfl_s))
    !$ser data nh_interface_nwp_prm_diag_pat_len=prm_diag%pat_len(:,:) IF (ASSOCIATED(prm_diag%pat_len))
    !$ser data nh_interface_nwp_prm_diag_tropics_mask=prm_diag%tropics_mask(:,:) IF (ASSOCIATED(prm_diag%tropics_mask))
    !$ser data nh_interface_nwp_prm_diag_innertropics_mask=prm_diag%innertropics_mask(:,:) IF (ASSOCIATED(prm_diag%innertropics_mask))
    !$ser data nh_interface_nwp_prm_diag_tkred_sfc=prm_diag%tkred_sfc(:,:) IF (ASSOCIATED(prm_diag%tkred_sfc))
    !$ser data nh_interface_nwp_wtr_prog_new_h_ice=wtr_prog_new%h_ice(:,:) IF (ASSOCIATED(wtr_prog_new%h_ice))
    !$ser data nh_interface_nwp_lnd_prog_new_t_g_t=lnd_prog_new%t_g_t(:,:,:) IF (ASSOCIATED(lnd_prog_new%t_g_t))
    !$ser data nh_interface_nwp_lnd_diag_qv_s_t=lnd_diag%qv_s_t(:,:,:) IF (ASSOCIATED(lnd_diag%qv_s_t))
    !$ser data nh_interface_nwp_lnd_diag_snowfrac_t=lnd_diag%snowfrac_t(:,:,:) IF (ASSOCIATED(lnd_diag%snowfrac_t))
    !$ser data nh_interface_nwp_lnd_diag_snowfrac_lc_t=lnd_diag%snowfrac_lc_t(:,:,:) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t))
    !$ser data nh_interface_nwp_ext_data_idx_lst_t=ext_data%atm%idx_lst_t IF (ASSOCIATED(ext_data%atm%idx_lst_t))
    !$ser data nh_interface_nwp_ext_data_gp_count_t=ext_data%atm%gp_count_t IF (ASSOCIATED(ext_data%atm%gp_count_t))
    !$ser data nh_interface_nwp_ext_data_lc_class_t=ext_data%atm%lc_class_t IF (ASSOCIATED(ext_data%atm%lc_class_t))
    !$ser data nh_interface_nwp_ext_data_z0_lcc_min=ext_data%atm%z0_lcc_min IF (ASSOCIATED(ext_data%atm%z0_lcc_min))
    !$ser data nh_interface_nwp_ext_data_z0_lcc=ext_data%atm%z0_lcc IF (ASSOCIATED(ext_data%atm%z0_lcc))
    !$ser data nh_interface_nwp_ext_data_sso_stdh_raw=ext_data%atm%sso_stdh_raw IF (ASSOCIATED(ext_data%atm%sso_stdh_raw))
    !$ser data nh_interface_nwp_ext_data_frac_t=ext_data%atm%frac_t IF (ASSOCIATED(ext_data%atm%frac_t))
    !$ser data nh_interface_nwp_ext_data_plcov_t=ext_data%atm%plcov_t IF (ASSOCIATED(ext_data%atm%plcov_t))
    !$ser data nh_interface_nwp_ext_data_sai_t=ext_data%atm%sai_t IF (ASSOCIATED(ext_data%atm%sai_t))
    !$ser data nh_interface_nwp_ext_data_sai=ext_data%atm%sai IF (ASSOCIATED(ext_data%atm%sai))
    !$ser data nh_interface_nwp_ext_data_fr_land=ext_data%atm%fr_land IF (ASSOCIATED(ext_data%atm%fr_land))
    !$ser data nh_interface_nwp_ext_data_depth_lk=ext_data%atm%depth_lk IF (ASSOCIATED(ext_data%atm%depth_lk))

#if defined(_OPENACC)
#if defined(SERIALIZE_READ_REFERENCE) || defined(SERIALIZE_PERTURB_REFERENCE)
    !$ser verbatim CALL warning('GPU:mo_ser_nwp_tudif:turbdiff_interface-input','GPU DEVICE synchronization forced by serialization!')
    !$ser verbatim IF(.not. lcpu_only) THEN
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_prog%w ) IF( ASSOCIATED(pt_prog%w) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_prog%vn ) IF( ASSOCIATED(pt_prog%vn) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_prog%rho ) IF( ASSOCIATED(pt_prog%rho) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_prog%exner ) IF( ASSOCIATED(pt_prog%exner) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_prog%theta_v ) IF( ASSOCIATED(pt_prog%theta_v) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%dpres_mc ) IF( ASSOCIATED(pt_diag%dpres_mc) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%pres_sfc ) IF( ASSOCIATED(pt_diag%pres_sfc) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%u ) IF( ASSOCIATED(pt_diag%u) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%v ) IF( ASSOCIATED(pt_diag%v) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%temp ) IF( ASSOCIATED(pt_diag%temp) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%pres ) IF( ASSOCIATED(pt_diag%pres) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%hdef_ic ) IF( ASSOCIATED(pt_diag%hdef_ic) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%div_ic ) IF( ASSOCIATED(pt_diag%div_ic) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%dwdx ) IF( ASSOCIATED(pt_diag%dwdx) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%dwdy ) IF( ASSOCIATED(pt_diag%dwdy) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%ddt_tracer_adv ) IF( ltke_adv)
    !$ser verbatim   !$ACC UPDATE DEVICE( p_metrics%wgtfac_c ) IF( ASSOCIATED(p_metrics%wgtfac_c) )
    !$ser verbatim   !$ACC UPDATE DEVICE( p_metrics%z_ifc ) IF( ASSOCIATED(p_metrics%z_ifc) )
    !$ser verbatim   !$ACC UPDATE DEVICE( p_metrics%geopot_agl ) IF( ASSOCIATED(p_metrics%geopot_agl) )
    !$ser verbatim   !$ACC UPDATE DEVICE( p_metrics%geopot_agl_ifc ) IF( ASSOCIATED(p_metrics%geopot_agl_ifc) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_prog_rcf%tracer ) IF( ASSOCIATED(pt_prog_rcf%tracer) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_prog_now_rcf%tke ) IF( ASSOCIATED(pt_prog_now_rcf%tke) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%gz0 ) IF( ASSOCIATED(prm_diag%gz0) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tvm ) IF( ASSOCIATED(prm_diag%tvm) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tvh ) IF( ASSOCIATED(prm_diag%tvh) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tkvm ) IF( ASSOCIATED(prm_diag%tkvm) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tkvh ) IF( ASSOCIATED(prm_diag%tkvh) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%shfl_s ) IF( ASSOCIATED(prm_diag%shfl_s) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%qhfl_s ) IF( ASSOCIATED(prm_diag%qhfl_s) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%pat_len ) IF( ASSOCIATED(prm_diag%pat_len) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tropics_mask ) IF( ASSOCIATED(prm_diag%tropics_mask) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%innertropics_mask ) IF( ASSOCIATED(prm_diag%innertropics_mask) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tkred_sfc ) IF( ASSOCIATED(prm_diag%tkred_sfc) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_nwp_tend%ddt_tracer_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_tracer_turb) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_nwp_tend%ddt_tke ) IF( ASSOCIATED(prm_nwp_tend%ddt_tke) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_nwp_tend%ddt_tke_pconv ) IF( ASSOCIATED(prm_nwp_tend%ddt_tke_pconv) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_nwp_tend%ddt_tke_hsh ) IF( ASSOCIATED(prm_nwp_tend%ddt_tke_hsh) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_nwp_tend%ddt_u_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_u_turb) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_nwp_tend%ddt_v_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_v_turb) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_nwp_tend%ddt_temp_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_temp_turb) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_nwp_tend%ddt_u_sso ) IF( ASSOCIATED(prm_nwp_tend%ddt_u_sso) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_nwp_tend%ddt_v_sso ) IF( ASSOCIATED(prm_nwp_tend%ddt_v_sso) )
    !$ser verbatim   !$ACC UPDATE DEVICE( wtr_prog_now%t_ice ) IF( ASSOCIATED(wtr_prog_now%t_ice) )
    !$ser verbatim   !$ACC UPDATE DEVICE( lnd_prog_now%t_g ) IF( ASSOCIATED(lnd_prog_now%t_g) )
    !$ser verbatim   !$ACC UPDATE DEVICE( lnd_prog_now%t_snow_t ) IF( ASSOCIATED(lnd_prog_now%t_snow_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( lnd_diag%qv_s ) IF( ASSOCIATED(lnd_diag%qv_s) )
    !$ser verbatim   !$ACC UPDATE DEVICE( p_metrics%z_mc ) IF( ASSOCIATED(p_metrics%z_mc) )
    !$ser verbatim   !$ACC UPDATE DEVICE( p_metrics%mask_mtnpoints_g ) IF( ASSOCIATED(p_metrics%mask_mtnpoints_g) )
    !$ser verbatim   !$ACC UPDATE DEVICE( pt_diag%pres_ifc ) IF( ASSOCIATED(pt_diag%pres_ifc) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%gz0_t ) IF( ASSOCIATED(prm_diag%gz0_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tcm_t ) IF( ASSOCIATED(prm_diag%tcm_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tch_t ) IF( ASSOCIATED(prm_diag%tch_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tvm_t ) IF( ASSOCIATED(prm_diag%tvm_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tvh_t ) IF( ASSOCIATED(prm_diag%tvh_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tcm ) IF( ASSOCIATED(prm_diag%tcm) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tch ) IF( ASSOCIATED(prm_diag%tch) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tfm ) IF( ASSOCIATED(prm_diag%tfm) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tfh ) IF( ASSOCIATED(prm_diag%tfh) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tfv_t ) IF( ASSOCIATED(prm_diag%tfv_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tkr_t ) IF( ASSOCIATED(prm_diag%tkr_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tfv ) IF( ASSOCIATED(prm_diag%tfv) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tkr ) IF( ASSOCIATED(prm_diag%tkr) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tkvm_s_t ) IF( ASSOCIATED(prm_diag%tkvm_s_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tkvh_s_t ) IF( ASSOCIATED(prm_diag%tkvh_s_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%rcld ) IF( ASSOCIATED(prm_diag%rcld) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%ktop_envel ) IF( ASSOCIATED(prm_diag%ktop_envel) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%shfl_s_t ) IF( ASSOCIATED(prm_diag%shfl_s_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%qhfl_s_t ) IF( ASSOCIATED(prm_diag%qhfl_s_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%umfl_s_t ) IF( ASSOCIATED(prm_diag%umfl_s_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%vmfl_s_t ) IF( ASSOCIATED(prm_diag%vmfl_s_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%lhfl_s_t ) IF( ASSOCIATED(prm_diag%lhfl_s_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%u_10m ) IF( ASSOCIATED(prm_diag%u_10m) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%v_10m ) IF( ASSOCIATED(prm_diag%v_10m) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%u_10m_t ) IF( ASSOCIATED(prm_diag%u_10m_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%v_10m_t ) IF( ASSOCIATED(prm_diag%v_10m_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tmax_2m ) IF( ASSOCIATED(prm_diag%tmax_2m) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tmin_2m ) IF( ASSOCIATED(prm_diag%tmin_2m) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%t_2m ) IF( ASSOCIATED(prm_diag%t_2m) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%qv_2m ) IF( ASSOCIATED(prm_diag%qv_2m) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%td_2m ) IF( ASSOCIATED(prm_diag%td_2m) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%rh_2m ) IF( ASSOCIATED(prm_diag%rh_2m) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%tvs_s_t ) IF( ASSOCIATED(prm_diag%tvs_s_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%t_2m_land ) IF (ASSOCIATED(prm_diag%t_2m_land) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%td_2m_land ) IF (ASSOCIATED(prm_diag%td_2m_land) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%rh_2m_land ) IF (ASSOCIATED(prm_diag%rh_2m_land) )
    !$ser verbatim   !$ACC UPDATE DEVICE( prm_diag%dyn_gust ) IF (ASSOCIATED(prm_diag%dyn_gust) )
    !$ser verbatim   !$ACC UPDATE DEVICE( wtr_prog_new%h_ice ) IF (ASSOCIATED(wtr_prog_new%h_ice) )
    !$ser verbatim   !$ACC UPDATE DEVICE( lnd_prog_new%t_g_t ) IF (ASSOCIATED(lnd_prog_new%t_g_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( lnd_diag%qv_s_t ) IF (ASSOCIATED(lnd_diag%qv_s_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( lnd_diag%snowfrac_t ) IF (ASSOCIATED(lnd_diag%snowfrac_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( lnd_diag%snowfrac_lc_t ) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%idx_lst_t ) IF (ASSOCIATED(ext_data%atm%idx_lst_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%gp_count_t ) IF (ASSOCIATED(ext_data%atm%gp_count_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%lc_class_t ) IF (ASSOCIATED(ext_data%atm%lc_class_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%z0_lcc_min ) IF (ASSOCIATED(ext_data%atm%z0_lcc_min) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%z0_lcc ) IF (ASSOCIATED(ext_data%atm%z0_lcc) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%sso_stdh_raw ) IF (ASSOCIATED(ext_data%atm%sso_stdh_raw) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%frac_t ) IF (ASSOCIATED(ext_data%atm%frac_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%plcov_t ) IF (ASSOCIATED(ext_data%atm%plcov_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%sai_t ) IF (ASSOCIATED(ext_data%atm%sai_t) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%sai ) IF (ASSOCIATED(ext_data%atm%sai) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%fr_land ) IF (ASSOCIATED(ext_data%atm%fr_land) )
    !$ser verbatim   !$ACC UPDATE DEVICE( ext_data%atm%depth_lk ) IF (ASSOCIATED(ext_data%atm%depth_lk) )
    !$ser verbatim END IF
#endif
#endif
    !$ser verbatim END IF

  END SUBROUTINE serialize_nh_interface_nwp_input

  SUBROUTINE serialize_nh_interface_nwp_output(jg, nproma, nlev, pt_prog, &
                                               pt_prog_rcf, pt_prog_now_rcf, pt_diag, p_metrics, &
                                               prm_diag, prm_nwp_tend, wtr_prog_now, wtr_prog_new, &
                                               lnd_prog_now, lnd_prog_new, lnd_diag, ext_data, lcpu_only)
    INTEGER, INTENT(IN)    :: jg, nproma, nlev
    TYPE(t_nh_prog), TARGET, INTENT(INOUT) :: pt_prog 
    TYPE(t_nh_prog), TARGET, INTENT(INOUT) :: pt_prog_rcf
    TYPE(t_nh_prog), TARGET, INTENT(IN) :: pt_prog_now_rcf
    TYPE(t_nh_diag), TARGET, INTENT(INOUT) :: pt_diag
    TYPE(t_nh_metrics), INTENT(IN) :: p_metrics
    TYPE(t_nwp_phy_diag), INTENT(INOUT) :: prm_diag
    TYPE(t_nwp_phy_tend), TARGET, INTENT(INOUT) :: prm_nwp_tend
    TYPE(t_wtr_prog), INTENT(INOUT) :: wtr_prog_now, wtr_prog_new
    TYPE(t_lnd_prog), INTENT(INOUT) :: lnd_prog_now, lnd_prog_new
    TYPE(t_lnd_diag), INTENT(INOUT) :: lnd_diag
    TYPE(t_external_data), INTENT(INOUT) :: ext_data
    LOGICAL, INTENT(IN) :: lcpu_only

    CHARACTER(LEN=MAX_DATETIME_STR_LEN) :: date
    INTEGER, PARAMETER :: nser = 1
    INTEGER, SAVE :: ser_count = 0

    LOGICAL :: ltke_adv
    LOGICAL :: lnumber
    !$ser verbatim ltke_adv = advection_config(jg)%iadv_tke > 0
    !$ser verbatim lnumber = atm_phy_nwp_config(jg)%icpl_aero_gscp > 0 .and. iprog_aero > 0
    
    !$ser verbatim ser_count = ser_count + 1
    !$ser verbatim IF(ser_count <= ser_interface_nwp) THEN
    !$ser verbatim   CALL warning('SER:mo_ser_nh_interface_nwp:serialize_nh_interface_nwp_output','Serialization is active!')
#if defined(_OPENACC)
    !$ser verbatim   CALL warning('GPU:mo_ser_nh_interface_nwp:serialize_nh_interface_nwp_output','GPU HOST synchronization forced by serialization!')
    !$ser verbatim IF(.not. lcpu_only) THEN
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%w ) IF( ASSOCIATED(pt_prog%w) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%rho ) IF( ASSOCIATED(pt_prog%rho) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%exner ) IF( ASSOCIATED(pt_prog%exner) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%vn ) IF( ASSOCIATED(pt_prog%vn) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog%theta_v ) IF( ASSOCIATED(pt_prog%theta_v) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%dpres_mc ) IF( ASSOCIATED(pt_diag%dpres_mc) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%pres_sfc ) IF( ASSOCIATED(pt_diag%pres_sfc) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%u ) IF( ASSOCIATED(pt_diag%u) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%v ) IF( ASSOCIATED(pt_diag%v) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%temp ) IF( ASSOCIATED(pt_diag%temp) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%pres ) IF( ASSOCIATED(pt_diag%pres) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%hdef_ic ) IF( ASSOCIATED(pt_diag%hdef_ic) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%div_ic ) IF( ASSOCIATED(pt_diag%div_ic) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%dwdx ) IF( ASSOCIATED(pt_diag%dwdx) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%dwdy ) IF( ASSOCIATED(pt_diag%dwdy) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%ddt_tracer_adv ) IF( ltke_adv)
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%pres_ifc ) IF( ASSOCIATED(pt_diag%pres_ifc) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%tempv ) IF( ASSOCIATED(pt_diag%tempv) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%temp_ifc ) IF( ASSOCIATED(pt_diag%temp_ifc) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%exner_dyn_incr ) IF( ASSOCIATED(pt_diag%exner_dyn_incr) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%airmass_now ) IF( ASSOCIATED(pt_diag%airmass_now) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_diag%airmass_new ) IF( ASSOCIATED(pt_diag%airmass_new) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%wgtfac_c ) IF( ASSOCIATED(p_metrics%wgtfac_c) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%z_ifc ) IF( ASSOCIATED(p_metrics%z_ifc) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%geopot_agl ) IF( ASSOCIATED(p_metrics%geopot_agl) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%geopot_agl_ifc ) IF( ASSOCIATED(p_metrics%geopot_agl_ifc) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%z_mc ) IF( ASSOCIATED(p_metrics%z_mc) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%mask_mtnpoints_g ) IF( ASSOCIATED(p_metrics%mask_mtnpoints_g) )
    !$ser verbatim   !$ACC UPDATE HOST( p_metrics%ddqz_z_full ) IF ( ASSOCIATED(p_metrics%ddqz_z_full) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog_rcf%tracer ) IF( ASSOCIATED(pt_prog_rcf%tracer) )
    !$ser verbatim   !$ACC UPDATE HOST( pt_prog_now_rcf%tke ) IF( ASSOCIATED(pt_prog_now_rcf%tke) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%gz0 ) IF( ASSOCIATED(prm_diag%gz0) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvm ) IF( ASSOCIATED(prm_diag%tvm) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvh ) IF( ASSOCIATED(prm_diag%tvh) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkvm ) IF( ASSOCIATED(prm_diag%tkvm) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkvh ) IF( ASSOCIATED(prm_diag%tkvh) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%shfl_s ) IF( ASSOCIATED(prm_diag%shfl_s) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qhfl_s ) IF( ASSOCIATED(prm_diag%qhfl_s) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%pat_len ) IF( ASSOCIATED(prm_diag%pat_len) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tropics_mask ) IF( ASSOCIATED(prm_diag%tropics_mask) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%innertropics_mask ) IF( ASSOCIATED(prm_diag%innertropics_mask) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkred_sfc ) IF( ASSOCIATED(prm_diag%tkred_sfc) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%gz0_t ) IF( ASSOCIATED(prm_diag%gz0_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tcm_t ) IF( ASSOCIATED(prm_diag%tcm_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tch_t ) IF( ASSOCIATED(prm_diag%tch_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvm_t ) IF( ASSOCIATED(prm_diag%tvm_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvh_t ) IF( ASSOCIATED(prm_diag%tvh_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tcm ) IF( ASSOCIATED(prm_diag%tcm) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tch ) IF( ASSOCIATED(prm_diag%tch) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tfm ) IF( ASSOCIATED(prm_diag%tfm) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tfh ) IF( ASSOCIATED(prm_diag%tfh) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tfv_t ) IF( ASSOCIATED(prm_diag%tfv_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkr_t ) IF( ASSOCIATED(prm_diag%tkr_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tfv ) IF( ASSOCIATED(prm_diag%tfv) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkr ) IF( ASSOCIATED(prm_diag%tkr) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkvm_s_t ) IF( ASSOCIATED(prm_diag%tkvm_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tkvh_s_t ) IF( ASSOCIATED(prm_diag%tkvh_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rcld ) IF( ASSOCIATED(prm_diag%rcld) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%ktop_envel ) IF( ASSOCIATED(prm_diag%ktop_envel) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%shfl_s_t ) IF( ASSOCIATED(prm_diag%shfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qhfl_s_t ) IF( ASSOCIATED(prm_diag%qhfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%umfl_s_t ) IF( ASSOCIATED(prm_diag%umfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%vmfl_s_t ) IF( ASSOCIATED(prm_diag%vmfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%lhfl_s_t ) IF( ASSOCIATED(prm_diag%lhfl_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%u_10m ) IF( ASSOCIATED(prm_diag%u_10m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%v_10m ) IF( ASSOCIATED(prm_diag%v_10m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%u_10m_t ) IF( ASSOCIATED(prm_diag%u_10m_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%v_10m_t ) IF( ASSOCIATED(prm_diag%v_10m_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tmax_2m ) IF( ASSOCIATED(prm_diag%tmax_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tmin_2m ) IF( ASSOCIATED(prm_diag%tmin_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%t_2m ) IF( ASSOCIATED(prm_diag%t_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qv_2m ) IF( ASSOCIATED(prm_diag%qv_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%td_2m ) IF( ASSOCIATED(prm_diag%td_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rh_2m ) IF( ASSOCIATED(prm_diag%rh_2m) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tvs_s_t ) IF( ASSOCIATED(prm_diag%tvs_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%t_2m_land ) IF (ASSOCIATED(prm_diag%t_2m_land) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%td_2m_land ) IF (ASSOCIATED(prm_diag%td_2m_land) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rh_2m_land ) IF (ASSOCIATED(prm_diag%rh_2m_land) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%dyn_gust ) IF (ASSOCIATED(prm_diag%dyn_gust) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%cloud_num(:,:) ) IF ( ASSOCIATED(prm_diag%cloud_num) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%tt_lheat ) IF ( ASSOCIATED(prm_diag%tt_lheat) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rain_gsp_rate ) IF ( ASSOCIATED(prm_diag%rain_gsp_rate) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%snow_gsp_rate ) IF ( ASSOCIATED(prm_diag%snow_gsp_rate) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%graupel_gsp_rate  ) IF ( ASSOCIATED(prm_diag%graupel_gsp_rate) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qrs_flux ) IF ( ASSOCIATED(prm_diag%qrs_flux) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%rain_gsp ) IF ( ASSOCIATED(prm_diag%rain_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%ice_gsp ) IF ( ASSOCIATED(prm_diag%ice_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%snow_gsp ) IF ( ASSOCIATED(prm_diag%snow_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%hail_gsp ) IF ( ASSOCIATED(prm_diag%hail_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%graupel_gsp ) IF ( ASSOCIATED(prm_diag%graupel_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%prec_gsp ) IF ( ASSOCIATED(prm_diag%prec_gsp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_diag%qcfl_s ) IF ( ASSOCIATED(prm_diag%qcfl_s) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tracer_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_tracer_turb) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tke ) IF( ASSOCIATED(prm_nwp_tend%ddt_tke) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tke_pconv ) IF( ASSOCIATED(prm_nwp_tend%ddt_tke_pconv) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tke_hsh ) IF( ASSOCIATED(prm_nwp_tend%ddt_tke_hsh) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_u_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_u_turb) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_v_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_v_turb) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_temp_turb ) IF( ASSOCIATED(prm_nwp_tend%ddt_temp_turb) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_u_sso ) IF( ASSOCIATED(prm_nwp_tend%ddt_u_sso) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_v_sso ) IF( ASSOCIATED(prm_nwp_tend%ddt_v_sso) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_temp_gscp ) IF ( ASSOCIATED(prm_nwp_tend%ddt_temp_gscp) )
    !$ser verbatim   !$ACC UPDATE HOST( prm_nwp_tend%ddt_tracer_gscp ) IF ( ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp) )
    !$ser verbatim   !$ACC UPDATE HOST( wtr_prog_now%t_ice ) IF( ASSOCIATED(wtr_prog_now%t_ice) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_prog_now%t_g ) IF( ASSOCIATED(lnd_prog_now%t_g) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_prog_now%t_snow_t ) IF( ASSOCIATED(lnd_prog_now%t_snow_t) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_diag%qv_s ) IF( ASSOCIATED(lnd_diag%qv_s) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_diag%qv_s_t ) IF (ASSOCIATED(lnd_diag%qv_s_t) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_diag%snowfrac_t ) IF (ASSOCIATED(lnd_diag%snowfrac_t) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_diag%snowfrac_lc_t ) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t) )
    !$ser verbatim   !$ACC UPDATE HOST( wtr_prog_new%h_ice ) IF (ASSOCIATED(wtr_prog_new%h_ice) )
    !$ser verbatim   !$ACC UPDATE HOST( lnd_prog_new%t_g_t ) IF (ASSOCIATED(lnd_prog_new%t_g_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%idx_lst_t ) IF (ASSOCIATED(ext_data%atm%idx_lst_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%gp_count_t ) IF (ASSOCIATED(ext_data%atm%gp_count_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%lc_class_t ) IF (ASSOCIATED(ext_data%atm%lc_class_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%z0_lcc_min ) IF (ASSOCIATED(ext_data%atm%z0_lcc_min) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%z0_lcc ) IF (ASSOCIATED(ext_data%atm%z0_lcc) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%sso_stdh_raw ) IF (ASSOCIATED(ext_data%atm%sso_stdh_raw) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%frac_t ) IF (ASSOCIATED(ext_data%atm%frac_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%plcov_t ) IF (ASSOCIATED(ext_data%atm%plcov_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%sai_t ) IF (ASSOCIATED(ext_data%atm%sai_t) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%sai ) IF (ASSOCIATED(ext_data%atm%sai) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%fr_land ) IF (ASSOCIATED(ext_data%atm%fr_land) )
    !$ser verbatim   !$ACC UPDATE HOST( ext_data%atm%depth_lk ) IF (ASSOCIATED(ext_data%atm%depth_lk) )
    !$ser verbatim END IF

#endif
    !$ser verbatim   CALL datetimeToString(time_config%tc_current_date, date)
    !$ser verbatim   CALL init('icon')
    !$ser savepoint nh_interface_nwp-output jg=jg nproma=nproma nlev=nlev date=TRIM(date)
    !$ser mode write

    !$ser data nh_interface_nwp_pt_prog_w=pt_prog%w(:,:,:) IF (ASSOCIATED(pt_prog%w))
    !$ser data nh_interface_nwp_pt_prog_vn=pt_prog%vn(:,:,:) IF (ASSOCIATED(pt_prog%vn))
    !$ser data nh_interface_nwp_pt_prog_rho=pt_prog%rho(:,:,:) IF (ASSOCIATED(pt_prog%rho))
    !$ser data nh_interface_nwp_pt_prog_exner=pt_prog%exner(:,:,:) IF (ASSOCIATED(pt_prog%exner))
    !$ser data nh_interface_nwp_pt_prog_theta_v=pt_prog%theta_v(:,:,:) IF (ASSOCIATED(pt_prog%theta_v))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqv=pt_prog_rcf%tracer(:,:,:,iqv) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqc=pt_prog_rcf%tracer(:,:,:,iqc) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqs=pt_prog_rcf%tracer(:,:,:,iqs) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqi=pt_prog_rcf%tracer(:,:,:,iqi) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqnc=pt_prog_rcf%tracer(:,:,:,iqnc) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqnr=pt_prog_rcf%tracer(:,:,:,iqnr) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqni=pt_prog_rcf%tracer(:,:,:,iqni) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqns=pt_prog_rcf%tracer(:,:,:,iqns) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqng=pt_prog_rcf%tracer(:,:,:,iqng) IF (lnumber)
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqr=pt_prog_rcf%tracer(:,:,:,iqr) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_rcf_tracer_iqg=pt_prog_rcf%tracer(:,:,:,iqg) IF (ASSOCIATED(pt_prog_rcf%tracer))
    !$ser data nh_interface_nwp_pt_prog_now_rcf=pt_prog_now_rcf%tke(:,:,:) IF (ASSOCIATED(pt_prog_now_rcf%tke))
    !$ser data nh_interface_nwp_pt_diag_u=pt_diag%u(:,:,:) IF (ASSOCIATED(pt_diag%u))
    !$ser data nh_interface_nwp_pt_diag_v=pt_diag%v(:,:,:) IF (ASSOCIATED(pt_diag%v))
    !$ser data nh_interface_nwp_pt_diag_temp=pt_diag%temp(:,:,:) IF (ASSOCIATED(pt_diag%temp))
    !$ser data nh_interface_nwp_pt_diag_pres=pt_diag%pres(:,:,:) IF (ASSOCIATED(pt_diag%pres))
    !$ser data nh_interface_nwp_pt_diag_hdef_ic=pt_diag%hdef_ic(:,:,:) IF (ASSOCIATED(pt_diag%hdef_ic))
    !$ser data nh_interface_nwp_pt_diag_div_ic=pt_diag%div_ic(:,:,:) IF (ASSOCIATED(pt_diag%div_ic))
    !$ser data nh_interface_nwp_pt_diag_dwdx=pt_diag%dwdx(:,:,:) IF (ASSOCIATED(pt_diag%dwdx))
    !$ser data nh_interface_nwp_pt_diag_dwdy=pt_diag%dwdy(:,:,:) IF (ASSOCIATED(pt_diag%dwdy))
    !$ser data nh_interface_nwp_pt_diag_ddt_tracer_adv_iqtke=pt_diag%ddt_tracer_adv(:,:,:,iqtke) IF (ltke_adv)
    !$ser data nh_interface_nwp_pt_diag_dpres_mc=pt_diag%dpres_mc(:,:,:) IF (ASSOCIATED(pt_diag%dpres_mc))
    !$ser data nh_interface_nwp_pt_diag_pres_sfc=pt_diag%pres_sfc(:,:) IF (ASSOCIATED(pt_diag%pres_sfc))
    !$ser data nh_interface_nwp_pt_diag_tempv=pt_diag%tempv(:,:,:) IF (ASSOCIATED(pt_diag%tempv))
    !$ser data nh_interface_nwp_p_metrics_wgtfac_c=p_metrics%wgtfac_c(:,:,:) IF (ASSOCIATED(p_metrics%wgtfac_c))
    !$ser data nh_interface_nwp_p_metrics_z_ifc=p_metrics%z_ifc(:,:,:) IF (ASSOCIATED(p_metrics%z_ifc))
    !$ser data nh_interface_nwp_p_metrics_geopot_agl=p_metrics%geopot_agl(:,:,:) IF (ASSOCIATED(p_metrics%geopot_agl))
    !$ser data nh_interface_nwp_p_metrics_geopot_agl_ifc=p_metrics%geopot_agl_ifc(:,:,:) IF (ASSOCIATED(p_metrics%geopot_agl_ifc))
    !$ser data nh_interface_nwp_p_metrics_z_mc=p_metrics%z_mc(:,:,:) IF (ASSOCIATED(p_metrics%z_mc))
    !$ser data nh_interface_nwp_p_metrics_ddqz_z_full=p_metrics%ddqz_z_full(:,:,:) IF (ASSOCIATED(p_metrics%ddqz_z_full))
    !$ser data nh_interface_nwp_p_metrics_mask_mtnpoints_g=p_metrics%mask_mtnpoints_g(:,:) IF (ASSOCIATED(p_metrics%mask_mtnpoints_g))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_turb_iqv=prm_nwp_tend%ddt_tracer_turb(:,:,:,iqv) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_turb_iqc=prm_nwp_tend%ddt_tracer_turb(:,:,:,iqc) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_turb_iqi=prm_nwp_tend%ddt_tracer_turb(:,:,:,iqi) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_temp_gscp=prm_nwp_tend%ddt_temp_gscp(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_temp_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqv=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqv) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqc=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqc) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqi=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqi) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqr=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqr) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tracer_gscp_iqs=prm_nwp_tend%ddt_tracer_gscp(:,:,:,iqs) IF (ASSOCIATED(prm_nwp_tend%ddt_tracer_gscp))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tke=prm_nwp_tend%ddt_tke(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_tke))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tke_pconv=prm_nwp_tend%ddt_tke_pconv(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_tke_pconv))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_tke_hsh=prm_nwp_tend%ddt_tke_hsh(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_tke_hsh))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_u_turb=prm_nwp_tend%ddt_u_turb(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_u_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_v_turb=prm_nwp_tend%ddt_v_turb(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_v_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_temp_turb=prm_nwp_tend%ddt_temp_turb(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_temp_turb))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_u_sso=prm_nwp_tend%ddt_u_sso(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_u_sso))
    !$ser data nh_interface_nwp_prm_nwp_tend_ddt_v_sso=prm_nwp_tend%ddt_v_sso(:,:,:) IF (ASSOCIATED(prm_nwp_tend%ddt_v_sso))
    !$ser data nh_interface_nwp_prm_wtr_prog_now_t_ice=wtr_prog_now%t_ice(:,:) IF (ASSOCIATED(wtr_prog_now%t_ice))
    !$ser data nh_interface_nwp_lnd_prg_now_t_g=lnd_prog_now%t_g(:,:) IF (ASSOCIATED(lnd_prog_now%t_g))
    !$ser data nh_interface_nwp_lnd_prg_now_t_snow_t=lnd_prog_now%t_snow_t(:,:,:) IF (ASSOCIATED(lnd_prog_now%t_snow_t))
    !$ser data nh_interface_nwp_lnd_diag_qv_s=lnd_diag%qv_s(:,:) IF (ASSOCIATED(lnd_diag%qv_s))
    !$ser data nh_interface_nwp_p_diag_pres_ifc=pt_diag%pres_ifc(:,:,:) IF (ASSOCIATED(pt_diag%pres_ifc))
    !$ser data nh_interface_nwp_prm_diag_gz0_t=prm_diag%gz0_t(:,:,:) IF (ASSOCIATED(prm_diag%gz0_t))
    !$ser data nh_interface_nwp_prm_diag_tcm_t=prm_diag%tcm_t(:,:,:) IF (ASSOCIATED(prm_diag%tcm_t))
    !$ser data nh_interface_nwp_prm_diag_tch_t=prm_diag%tch_t(:,:,:) IF (ASSOCIATED(prm_diag%tch_t))
    !$ser data nh_interface_nwp_prm_diag_tvh_t=prm_diag%tvh_t(:,:,:) IF (ASSOCIATED(prm_diag%tvh_t))
    !$ser data nh_interface_nwp_prm_diag_tcm=prm_diag%tcm(:,:) IF (ASSOCIATED(prm_diag%tcm))
    !$ser data nh_interface_nwp_prm_diag_tch=prm_diag%tch(:,:) IF (ASSOCIATED(prm_diag%tch))
    !$ser data nh_interface_nwp_prm_diag_tfm=prm_diag%tfm(:,:) IF (ASSOCIATED(prm_diag%tfm))
    !$ser data nh_interface_nwp_prm_diag_tfh=prm_diag%tfh(:,:) IF (ASSOCIATED(prm_diag%tfh))
    !$ser data nh_interface_nwp_prm_diag_tfv_t=prm_diag%tfv_t(:,:,:) IF (ASSOCIATED(prm_diag%tfv_t))
    !$ser data nh_interface_nwp_prm_diag_tkr_t=prm_diag%tkr_t(:,:,:) IF (ASSOCIATED(prm_diag%tkr_t))
    !$ser data nh_interface_nwp_prm_diag_tkvm_t=prm_diag%tkvm_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tkvm_s_t))
    !$ser data nh_interface_nwp_prm_diag_tkvh_t=prm_diag%tkvh_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tkvh_s_t))
    !$ser data nh_interface_nwp_prm_diag_rcld=prm_diag%rcld(:,:,:) IF (ASSOCIATED(prm_diag%rcld))
    !$ser data nh_interface_nwp_prm_diag_ktop_envel=prm_diag%ktop_envel(:,:) IF (ASSOCIATED(prm_diag%ktop_envel))
    !$ser data nh_interface_nwp_prm_diag_shfl_s_t=prm_diag%shfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%shfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_qhfl_s_t=prm_diag%qhfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%qhfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_umfl_s_t=prm_diag%umfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%umfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_vmfl_s_t=prm_diag%vmfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%vmfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_lhfl_s_t=prm_diag%lhfl_s_t(:,:,:) IF (ASSOCIATED(prm_diag%lhfl_s_t))
    !$ser data nh_interface_nwp_prm_diag_umfl_s=prm_diag%umfl_s(:,:) IF (ASSOCIATED(prm_diag%umfl_s))
    !$ser data nh_interface_nwp_prm_diag_vmfl_s=prm_diag%vmfl_s(:,:) IF (ASSOCIATED(prm_diag%vmfl_s))
    !$ser data nh_interface_nwp_prm_diag_lhfl_s=prm_diag%lhfl_s(:,:) IF (ASSOCIATED(prm_diag%lhfl_s))
    !$ser data nh_interface_nwp_prm_diag_u_10m=prm_diag%u_10m(:,:) IF (ASSOCIATED(prm_diag%u_10m))
    !$ser data nh_interface_nwp_prm_diag_v_10m=prm_diag%v_10m(:,:) IF (ASSOCIATED(prm_diag%v_10m))
    !$ser data nh_interface_nwp_prm_diag_u_10m_t=prm_diag%u_10m_t(:,:,:) IF (ASSOCIATED(prm_diag%u_10m_t))
    !$ser data nh_interface_nwp_prm_diag_v_10m_t=prm_diag%v_10m_t(:,:,:) IF (ASSOCIATED(prm_diag%v_10m_t))
    !$ser data nh_interface_nwp_prm_diag_tmax_2m=prm_diag%tmax_2m(:,:) IF (ASSOCIATED(prm_diag%tmax_2m))
    !$ser data nh_interface_nwp_prm_diag_tmin_2m=prm_diag%tmin_2m(:,:) IF (ASSOCIATED(prm_diag%tmin_2m))
    !$ser data nh_interface_nwp_prm_diag_t_2m=prm_diag%t_2m(:,:) IF (ASSOCIATED(prm_diag%t_2m))
    !$ser data nh_interface_nwp_prm_diag_qv_2m=prm_diag%qv_2m(:,:) IF (ASSOCIATED(prm_diag%qv_2m))
    !$ser data nh_interface_nwp_prm_diag_td_2m=prm_diag%td_2m(:,:) IF (ASSOCIATED(prm_diag%td_2m))
    !$ser data nh_interface_nwp_prm_diag_rh_2m=prm_diag%rh_2m(:,:) IF (ASSOCIATED(prm_diag%rh_2m))
    !$ser data nh_interface_nwp_prm_diag_tvs_s_t=prm_diag%tvs_s_t(:,:,:) IF (ASSOCIATED(prm_diag%tvs_s_t))
    !$ser data nh_interface_nwp_prm_diag_tfv=prm_diag%tfv(:,:) IF (ASSOCIATED(prm_diag%tfv))
    !$ser data nh_interface_nwp_prm_diag_tkr=prm_diag%tkr(:,:) IF (ASSOCIATED(prm_diag%tkr))
    !$ser data nh_interface_nwp_prm_diag_t_2m_land=prm_diag%t_2m_land(:,:) IF (ASSOCIATED(prm_diag%t_2m_land))
    !$ser data nh_interface_nwp_prm_diag_td_2m_land=prm_diag%td_2m_land(:,:) IF (ASSOCIATED(prm_diag%td_2m_land))
    !$ser data nh_interface_nwp_prm_diag_rh_2m_land=prm_diag%rh_2m_land(:,:) IF (ASSOCIATED(prm_diag%rh_2m_land))
    !$ser data nh_interface_nwp_prm_diag_dyn_gust=prm_diag%dyn_gust(:,:) IF (ASSOCIATED(prm_diag%dyn_gust))
    !$ser data nh_interface_nwp_prm_diag_cloud_num=prm_diag%cloud_num(:,:) IF (ASSOCIATED(prm_diag%cloud_num))
    !$ser data nh_interface_nwp_prm_diag_tt_lheat=prm_diag%tt_lheat(:,:,:) IF (ASSOCIATED(prm_diag%tt_lheat))
    !$ser data nh_interface_nwp_prm_diag_rain_gsp_rate=prm_diag%rain_gsp_rate(:,:) IF (ASSOCIATED(prm_diag%rain_gsp_rate))
    !$ser data nh_interface_nwp_prm_diag_snow_gsp_rate=prm_diag%snow_gsp_rate(:,:) IF (ASSOCIATED(prm_diag%snow_gsp_rate))
    !$ser data nh_interface_nwp_prm_diag_graupel_gsp_rate=prm_diag%graupel_gsp_rate (:,:) IF (ASSOCIATED(prm_diag%graupel_gsp_rate))
    !$ser data nh_interface_nwp_prm_diag_qrs_flux=prm_diag%qrs_flux(:,:,:) IF (ASSOCIATED(prm_diag%qrs_flux))
    !$ser data nh_interface_nwp_prm_diag_rain_gsp=prm_diag%rain_gsp(:,:) IF (ASSOCIATED(prm_diag%rain_gsp))
    !$ser data nh_interface_nwp_prm_diag_ice_gsp=prm_diag%ice_gsp(:,:) IF (ASSOCIATED(prm_diag%ice_gsp))
    !$ser data nh_interface_nwp_prm_diag_snow_gsp=prm_diag%snow_gsp(:,:) IF (ASSOCIATED(prm_diag%snow_gsp))
    !$ser data nh_interface_nwp_prm_diag_hail_gsp=prm_diag%hail_gsp(:,:) IF (ASSOCIATED(prm_diag%hail_gsp))
    !$ser data nh_interface_nwp_prm_diag_graupel_gsp=prm_diag%graupel_gsp(:,:) IF (ASSOCIATED(prm_diag%graupel_gsp))
    !$ser data nh_interface_nwp_prm_diag_prec_gsp=prm_diag%prec_gsp(:,:) IF (ASSOCIATED(prm_diag%prec_gsp))
    !$ser data nh_interface_nwp_prm_diag_qcfl_s=prm_diag%qcfl_s(:,:) IF (ASSOCIATED(prm_diag%qcfl_s))
    !$ser data nh_interface_nwp_prm_diag_gz0=prm_diag%gz0(:,:) IF (ASSOCIATED(prm_diag%gz0))
    !$ser data nh_interface_nwp_prm_diag_tvm=prm_diag%tvm(:,:) IF (ASSOCIATED(prm_diag%tvm))
    !$ser data nh_interface_nwp_prm_diag_tvh=prm_diag%tvh(:,:) IF (ASSOCIATED(prm_diag%tvh))
    !$ser data nh_interface_nwp_prm_diag_tkvm=prm_diag%tkvm(:,:,:) IF (ASSOCIATED(prm_diag%tkvm))
    !$ser data nh_interface_nwp_prm_diag_tkvh=prm_diag%tkvh(:,:,:) IF (ASSOCIATED(prm_diag%tkvh))
    !$ser data nh_interface_nwp_prm_diag_shfl_s=prm_diag%shfl_s(:,:) IF (ASSOCIATED(prm_diag%shfl_s))
    !$ser data nh_interface_nwp_prm_diag_qhfl_s=prm_diag%qhfl_s(:,:) IF (ASSOCIATED(prm_diag%qhfl_s))
    !$ser data nh_interface_nwp_prm_diag_pat_len=prm_diag%pat_len(:,:) IF (ASSOCIATED(prm_diag%pat_len))
    !$ser data nh_interface_nwp_prm_diag_tropics_mask=prm_diag%tropics_mask(:,:) IF (ASSOCIATED(prm_diag%tropics_mask))
    !$ser data nh_interface_nwp_prm_diag_innertropics_mask=prm_diag%innertropics_mask(:,:) IF (ASSOCIATED(prm_diag%innertropics_mask))
    !$ser data nh_interface_nwp_prm_diag_tkred_sfc=prm_diag%tkred_sfc(:,:) IF (ASSOCIATED(prm_diag%tkred_sfc))
    !$ser data nh_interface_nwp_wtr_prog_new_h_ice=wtr_prog_new%h_ice(:,:) IF (ASSOCIATED(wtr_prog_new%h_ice))
    !$ser data nh_interface_nwp_lnd_prog_new_t_g_t=lnd_prog_new%t_g_t(:,:,:) IF (ASSOCIATED(lnd_prog_new%t_g_t))
    !$ser data nh_interface_nwp_lnd_diag_qv_s_t=lnd_diag%qv_s_t(:,:,:) IF (ASSOCIATED(lnd_diag%qv_s_t))
    !$ser data nh_interface_nwp_lnd_diag_snowfrac_t=lnd_diag%snowfrac_t(:,:,:) IF (ASSOCIATED(lnd_diag%snowfrac_t))
    !$ser data nh_interface_nwp_lnd_diag_snowfrac_lc_t=lnd_diag%snowfrac_lc_t(:,:,:) IF (ASSOCIATED(lnd_diag%snowfrac_lc_t))
    !$ser data nh_interface_nwp_ext_data_idx_lst_t=ext_data%atm%idx_lst_t IF (ASSOCIATED(ext_data%atm%idx_lst_t))
    !$ser data nh_interface_nwp_ext_data_gp_count_t=ext_data%atm%gp_count_t IF (ASSOCIATED(ext_data%atm%gp_count_t))
    !$ser data nh_interface_nwp_ext_data_lc_class_t=ext_data%atm%lc_class_t IF (ASSOCIATED(ext_data%atm%lc_class_t))
    !$ser data nh_interface_nwp_ext_data_z0_lcc_min=ext_data%atm%z0_lcc_min IF (ASSOCIATED(ext_data%atm%z0_lcc_min))
    !$ser data nh_interface_nwp_ext_data_z0_lcc=ext_data%atm%z0_lcc IF (ASSOCIATED(ext_data%atm%z0_lcc))
    !$ser data nh_interface_nwp_ext_data_sso_stdh_raw=ext_data%atm%sso_stdh_raw IF (ASSOCIATED(ext_data%atm%sso_stdh_raw))
    !$ser data nh_interface_nwp_ext_data_frac_t=ext_data%atm%frac_t IF (ASSOCIATED(ext_data%atm%frac_t))
    !$ser data nh_interface_nwp_ext_data_plcov_t=ext_data%atm%plcov_t IF (ASSOCIATED(ext_data%atm%plcov_t))
    !$ser data nh_interface_nwp_ext_data_sai_t=ext_data%atm%sai_t IF (ASSOCIATED(ext_data%atm%sai_t))
    !$ser data nh_interface_nwp_ext_data_sai=ext_data%atm%sai IF (ASSOCIATED(ext_data%atm%sai))
    !$ser data nh_interface_nwp_ext_data_fr_land=ext_data%atm%fr_land IF (ASSOCIATED(ext_data%atm%fr_land))
    !$ser data nh_interface_nwp_ext_data_depth_lk=ext_data%atm%depth_lk IF (ASSOCIATED(ext_data%atm%depth_lk))
    !$ser verbatim END IF

  END SUBROUTINE serialize_nh_interface_nwp_output

END MODULE mo_ser_nh_interface_nwp
