# CLAW SCA model configuration for JSBACH in ICON

[model]
  name = "ICON_JSBACH"

[[dimensions]] # Definition of dimensions that can be used in layouts
  id = "jsb_hori"
  [dimensions.size]
    lower = 1             # if not specified, 1 by default
    upper = "nc"      # mandatory information

[[dimensions]]
  id = "jsb_soil"
  [dimensions.size]
    lower = 1
    upper = "nsoil"

[[layouts]] # Definition of layouts and default layout for specific target
  id = "default" # mandatory layout, used if no specific target layout
                 # specified
  position = [ "jsb_hori", ":" ]

[[layouts]]
  id = "nc_nsoil"
  position = [ "jsb_hori", "jsb_soil", ":" ]

