#! /bin/ksh
#-----------------------------------------------------------------------------
#PBS -q xc_norm_h
#PBS -l select=10:ompthreads=4
#PBS -l place=scatter
#PBS -l walltime=01:00:00
#PBS -j oe
# ----------------------------------------------------------------------
# Basic CRAY batch script for the ICON model
#
# Platform: xct.dwd.de
#
# 06-07/2013 : F. Prill, DWD
# ----------------------------------------------------------------------

set -x

export OMP_SCHEDULE="static"
export OMP_DYNAMIC="false"

# ----------------------------------------------------------------------
# path definitions
# ----------------------------------------------------------------------

# for PBS change to directory where job was submitted
# (without this job is started in HOME)
if [[ -n ${PBS_O_WORKDIR} ]] ; then
  cd ${PBS_O_WORKDIR}
fi

# determine base directory
ICONDIR=${PBS_O_WORKDIR}/../../

EXP="NWP"    # experiment identifier
EDIR="exp02"  # working directory


# absolute path to directory with plenty of space:
EXPDIR=$TMPDIR/../experiments/${EDIR}

# absolute path to model binary, including the executable
MODEL=$ICONDIR/build/x86_64-unknown-linux-gnu/bin/icon

# ----------------------------------------------------------------------
# copy input data: grids, external parameters
# ----------------------------------------------------------------------

# the directory for the experiment will be created, if not already there
if [ ! -d $EXPDIR ]; then
    mkdir -p $EXPDIR
fi
cd $EXPDIR

# root directory for input data
DATAROOT=/lustre2/rwork0/routfor/test/icon/Checksuite_data/


ln -sf ${DATAROOT}/GRF_R2B13lim/iconR2B13_DOM01.nc .




# ----------------------------------------------------------------------
# global namelist settings
# ----------------------------------------------------------------------

# the namelist filename
atmo_namelist=NAMELIST_${EXP}

# global timing
start_date="2012-06-20T00:00:00Z"
ndays_restart=60
dt_restart=$((${ndays_restart}*86400))



# the grid parameters
atmo_dyn_grids="iconR2B13_DOM01.nc" 


# ----------------------------------------------------------------------
# create ICON master namelist
# ----------------------------------------------------------------------

# For a complete list see Namelist_overview and Namelist_overview.pdf

cat > icon_master.namelist << EOF
&master_nml
 lrestart               = .false.
/
&time_nml
 ini_datetime_string = "$start_date"
 dt_restart          = $dt_restart
/
&master_model_nml
  model_type=1
  model_name="ATMO"
  model_namelist_filename="$atmo_namelist"
  model_min_rank=1
  model_max_rank=65536
  model_inc_rank=1
/
EOF


# ----------------------------------------------------------------------
# model namelists
# ----------------------------------------------------------------------

# reconstrcuct the grid parameters in namelist form
dynamics_grid_filename=""
for gridfile in ${atmo_dyn_grids}; do
  dynamics_grid_filename="${dynamics_grid_filename} '${gridfile}',"
done
radiation_grid_filename=""
for gridfile in ${atmo_rad_grids}; do
  radiation_grid_filename="${radiation_grid_filename} '${gridfile}',"
done


cat > ${atmo_namelist} << EOF
&parallel_nml
 nproma         = 8
 p_test_run     = .false.
 l_test_openmp  = .true.
 l_log_checks   = .true.
 iorder_sendrecv = 3
 num_io_procs   = 0 ! 1
/
&grid_nml
 dynamics_grid_filename  = ${dynamics_grid_filename}
 radiation_grid_filename = ' '
 dynamics_parent_grid_id = 0,1
 lredgrid_phys           = .false.,.false.
 lfeedback               = .true.
 l_limited_area = .true.
/
&nh_testcase_nml
 nh_test_name  = 'mrw_nh'    ! test case identifier
 u0_mrw       = 20 
 mount_height_mrw = 5000. ! max. 7750m with 25 m/s
 mount_half_width = 2000.
 mount_latctr_mrw_deg = 0.
 bruntvais_u_mwbr_const = 0.0075 ! 0.018228
 p_int_mwbr_const = 80000.
 rh_at_1000hpa  = 0.01
 qv_max         = 1.e-5
/
&output_nml
 filetype           = 4                    ! output format: 2=GRIB2, 4=NETCDFv2
 mode               = 1
 dom                = -1                   ! output for all subdomains
 output_bounds      = 0., 36000., 1800. ! start, end, increment
 steps_per_file     = 21
 include_last       = .TRUE.
 output_filename    = 'MRW_R2B13_ll'               ! file name base
 ml_varlist         =     'w','pres','pres_sfc', 'u', 'v', 'temp', 'topography_c','theta_v', 'z_mc','z_ifc'
! ml_varlist         =     'pres_sfc'
 remap              = 1
 reg_lon_def        =  89.,0.005,91.
 reg_lat_def        = -1.,0.005, 1.
 output_grid        = .TRUE.
/
&run_nml
 num_lev  = 50
 lvert_nest = .true.
 nsteps         = 200
 dtime          = 3.6
 ldynamics      = .TRUE.       ! dynamics
 ltransport     = .false.
 ntracer        = 0            ! default: 0
 iforcing       = 3            ! NWP forcing
 ltestcase      = .true.      ! false: run with real data
 msg_level      = 7           ! detailed report during integration
 ltimer         = .true.
 timers_level   = 10
 output         = "nml" ! "nml"
/
&nwp_phy_nml
inwp_gscp       = 0
inwp_convection = 0
inwp_radiation  = 0
inwp_cldcover   = 0
inwp_turb       = 1
inwp_satad      = 0
inwp_surface    = 0
/
&turbdiff_nml
pat_len = 100.
c_diff  = 0.2
tkhmin  = 0.75
tkmmin  = 0.75
lconst_z0 = .true.
const_z0 = 0.000001
icldm_tran=-1
icldm_turb=-1
lfreeslip=.true.
/
&nonhydrostatic_nml
 iadv_rhotheta = 2
 ivctype       = 2
 itime_scheme   = 5
 ndyn_substeps = 6
 damp_height  = 27500.
 rayleigh_coeff = 0.75
 exner_expol = 0.333
 vwind_offctr = 0.20
 igradp_method = 5
 l_zdiffu_t    = .true.
 thslp_zdiffu   = 0.05
 thhgtd_zdiffu  = 125.
 lhdiff_rcf    = .true.
 divdamp_fac   = 0.004
 divdamp_order = 4
/
&sleve_nml
 min_lay_thckn   = 20.
 top_height      = 40000.
 decay_scale_1   = 5500.
 decay_scale_2   = 3500.
 decay_exp       = 1.2
 flat_height     = 19000.
 stretch_fac     = 0.85
/
&dynamics_nml
 iequations     = 3
 idiv_method    = 1
 divavg_cntrwgt = 0.50
 lcoriolis      = .TRUE.
/
&transport_nml
  ctracer_list  = '12345'
! ivadv_tracer  = 3,3,3,3,3
! itype_hlimit = 3,4,4,4,4,0
! ihadv_tracer  = 3,2,2,2,2,0
 ihadv_tracer = 0,0,0,0,0,0,0
 ivadv_tracer = 0,0,0,0,0,0,0
/
&diffusion_nml
 hdiff_order      = 5
 hdiff_efdt_ratio = 25.0 
 hdiff_smag_fac   = 0.025
 lhdiff_vn        = .TRUE.
 lhdiff_temp      = .TRUE.
 itype_t_diffu    = 2
 lsmag_3d         = .TRUE.
/
&interpol_nml
nudge_zone_width  = 8
rbf_vec_scale_c =  0.03
rbf_vec_scale_v =  0.07
rbf_vec_scale_e = 0.25
rbf_scale_mode_ll = 1
/
&gridref_nml
 grf_intmethod_ct = 2
 grf_tracfbk      = 2
 denom_diffu_v    = 150.
/
&extpar_nml
 itopo          = 0
 n_iter_smooth_topo = 2
 heightdiff_threshold = 2000.
/
EOF


# ----------------------------------------------------------------------
# run the model!
# ----------------------------------------------------------------------
 cp -p $MODEL icon.exe
 aprun  -n 120 -N 12 -j 2 -d 4 -m 5g icon.exe



