#! /bin/ksh
#-----------------------------------------------------------------------------
#PBS -q xc_norm_b
#PBS -l select=20:ompthreads=6
#PBS -l place=scatter
#PBS -l walltime=08:00:00
#PBS -j oe
# ----------------------------------------------------------------------
# Basic CRAY batch script for the ICON model
#
# Platform: xct.dwd.de
#
# 06-07/2013 : F. Prill, DWD
# ----------------------------------------------------------------------
#
#

set -x

export OMP_SCHEDULE="static"
export OMP_DYNAMIC="false"
export ATP_ENABLED=1
export MPICH_RMA_OVER_DMAPP=1
# disable core dumps
export RLIMIT_CORE=0
export ATP_MAX_CORES=0

# ----------------------------------------------------------------------
# path definitions
# ----------------------------------------------------------------------

# for PBS change to directory where job was submitted
# (without this job is started in HOME)
if [[ -n ${PBS_O_WORKDIR} ]] ; then
  cd ${PBS_O_WORKDIR}
fi

# base directory for ICON sources and binary:
ICONDIR=${PBS_O_WORKDIR}/../../

EXP="LIMtest"    # experiment identifier
EDIR="exp4"  # working directory

# absolute path to directory with plenty of space:
EXPDIR=$TMPDIR/../experiments/${EDIR}

# root directory for input data
DATAROOT=/lustre2/rwork0/routfor/test/icon/Checksuite_data/

# directory for grid and extpar files
GRIDDIR=${DATAROOT}/GRF_R3B9lim/
EXTPDIR=${DATAROOT}/Extpar_R3B9lim/

# absolute path to input directory
DATADIR=${DATAROOT}/Inidata_R3B9lim
LBCDIR=${DATAROOT}/Lbcdata_R3B9lim

# absolute path to model binary, including the executable
 MODEL=$ICONDIR/build/x86_64-unknown-linux-gnu/bin/icon


# ----------------------------------------------------------------------
# copy input data: grids, external parameters
# ----------------------------------------------------------------------

# the directory for the experiment will be created, if not already there
if [ ! -d $EXPDIR ]; then
    mkdir -p $EXPDIR
fi
cd $EXPDIR

ln -sf $GRIDDIR/icongrid_DOM01.parent.nc iconR3B08_DOM00.nc
ln -sf $GRIDDIR/icongrid_DOM01.nc iconR3B09_DOM01.nc
ln -sf $GRIDDIR/icongrid_DOM01_lbc.grid.nc iconR3B09_DOM01_lbc.nc

ln -sf $EXTPDIR/extpar_R3B09_DOM01.nc extpar_iconR3B09_DOM01.nc



ln -sf $DATADIR/prepiconR3B09_DOM01_01.grb prepiconR3B09_DOM01.grb

# files needed for radiation
cp $HOME/icon-dev/data/ECHAM6_CldOptProps.nc .
cp $HOME/icon-dev/data/rrtmg_lw.nc .


for filenr in `seq -f "%02.0f" 1 4` ; do
  hr=`expr $filenr - 1`
  ln -sf $LBCDIR/lbc_R3B09_DOM01_${filenr}.grb lbc_R3B09_DOM01_201607110${hr}.grb
done


ln -sf $ICONDIR/run/dict.latbc .

# ----------------------------------------------------------------------
# global namelist settings
# ----------------------------------------------------------------------

# the namelist filename
atmo_namelist=NAMELIST_${EXP}

# global timing
start_date="2016-07-11T00:00:00Z"
ndays_restart=60
dt_restart=$((${ndays_restart}*86400))



# the grid parameters
atmo_dyn_grids="iconR3B09_DOM01.nc"
atmo_rad_grids="iconR3B08_DOM00.nc"


# ----------------------------------------------------------------------
# create ICON master namelist
# ----------------------------------------------------------------------

# For a complete list see Namelist_overview and Namelist_overview.pdf

cat > icon_master.namelist << EOF
&master_nml
 lrestart               = .false.
/
&time_nml
 ini_datetime_string = "$start_date"
 dt_restart          = $dt_restart
/
&master_model_nml
  model_type=1
  model_name="ATMO"
  model_namelist_filename="$atmo_namelist"
  model_min_rank=1
  model_max_rank=65536
  model_inc_rank=1
/
EOF


# ----------------------------------------------------------------------
# model namelists
# ----------------------------------------------------------------------

# reconstrcuct the grid parameters in namelist form
dynamics_grid_filename=""
for gridfile in ${atmo_dyn_grids}; do
  dynamics_grid_filename="${dynamics_grid_filename} '${gridfile}',"
done
radiation_grid_filename=""
for gridfile in ${atmo_rad_grids}; do
  radiation_grid_filename="${radiation_grid_filename} '${gridfile}',"
done

plevels="5000,10000,15000,20000,25000,30000,40000,50000,70000,85000"


cat > ${atmo_namelist} << EOF
&parallel_nml
 nproma          =  8
 p_test_run      = .false.
 l_test_openmp   = .true.
 l_log_checks    = .true.
 num_io_procs    =  2
 num_restart_procs = 0
 num_prefetch_proc = 1
 itype_comm      =  1
 iorder_sendrecv =  3
/
&grid_nml
 dynamics_grid_filename  = ${dynamics_grid_filename}
 radiation_grid_filename = ${radiation_grid_filename}
 dynamics_parent_grid_id = 0,1
 lredgrid_phys           = .true.
 lfeedback               = .true.
 l_limited_area          = .true.
 ifeedback_type          = 2
 start_time  = 0., 1800.,3600.,
/
&initicon_nml
 init_mode                    = 7
 zpbl1                        = 500.
 zpbl2                        = 1000.
 lread_ana                    = .false. ! (T) Read dwdana
 dwdfg_filename               = "prepiconR3B09_DOM01.grb"
! dwdana_filename              = "<path>an_R<nroot0>B<jlev>_DOM<idom>.grb"
 ana_varnames_map_file        = "map_file.ana"
 ltile_coldstart              = .TRUE.
 ltile_init                   = .TRUE.
/
&limarea_nml
 itype_latbc     = 1
 dtime_latbc     = 3600.
 nlev_latbc      = 60
! latbc_path      = '${LATBC_PATH}'
 latbc_boundary_grid = 'iconR3B09_DOM01_lbc.nc'
 latbc_varnames_map_file = 'dict.latbc'
 latbc_filename  = 'lbc_R<nroot>B<jlev>_DOM01_<y><m><d><h>.grb'
/
&io_nml
 itype_pres_msl               = 4        ! (1) 3: IFS-type extrapolation
 itype_rh                     = 1         ! (1) 2: mixed phase (water and ice)
! output_nml_dict              = 'map_file.fc'
 lmask_boundary               = .true.
/
&output_nml
 filetype                     =  4                        ! output format: 2=GRIB2, 4=NETCDFv2
 dom                          =  1                       ! write all domains
 output_bounds                =  0., 10000000., 10800.    ! start, end, increment
 steps_per_file               =  1
 mode                         =  1                        ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last                 = .FALSE.
 output_filename              = '${EXP}'                   ! file name base
 ml_varlist='u', 'v', 'w', 'temp', 'pres','topography_c', 'pres_msl', 'qv', 'cloud_num', 'tai', 'h_snow', 
'group:precip_vars', 'group:additional_precip_vars', 'group:land_vars', 'group:land_tile_vars', 'freshsnow', 'albdif'
 output_grid                  =  .TRUE.
 stream_partitions_ml = 2
/
&run_nml
 num_lev        = 60
 lvert_nest     = .false.
 nsteps         = 360 ! 8640
 dtime          = 30.     ! timestep in seconds
 ldynamics      = .TRUE.       ! dynamics
 ltransport     = .true.
 ntracer        = 5            ! default: 0
 iforcing       = 3
 ltestcase      = .false.
 msg_level      = 7 ! detailed report during integration
 ltimer         = .true.
 timers_level   = 10
 check_uuid_gracefully = .true.
 output         = "nml" ! "nml"
/
&nwp_phy_nml
inwp_gscp       = 2,2,
inwp_convection = 1,0
inwp_radiation  = 1
inwp_cldcover   = 1
inwp_turb       = 1
inwp_satad      = 1
inwp_sso        = 0,0
inwp_gwd        = 0,0
inwp_surface    = 1
latm_above_top  = .true.
ldetrain_conv_prec = .true.
efdt_min_raylfric = 7200.
itype_z0         = 2
icapdcycl        = 3
icpl_aero_conv   = 1
icpl_aero_gscp   = 1
dt_rad    = 720.
dt_conv   = 180.,90.,90.,
dt_sso    = 360.,360.,360.,
dt_gwd    = 360.,360.,360.,
/
&nwp_tuning_nml
itune_albedo = 1
/
&turbdiff_nml
  tkhmin        = 0.75
  tkmmin        = 0.75
  pat_len       = 750.
  rat_sea       = 7.5
  ltkesso       = .true.
  frcsmot       = 0.2   ! these 2 switches together apply vertical smoothing of the TKE source terms
  imode_frcsmot = 2     ! in the tropics (only), which reduces the moist bias in the tropical lower troposphere
 ! use horizontal shear production terms with 1/SQRT(Ri) scaling to prevent unwanted side effects:
  itype_sher    = 3    
  ltkeshs       = .true.
  a_hshr        = 2.0
  icldm_turb    = 1
/
&lnd_nml
  ntiles         = 3       ! 3      (tests)
  nlev_snow      = 3
  lmulti_snow    = .false. ! .true. (tests)
  itype_heatcond = 2
  idiag_snowfrac = 20
  lsnowtile      = .true.
  lseaice        = .true.
  llake          = .true.
  itype_lndtbl   = 3 
  itype_root     = 2
/
&radiation_nml
  irad_o3     = 7
  irad_aero   = 6
  albedo_type = 2          ! Modis albedo
  vmr_co2     = 390.e-06   ! values representative for 2012
  vmr_ch4     = 1800.e-09
  vmr_n2o     = 322.0e-09
  vmr_o2      = 0.20946
  vmr_cfc11   = 240.e-12
  vmr_cfc12   = 532.e-12 
/
&nonhydrostatic_nml
  iadv_rhotheta   = 2
  ivctype         = 2
  itime_scheme    = 4
  exner_expol     = 0.333
  vwind_offctr    = 0.2
  damp_height     = 15000.
  rayleigh_coeff  = 0.75
  divdamp_fac     = 0.004   ! 0.004 for R2B6; recommendation for R3B7: 0.003
  divdamp_order   = 24 ! 2 ass, 24 fc - may become unnecessary with incremental analysis update
  divdamp_type    = 3  ! optional: 2 assimilation cycle, 3 forecast
  l_open_ubc      = .false.
  igradp_method   = 3
  l_zdiffu_t      = .true.
  thslp_zdiffu    = 0.02
  thhgtd_zdiffu   = 125.
  htop_moist_proc = 22500.
  hbot_qvsubstep  = 22500 ! r3b7: 19000.  else: 22500.
/
&sleve_nml
 min_lay_thckn   = 20.
 top_height      = 22000.
 stretch_fac     = 0.9
 decay_scale_1   = 4000.
 decay_scale_2   = 2500.
 decay_exp       = 1.2
 flat_height     = 16000.
/
&dynamics_nml
 iequations     = 3
 idiv_method    = 1
 divavg_cntrwgt = 0.50
 lcoriolis      = .true.
/
&transport_nml
 ctracer_list = '12345'
 ivadv_tracer = 3,3,3,3,3,3
 itype_hlimit = 3,4,4,4,4,4
 ihadv_tracer = 52,2,2,2,2,2
 llsq_svd       = .TRUE.
 beta_fct       = 1.005
/
&diffusion_nml
 hdiff_order      = 5
 itype_vn_diffu   = 1
 itype_t_diffu    = 2
 hdiff_efdt_ratio = 24 ! 24.0  for R2B6; recommendation for R3B7: 30.0
 hdiff_smag_fac   = 0.025   ! 0.025 for R2B6; recommendation for R3B7: 0.02
 lhdiff_vn        = .true.
 lhdiff_temp      = .true.
/
&interpol_nml
  nudge_zone_width = 8
  lsq_high_ord     = 3
  l_intp_c2l       = .true.
  l_mono_c2l       = .true.
/
&gridref_nml
 grf_intmethod_e  = 6
 grf_intmethod_ct = 2
 grf_tracfbk      = 2
 denom_diffu_v    = 150.
/
&extpar_nml
 itopo                = 1
 n_iter_smooth_topo   = 1,1,1,1,1,1
 hgtdiff_max_smooth_topo = 750.,750.,750.,750.,750.,750.
 heightdiff_threshold = 2250.,1500.
/
EOF

cat > map_file.ana << EOF2
# internal name     GRIB2 shortName
theta_v             THETA_V
rho                 DEN
vn                  VN
u                   U
v                   V
w                   W
tke                 TKE
temp                T
pres                P
qv                  QV
qc                  QC
qi                  QI
qr                  QR
qs                  QS
t_g                 T_G
qv_s                QV_S
fr_seaice           FR_ICE
t_ice               T_ICE
h_ice               H_ICE
t_snow              T_SNOW
freshsnow           FRESHSNW
w_snow              W_SNOW
rho_snow            RHO_SNOW
h_snow              H_SNOW
w_i                 W_I
w_so                W_SO
w_so_ice            W_SO_ICE
t_so                T_SO
smi                 SMI
gz0                 Z0
pres_sfc            PS
z_ifc               HHL

t_mnw_lk            T_MNW_LK
t_wml_lk            T_WML_LK
h_ml_lk             H_ML_LK
t_bot_lk            T_BOT_LK
c_t_lk              C_T_LK
t_b1_lk             T_B1_LK
h_b1_lk             H_B1_LK
EOF2

# ----------------------------------------------------------------------
# run the model!
# ----------------------------------------------------------------------
 cp -p $MODEL icon.exe
 aprun  -n 240 -N 12 -j 2 -d 6 -m 3g icon.exe


