#! /bin/ksh
#-----------------------------------------------------------------------------
#PBS -q xc_norm_b
#PBS -l select=80:ompthreads=6
#PBS -l place=scatter
#PBS -l walltime=01:30:00
#PBS -j oe
# ----------------------------------------------------------------------
# Basic CRAY batch script for the ICON model
#
# Platform: xct.dwd.de
#
# 06-07/2013 : F. Prill, DWD
# ----------------------------------------------------------------------
#
#

set -x

export OMP_SCHEDULE="static"
export OMP_DYNAMIC="false"
 export ATP_ENABLED=1
 export MPICH_RMA_OVER_DMAPP=1
# export UGNI_CDM_MDD_DEDICATED=2

# ----------------------------------------------------------------------
# path definitions
# ----------------------------------------------------------------------

# for PBS change to directory where job was submitted
# (without this job is started in HOME)
if [[ -n ${PBS_O_WORKDIR} ]] ; then
  cd ${PBS_O_WORKDIR}
fi

# determine base directory
ICONDIR=${PBS_O_WORKDIR}/../../

EXP="NWP"    # experiment identifier
EDIR="exp1"  # working directory

# absolute path to directory with plenty of space:
EXPDIR=$TMPDIR/../experiments/${EDIR}

# directory for grid and extpar files
 GRIDDIR=/e/rhome/routfox/routfox/icon/grids/public/edzw/
 EXTPDIR=/e/rhome/routfox/routfox/icon/grids/public/edzw/

# root directory for input data
DATAROOT=/lustre2/rwork0/routfor/test/icon/Checksuite_data/

# absolute path to input directory
INDIR=${DATAROOT}/Inidata_Routine

# absolute path to model binary, including the executable
 MODEL=$ICONDIR/build/x86_64-unknown-linux-gnu/bin/icon

# ----------------------------------------------------------------------
# copy input data: grids, external parameters
# ----------------------------------------------------------------------

# the directory for the experiment will be created, if not already there
if [ ! -d $EXPDIR ]; then
    mkdir -p $EXPDIR
fi
cd $EXPDIR

ln -sf $GRIDDIR/icon_grid_0025_R03B06_R.nc iconR3B06_DOM00.nc
ln -sf $GRIDDIR/icon_grid_0025_R03B06_R-grfinfo.nc iconR3B06_DOM00-grfinfo.nc
ln -sf $GRIDDIR/icon_grid_0026_R03B07_G.nc iconR3B07_DOM01.nc
ln -sf $GRIDDIR/icon_grid_0026_R03B07_G-grfinfo.nc iconR3B07_DOM01-grfinfo.nc
ln -sf $GRIDDIR/icon_grid_0027_R03B08_N02.nc iconR3B08_DOM02.nc
ln -sf $GRIDDIR/icon_grid_0027_R03B08_N02-grfinfo.nc iconR3B08_DOM02-grfinfo.nc


ln -sf $EXTPDIR/icon_extpar_0026_R03B07_G_20161124_tiles.nc extpar_iconR3B07_DOM01.nc
ln -sf $EXTPDIR/icon_extpar_0027_R03B08_N02_20161124_tiles.nc extpar_iconR3B08_DOM02.nc

 ln -sf  $INDIR/igaf20170703000000R.grb  an_R03B07_DOM01.grb
 ln -sf  $INDIR/ieaf20170703000000R.grb  an_R03B08_DOM02.grb
 ln -sf $INDIR/igfff2017070221-0130R.grb fg_R03B07_DOM01.grb
 ln -sf $INDIR/iefff2017070221-0130R.grb fg_R03B08_DOM02.grb

# files needed for radiation
cp $ICONDIR/data/ECHAM6_CldOptProps.nc rrtm_cldopt.nc
cp $ICONDIR/data/rrtmg_lw.nc .


ln -sf /e/uhome/gzaengl/constdir/rtcoef_msg_2_seviri.dat .
ln -sf /e/uhome/gzaengl/constdir/sccldcoef_msg_2_seviri.dat .


# ----------------------------------------------------------------------
# global namelist settings
# ----------------------------------------------------------------------

# the namelist filename
atmo_namelist=NAMELIST_${EXP}

# global timing
start_date="2017-07-03T00:00:00Z"
ndays_restart=60
dt_restart=$((${ndays_restart}*86400))

# model timing
dtime=120


# the grid parameters
atmo_dyn_grids="iconR3B07_DOM01.nc iconR3B08_DOM02.nc"
atmo_rad_grids="iconR3B06_DOM00.nc"


 cp -p $MODEL icon
 module load craype-hugepages2M

# ----------------------------------------------------------------------------
# ============================================================================
#                        LOOP: MODEL IS EXECUTED TWO TIMES
# ============================================================================
for iter in 1 2 ; do


if [ $iter -eq 1 ] ; then

restart="       .FALSE. "
nsteps="          1080  "
checkpoint="     86400. "

else

restart="        .TRUE. "
nsteps="           360  "
checkpoint="    864000. "

fi

# ----------------------------------------------------------------------
# create ICON master namelist
# ----------------------------------------------------------------------

# For a complete list see Namelist_overview and Namelist_overview.pdf

cat > icon_master.namelist << EOF
&master_nml
 lrestart               = ${restart}
/
&time_nml
 ini_datetime_string = "$start_date"
 dt_restart          = $dt_restart
/
&master_model_nml
  model_type=1
  model_name="ATMO"
  model_namelist_filename="$atmo_namelist"
  model_min_rank=1
  model_max_rank=65536
  model_inc_rank=1
/
EOF


# ----------------------------------------------------------------------
# model namelists
# ----------------------------------------------------------------------

# reconstrcuct the grid parameters in namelist form
dynamics_grid_filename=""
for gridfile in ${atmo_dyn_grids}; do
  dynamics_grid_filename="${dynamics_grid_filename} '${gridfile}',"
done
radiation_grid_filename=""
for gridfile in ${atmo_rad_grids}; do
  radiation_grid_filename="${radiation_grid_filename} '${gridfile}',"
done

plevels="5000,10000,15000,20000,25000,30000,40000,50000,70000,85000"


cat > ${atmo_namelist} << EOF
&parallel_nml
 nproma          = 8
 p_test_run      = .false.
 l_test_openmp   = .true.
 l_log_checks    = .true.
 num_io_procs    = 13
 num_restart_procs = 0 ! 2
 itype_comm      = 1
 iorder_sendrecv = 3
/
&grid_nml
 dynamics_grid_filename  = 'iconR3B07_DOM01.nc','iconR3B08_DOM02.nc'
 radiation_grid_filename = 'iconR3B06_DOM00.nc'
 dynamics_parent_grid_id = 0,1
 lredgrid_phys           = .true.,.true.,       ! ,.true. (second value: nest)
 lfeedback               = .true.
 ifeedback_type          = 2
 start_time              = 0., -5400 ! ** Achtung: muss "0.,-5400." heissen, wenn Input am genesteten Gebiet gelesen werden soll **
 end_time                = 0., 432000.    ! ** bewirkt, dass das Nest nur bis vv=120h laueft **
/
&synsat_nml
 lsynsat = .false.,.true.  ! output only within nest1
/ 
&initicon_nml
  init_mode             = 5
  lread_ana             = .true.
  dt_iau                = 10800
  dt_shift              = -5400
  iterate_iau           = .true.
  zpbl1                 = 500. 
  zpbl2                 = 1000. 
 dwdfg_filename         = "<path>fg_R<nroot0>B<jlev>_DOM<idom>.grb"
 dwdana_filename        = "<path>an_R<nroot0>B<jlev>_DOM<idom>.grb"
  ana_varnames_map_file = 'map_file.ana'
  check_ana(1)%list     = 'T_SO','FR_ICE','W_SO','P','QV','T','U','V','FRESHSNW','H_SNOW'
  check_ana(2)%list     = 'T_SO','FR_ICE','W_SO','FRESHSNW','H_SNOW'
  ltile_coldstart       = .false.
  lp2cintp_incr         = .true.
  lp2cintp_sfcana       = .false.
  use_lakeiceana        = .true.
/
&io_nml
 itype_pres_msl  = 5              ! new DWD method: Mixture between IFS and old GME method
 itype_rh        = 1              ! RH w.r.t. water
 output_nml_dict = 'map_file.fc'
 dt_checkpoint   = ${checkpoint}
! restart_write_mode = 'dedicated procs multifile'
 restart_write_mode = 'joint procs multifile'
/
&run_nml
 num_lev        = 90,60
 nsteps         = ${nsteps}
 lvert_nest     = .true.
 dtime          = 120              ! timestep in seconds
 ldynamics      = .true.               ! dynamics
 ltransport     = .true.
 iforcing       = 3                    ! NWP forcing
 lart           = .false.              ! ICON-ART main switch
 ltestcase      = .false.              ! false: run with real data
 msg_level      = 7          ! 7: print maximum wind speeds every 5th time steps
 ltimer         = .true.
 timers_level   = 10                   ! can be increased up to 10 for detailed timer output
 output         = "nml"
/
&nwp_phy_nml
 inwp_gscp         = 1
 inwp_convection   = 1
 inwp_radiation    = 1
 inwp_cldcover     = 1
 inwp_turb         = 1
 inwp_satad        = 1
 inwp_sso          = 1
 inwp_gwd          = 1
 inwp_surface      = 1
 icapdcycl         = 3
 latm_above_top    = .false.,.true. ! ,.true. (nest) - necessary for nest
 efdt_min_raylfric = 7200.
 itype_z0          = 2
 icpl_aero_conv    = 1
 icpl_aero_gscp    = 1
 lrtm_filename     = 'rrtmg_lw.nc'
 cldopt_filename   = 'rrtm_cldopt.nc'
 dt_rad  = 1440
 dt_conv = 360,180
 dt_sso  = 720
 dt_gwd  = 720
 ldetrain_conv_prec = .false.,.true.   ! .false.,.true.  for r3b07
/
&turbdiff_nml
  tkhmin        = 0.75
  tkmmin        = 0.75
  pat_len       = 750.
  c_diff        = 0.2
  rat_sea       = 7.0
  ltkesso       = .true.
  frcsmot       = 0.2   ! these 2 switches together apply vertical smoothing of the TKE source terms
  imode_frcsmot = 2     ! in the tropics (only), which reduces the moist bias in the tropical lower troposphere
 ! use horizontal shear production terms with 1/SQRT(Ri) scaling to prevent unwanted side effects:
  itype_sher    = 3    
  ltkeshs       = .true.
  a_hshr        = 2.0
  alpha0        = 0.0123
  alpha0_max    = 0.0335
  icldm_turb    = 1
/
&lnd_nml
  ntiles         = 3
  nlev_snow      = 3
  lmulti_snow    = .false. ! .true. (tests)
  itype_heatcond = 3
  idiag_snowfrac = 20
  lsnowtile      = .true.
  lseaice        = .true.
  llake          = .true.
  lprog_albsi    = .true.
  itype_lndtbl   = 4 
  itype_root     = 2
  itype_evsl     = 4
  cwimax_ml      = 5.e-4
  c_soil         = 1.25
  c_soil_urb     = 0.5
  sstice_mode = 2
/
&radiation_nml
  irad_o3     = 79
  irad_aero   = 6
  albedo_type = 2          ! Modis albedo
  vmr_co2     = 390.e-06   ! values representative for 2012
  vmr_ch4     = 1800.e-09
  vmr_n2o     = 322.0e-09
  vmr_o2      = 0.20946
  vmr_cfc11   = 240.e-12
  vmr_cfc12   = 532.e-12 
/
&nonhydrostatic_nml
  iadv_rhotheta   = 2
  ivctype         = 2
  itime_scheme    = 4
  exner_expol     = 0.333
  vwind_offctr    = 0.2
  damp_height     = 44000.
  rayleigh_coeff  = 1
  lhdiff_rcf      = .true.
  divdamp_order   = 24 ! 2 ass, 24 fc
  divdamp_type    = 32  ! optional: 2 assimilation cycle, 32 forecast
  divdamp_fac     = 0.004   ! 0.004 for R2B6; recommendation for R3B7: 0.003
  divdamp_trans_start= 12500
  divdamp_trans_end  = 17500
  l_open_ubc      = .false.
  igradp_method   = 3
  l_zdiffu_t      = .true.
  thslp_zdiffu    = 0.02
  thhgtd_zdiffu   = 125.
  htop_moist_proc = 22500.
  hbot_qvsubstep  = 16000.
/
&sleve_nml
 min_lay_thckn   = 20.
 max_lay_thckn   = 400.   ! maximum layer thickness below htop_thcknlimit
 htop_thcknlimit = 14000. ! this implies that the upcoming COSMO-EU nest will have 60 levels
 top_height      = 75000.
 stretch_fac     = 0.9
 decay_scale_1   = 4000.
 decay_scale_2   = 2500.
 decay_exp       = 1.2
 flat_height     = 16000.
/
&dynamics_nml
 iequations     = 3
 idiv_method    = 1
 divavg_cntrwgt = 0.50
 lcoriolis      = .true.
/
&transport_nml
 ctracer_list = '12345'
 ivadv_tracer = 3,3,3,3,3
 itype_hlimit = 3,4,4,4,4
 ihadv_tracer = 52,2,2,2,2
/
&diffusion_nml
 hdiff_order      = 5
 itype_vn_diffu   = 1
 itype_t_diffu    = 2
 hdiff_efdt_ratio = 24.     ! 24.0  for R2B6; recommendation for R3B7: 30.0
 hdiff_smag_fac   = 0.025   ! 0.025 for R2B6; recommendation for R3B7: 0.02
 lhdiff_vn        = .true.
 lhdiff_temp      = .true.
/
&interpol_nml
  nudge_zone_width     = 8
  lsq_high_ord         = 3
  l_intp_c2l           = .true.
  l_mono_c2l           = .true.
  support_baryctr_intp = .true.
/
&gridref_nml
 grf_intmethod_e  = 6
 grf_intmethod_ct = 2
 grf_tracfbk      = 2
 denom_diffu_v    = 150.
/
&extpar_nml
 itopo                = 1
 n_iter_smooth_topo   = 1,1
 heightdiff_threshold = 3000.
 hgtdiff_max_smooth_topo = 750.,750.,
/
&nwp_tuning_nml
 itune_albedo   = 1
!tune_zceff_min = 0.075   ! use default 0.075
 tune_gkwake    = 1.8
 tune_gfrcrit   = 0.4
 tune_dust_abs  = 1.
/
&ensemble_pert_nml
 use_ensemble_pert = .true.
/
&gribout_nml
 preset                          = "deterministic"
 ldate_grib_act                  = .true.
 lgribout_24bit                  = .false.
 backgroundProcess               = 0
 localNumberOfExperiment         = 10446
 productionStatusOfProcessedData = 2
 localTypeOfEnsembleForecast     = -1     ! -1, etyp
 numberOfForecastsInEnsemble     = -1     ! -1, nr_member
 perturbationNumber              = -1              ! -1, member
 generatingProcessIdentifier     = 1, 2                              ! 2 .. nest
 tablesVersion                   = 11
/
&output_nml
 ! ------------------------------------------------------------ !
 ! ---  IGLO: constant output fields - native grid at VV=0  --- !
 ! ------------------------------------------------------------ !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1                         ! write global domains
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0., 0., 3600.             ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .false.
 output_filename      = 'igfff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss>c'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 0
 ml_varlist           = '-grid:VLAT', '-grid:VLON', 'DEPTH_LK', 'FR_LAKE', 
                        'FR_LAND', 'HHL', 'HSURF', 'LAI', 'NDVIRATIO', 'PLCOV', 
                        'ROOTDP', 'SOILTYP', 
 output_grid          = .true.
/
&output_nml
 ! ------------------------------------------------------------- !
 ! ---  IGLO: constant output fields - regular grid at VV=0  --- !
 ! ------------------------------------------------------------- !
 filetype             = 2        ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1
 remap                = 1                        ! reg. lat-lon
 output_time_unit     = 1                        ! 1: seconds
 output_bounds        = 0., 0., 3600.            ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .false.
 output_filename      = 'igfrf'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss>c'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 1
 ml_varlist           = 'DEPTH_LK', 'FR_LAKE', 'FR_LAND', 'HHL', 'HSURF', 
                        'LAI', 'PLCOV', 'ROOTDP', 'SOILTYP', 
 reg_lon_def          = 0.,0.25,359.755
 reg_lat_def          = -90.,0.25,90.
 output_grid          = .true.
/
&output_nml
 ! ------------------------------------------------------- !
 ! ---  IGLO: fields used by interpolation IGLO -> LM  --- !
 ! ---        (part 1 of output namelist)              --- !
 ! ------------------------------------------------------- !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1                         ! write global domains
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0.,86400,3600., 97200.,108000.,10800., 129600., 10000000.,21600.           ! start, end, increment [s]
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'igfff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 3
 pe_placement_ml      = 2,3,1
 ml_varlist           = 'FRESHSNW', 'H_ICE', 'P', 'QC', 'QI', 'QR', 'QS', 
                        'QV', 'QV_S', 'RHO_SNOW', 'T', 'T_G', 'T_ICE', 'T_SNOW', 
                        'T_SO', 'U', 'V', 'W', 'W_I', 'W_SNOW', 'W_SO', 
 output_grid          = .false.
/
&output_nml
 ! ------------------------------------------------------------------------ !
 ! ---  IGLO: output fields used by other programs/users - native grid  --- !
 ! ---        (forecast run, part 2 of output namelist)                 --- !
 ! ------------------------------------------------------------------------ !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1                         ! write global domains
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0.,86400,3600., 97200.,108000.,10800., 129600., 10000000.,21600.           ! start, end, increment [s]
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'igfff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>oth'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 2
 pe_placement_ml      = 4,5
 stream_partitions_pl = 1
 pe_placement_pl      = 10
 ml_varlist           = 'ALB_RAD', 'ALHFL_S', 'ASHFL_S', 'ASOB_S', 'ASOB_T', 
                        'ASWDIFD_S', 'ASWDIFU_S', 'ASWDIR_S', 'ATHB_S', 'ATHB_T', 
                        'AUMFL_S', 'AVMFL_S', 'CAPE_CON', 'CLC', 'CLCH', 
                        'CLCL', 'CLCM', 'CLCT', 'CLCT_MOD', 'C_T_LK', 'DEN', 
                        'FR_ICE', 'HBAS_CON', 'HTOP_CON', 'HTOP_DC', 'HZEROCL', 
                        'H_ML_LK', 'H_SNOW', 'PMSL', 'PS', 'RAIN_CON', 'RAIN_GSP', 
                        'RUNOFF_G', 'RUNOFF_S', 'SNOW_CON', 'SNOW_GSP', 'TCH', 
                        'TCM', 'TD_2M',        'TMAX_2M', 'TMIN_2M', 'TOT_PREC', 
                        'TQC', 'TQC_DIA', 'TQI', 'TQI_DIA', 'TQR', 'TQS', 
                        'TQV', 'T_2M', 'T_BOT_LK', 'T_MNW_LK', 'T_S', 'T_WML_LK', 
                        'U_10M', 'V_10M', 'WW', 'W_SO_ICE', 'Z0', 
 m_levels             = '25...(nlev+1)',
 pl_varlist           = 'U',         'V',         'T',         'FI',        'RELHUM',
 p_levels             = 30000, 50000, 70000, 85000, 95000, 100000
 output_grid          = .false.
/
&output_nml
 ! ------------------------------------------------------------------------ !
 ! ---  IGLO: output fields used by other programs/users - native grid  --- !
 ! ---        (forecast run, part 2 of output namelist)                 --- !
 ! ------------------------------------------------------------------------ !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1                         ! write global domains
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0.,172800.,3600.          ! start, end, increment [s]
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'igfff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>tke'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 12
 ml_varlist           = 'DTKE_CON', 'TKE', 'DTKE_HSH'
 m_levels             = '44...(nlev+1)',
 output_grid          = .false.
/
&output_nml
 ! -------------------------------------------------------------- !
 ! ---  IGLO: original grid hourly until the end of forecast  --- !
 ! ---        + max. wind at 10m                              --- !
 ! -------------------------------------------------------------- !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1                         ! write global domains
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 3600., 648000., 3600.      ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'igfff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss>uv'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 0
 ml_varlist           = 'VMAX_10M',
 output_grid          = .false.
/
&output_nml
 ! -------------------------------------------- !
 ! ---  IGLO: output fields - regular grid  --- !
 ! -------------------------------------------- !
 filetype             = 2        ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1
 remap                = 1                        ! reg. lat-lon
 output_time_unit     = 1                        ! 1: seconds
!output_bounds        = 0., 648000., 3600.     ! start, end, increment
 output_bounds        = 0.,86400,3600., 97200.,108000.,10800., 129600., 10000000.,21600.          ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'igfrf'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 3
 pe_placement_ml      = 6,7,8
 stream_partitions_pl = 1
 pe_placement_pl      = 9
!stream_partitions_hl = 1
!pe_placement_hl      = 9
 ml_varlist           = 'ALB_RAD', 'ALHFL_S', 'APAB_S', 'ASHFL_S', 'ASOB_S', 
                        'ASOB_T', 'ASWDIFD_S', 'ASWDIFU_S', 'ASWDIR_S', 'ATHB_S', 
                        'ATHB_T', 'AUMFL_S', 'AVMFL_S', 'CAPE_ML', 'CIN_ML', 
                        'CLC', 'CLCH', 'CLCL', 'CLCM', 'CLCT', 'CLCT_MOD', 
                        'CLDEPTH', 'FR_ICE', 'HBAS_CON', 'HTOP_CON', 'HTOP_DC', 
                        'HZEROCL', 'H_ICE', 'H_SNOW', 'P', 'PMSL', 'PS', 
                        'QC', 'QI', 'QV', 'QV_2M', 'QV_S', 'RAIN_CON', 'RAIN_GSP', 
                        'RELHUM_2M', 'RHO_SNOW', 'RUNOFF_G', 'RUNOFF_S', 
                        'SNOW_CON', 'SNOW_GSP', 'SOBS_RAD', 'T', 'TCH', 'TCM', 
                        'TD_2M', 'THBS_RAD', 'TKE', 'TMAX_2M', 'TMIN_2M', 
                        'TOT_PREC', 'TQC', 'TQC_DIA', 'TQI', 'TQI_DIA', 'TQR', 
                        'TQS', 'TQV', 'T_2M', 'T_G', 'T_ICE', 'T_SNOW', 'T_SO', 
                        'U', 'V', 'W', 'WW', 'W_SNOW', 'W_SO', 'W_SO_ICE', 
                        'Z0', 
 m_levels             = '25...(nlev+1)',
 pl_varlist           = 'FI', 'T', 'U', 'V', 'RELHUM', 'OMEGA', 'CLC'
 p_levels             =   500,  1000,  3000,  5000,  7000, 10000, 12500, 15000,
                        17500, 20000, 22500, 25000, 27500, 30000, 35000, 40000,
                        45000, 50000, 55000, 60000, 65000, 70000, 75000, 77500,
                        80000, 82500, 85000, 87500, 90000, 92500, 95000, 97500,
                        100000
!hl_varlist           = 'P',         'T',         'U',         'V',         'W',
!h_levels             = 10000, 5000, 3000, 2000, 1500, 1000, 500, 100
 reg_lon_def          = 0.,0.25,359.755
 reg_lat_def          = -90.,0.25,90.
 output_grid          = .false.
/
&output_nml
 ! -------------------------------------------- !
 ! ---  IGLO: output fields - regular grid  --- !
 ! -------------------------------------------- !
 filetype             = 2        ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1
 remap                = 1                        ! reg. lat-lon
 output_time_unit     = 1                        ! 1: seconds
!output_bounds        = 0., 648000., 3600.     ! start, end, increment
 output_bounds        = 0.,86400,3600., 97200.,108000.,10800., 129600., 10000000.,21600.          ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'igfrf'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>strato'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_pl = 1
 pe_placement_pl      = 9
 pl_varlist           = 'FI', 'T', 'U', 'V'
 p_levels             =    10,   100,   200,
 reg_lon_def          = 0.,0.25,359.755
 reg_lat_def          = -90.,0.25,90.
 output_grid          = .false.
/
&output_nml
 ! ------------------------------------------------------------- !
 ! ---  IGLO: regular grid hourly until the end of forecast  --- !
 ! ---        + fields used by WAVE model (wind 10m)         --- !
 ! ---        + max. wind at 10m                             --- !
 ! ------------------------------------------------------------- !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1
 remap                = 1                         ! reg. lat-lon
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0., 648000., 3600.      ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'igfrf'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss>uv'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 0
 ml_varlist           = 'U_10M', 'VMAX_10M', 'V_10M', 
 reg_lon_def          = 0.,0.25,359.755
 reg_lat_def          = -90.,0.25,90.
 output_grid          = .false.
/
&output_nml
! ---------------------------------------------------------------- !
 ! ---  ICON-EU: constant output fields - native grid at VV=0  --- !
 ! --------------------------------------------------------------- !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 2                         ! write EU nest
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0., 0., 3600.             ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .false.
 output_filename      = 'iefff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss>c'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 0
 ml_varlist           = '-grid:VLAT', '-grid:VLON', 'DEPTH_LK', 'FR_LAKE', 
                        'FR_LAND', 'HHL', 'HSURF', 'LAI', 'PLCOV', 'ROOTDP', 
                        'SOILTYP', 
 output_grid          = .true.
/
&output_nml
 ! ------------------------------------------------------------------- !
 ! ---  ICON-EU: constant output fields - regular EU-grid at VV=0  --- !
 ! ------------------------------------------------------------------- !
 filetype             = 2        ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 2
 remap                = 1                        ! reg. lat-lon
 output_time_unit     = 1                        ! 1: seconds
 output_bounds        = 0., 0., 3600.            ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .false.
 output_filename      = 'iefrf'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss>c'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 1
 ml_varlist           = 'DEPTH_LK', 'FR_LAKE', 'FR_LAND', 'HHL', 'HSURF', 
                        'LAI', 'PLCOV', 'ROOTDP', 'SOILTYP', 
!pl_varlist           = 
 reg_lon_def          = -23.5,0.0625,62.5
 reg_lat_def          = 29.5,0.0625,70.5
 output_grid          = .true.
/
&output_nml
 ! -------------------------------------------------------------- !
 ! ---  ICON-EU: fields used by interpolation ICON-EU -> LMK  --- !
 ! ---           (part 1 of output namelist)                  --- !
 ! -------------------------------------------------------------- !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 2                         ! write EU nest
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0.,86400,3600., 97200.,108000.,10800., 129600., 10000000.,21600.           ! start, end, increment [s]
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'iefff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 11
 ml_varlist           = 'FRESHSNW', 'H_ICE', 'P', 'QC', 'QI', 'QR', 'QS', 
                        'QV', 'QV_S', 'RHO_SNOW', 'T', 'T_G', 'T_ICE', 'T_SNOW', 
                        'T_SO', 'U', 'V', 'W', 'W_I', 'W_SNOW', 'W_SO', 
 output_grid          = .false.
/
&output_nml
 ! --------------------------------------------------------------------------- !
 ! ---  ICON-EU: output fields used by other programs/users - native grid  --- !
 ! ---           (forecast run, part 2 of output namelist)                 --- !
 ! --------------------------------------------------------------------------- !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 2                         ! write EU nest
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0.,86400,3600., 97200.,108000.,10800., 129600., 10000000.,21600.           ! start, end, increment [s]
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'iefff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>oth'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 10
 ml_varlist           = 'ALHFL_S', 'ASHFL_S', 'ASOB_S', 'CLCH', 'CLCL', 'CLCM', 
                        'CLCT', 'C_T_LK', 'FR_ICE', 'H_ML_LK', 'PS', 'TCH', 
                        'TCM', 'TD_2M', 'TMAX_2M', 'TMIN_2M', 'TOT_PREC', 
                        'T_2M', 'T_BOT_LK', 'T_MNW_LK', 'T_WML_LK', 'U_10M', 
                        'VMAX_10M', 'V_10M', 'W_SO_ICE', 
!m_levels             = '1...(nlev+1)',
 output_grid          = .false.
/
&output_nml
 ! --------------------------------------------------------------------------- !
 ! ---  ICON-EU: output fields used by other programs/users - native grid  --- !
 ! ---           (forecast run, part 2 of output namelist)                 --- !
 ! --------------------------------------------------------------------------- !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 2                         ! write EU nest
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0.,172800.,3600.          ! start, end, increment [s]
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'iefff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>tke'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 10
 ml_varlist           = 'DTKE_CON', 'TKE', 'DTKE_HSH'
 m_levels             = '14...(nlev+1)',
 output_grid          = .false.
/
&output_nml
 ! ----------------------------------------------- !
 ! ---  ICON-EU: output fields - regular grid  --- !
 ! ----------------------------------------------- !
 filetype             = 2        ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 2
 remap                = 1                        ! reg. lat-lon
 output_time_unit     = 1                        ! 1: seconds
!output_bounds        = 0., 648000., 3600.     ! start, end, increment
 output_bounds        = 0.,86400,3600., 97200.,108000.,10800., 129600., 10000000.,21600.          ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'iefrf'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 3
 pe_placement_ml      = 6,7,8
 stream_partitions_pl = 1
 pe_placement_pl      = 9
!stream_partitions_hl = 1
!pe_placement_hl      = 9
 ml_varlist           = 'ALB_RAD', 'ALHFL_S', 'APAB_S', 'ASHFL_S', 'ASOB_S', 
                        'ASOB_T', 'ASWDIFD_S', 'ASWDIFU_S', 'ASWDIR_S', 'ATHB_S', 
                        'ATHB_T', 'AUMFL_S', 'AVMFL_S', 'CAPE_CON', 'CAPE_ML', 
                        'CIN_ML', 'CLC', 'CLCH', 'CLCL', 'CLCM', 'CLCT', 
                        'CLCT_MOD', 'CLDEPTH',             'HBAS_CON', 'HTOP_CON', 
                        'HTOP_DC', 'HZEROCL', 'H_ICE', 'H_SNOW', 'P', 'PMSL', 
                        'PS', 'QC', 'QI', 'QV', 'QV_2M', 'QV_S', 'RAIN_CON', 
                        'RAIN_GSP', 'RELHUM_2M', 'RHO_SNOW', 'RUNOFF_G', 
                        'RUNOFF_S', 'SNOWLMT', 'SNOW_CON', 'SNOW_GSP', 'SYNMSG_BT_CL_IR10.8', 
                        'SYNMSG_BT_CL_WV6.2', 'T', 'TCH', 'TCM', 'TD_2M', 
                        'TKE', 'TMAX_2M', 'TMIN_2M', 'TOT_PREC', 'TQC', 'TQI', 
                        'TQR', 'TQS', 'TQV', 'T_2M', 'T_G', 'T_ICE', 'T_SNOW', 
                        'T_SO', 'U', 'V', 'W', 'WW', 'W_SNOW', 'W_SO', 'W_SO_ICE', 
                        'Z0', 
!m_levels             = '1...(nlev+1)',
 pl_varlist           = 'U',         'V',         'OMEGA',         'T',         'FI',
                        'RELHUM',    'CLC'
 p_levels             =  5000,  7000, 10000, 12500, 15000,
                        17500, 20000, 22500, 25000, 27500, 30000, 35000, 40000,
                        45000, 50000, 55000, 60000, 65000, 70000, 75000, 77500,
                        80000, 82500, 85000, 87500, 90000, 92500, 95000, 97500,
                        100000
!hl_varlist           = 'U',         'V',         'W',         'T',         'P',
!h_levels             = 10000, 5000, 3000, 2000, 1500, 1000, 500, 100
 reg_lon_def          = -23.5,0.0625,62.5
 reg_lat_def          = 29.5,0.0625,70.5
 output_grid          = .false.
/
&output_nml
 ! ---------------------------------------------------------------- !
 ! ---  ICON-EU: regular grid hourly until the end of forecast  --- !
 ! ---           + fields used by WAVE model (wind 10m)         --- !
 ! ---           + max. wind at 10m                             --- !
 ! ---------------------------------------------------------------- !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 2
 remap                = 1                         ! reg. lat-lon
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 0., 648000., 3600.      ! start, end, increment
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'iefrf'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss>uv'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 0
 ml_varlist           = 'U_10M', 'VMAX_10M', 'V_10M', 
 reg_lon_def          = -23.5,0.0625,62.5
 reg_lat_def          = 29.5,0.0625,70.5
 output_grid          = .false.
/
&output_nml
 ! ------------------------------------------------------------------------ !
 ! ---  IGLO: output fields used by SMA                  - native grid  --- !
 ! ------------------------------------------------------------------------ !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 1                      ! write global domains
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 7200., 86400., 3600.,     ! start, end, increment [s]
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'igfff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>sma'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 5,
 ml_varlist           = 'ALHFL_BS', 'ALHFL_PL', 'RSTOM'
 output_grid          = .false.
/
&output_nml
 ! ------------------------------------------------------------------------ !
 ! ---  ICON-EU: output fields used by SMA                  - native grid  --- !
 ! ------------------------------------------------------------------------ !
 filetype             = 2         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                  = 2                      ! write global domains
 remap                = 0                         ! icon grid
 output_time_unit     = 1                         ! 1: seconds
 output_bounds        = 7200., 86400., 3600.,     ! start, end, increment [s]
 steps_per_file       = 1
 taxis_tunit          = 2
 mode                 = 1  ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last         = .true.
 output_filename      = 'iefff'                      ! file name base
 filename_format      = '<output_filename><ddhhmmss><levtype>sma'
! ready_file           = 'ready//IGLO_<ddhhmmss>'
 stream_partitions_ml = 1
 pe_placement_ml      = 5,
 ml_varlist           = 'ALHFL_BS', 'ALHFL_PL', 'RSTOM'
 output_grid          = .false.
/
&meteogram_output_nml
  lmeteogram_enabled = .true., .true.
  n0_mtgrm           = 0                          ! meteogram initial time step (0 is first step!)
  ninc_mtgrm         = 30, 30 ! meteogram output interval (in terms of time steps)
  ldistributed       = .false., .false.
  stationlist_tot    =  50.0,       8.6,    'Frankfurt-Flughafen',  ! Lat, Lon
                        52.2418,   14.2320, 'Lindenberg_IGLO',
                        52.2055,   14.0702, 'Lindenberg_IEU',
                        52.1817,   13.9525, 'Waldstation_Kehrigk',
                        52.1665,   14.1222, 'Falkenberg',
                        50.783,     6.100,  'Aachen',
                        49.980,    11.682,  'Bayreuth',
                        51.9703,    4.9261, 'Cabauw',
                        52.106,    -0.421,  'Cardington',
                        51.144,   358.563,  'Chilbolton-UK',
                        47.5614,   21.4508, 'Debrecen',
                        43.3853,    1.2922, 'Fauga_Mauzac',
                        53.633,     9.983,  'Hamburg-Fuhlsbuettel',
                        47.8019,   11.0119, 'Hohenpeissenberg',
                        61.843,    24.288,  'Hyytiala-FI',            ! Mobile ARM-Station. Discon 09.2015, Finns are measuring
                        50.90856,   6.4134, 'Juelich',
                        51.35,     12.43,   'Leipzig',
                        50.326,   350.096,  'Mace-Head-IR',
                        53.779,     8.669,  'Nordholz',
                        48.713,     2.208,  'Palaiseau-FR',
                        46.8137,    6.9425, 'Payerne',
                        40.6,      15.72,   'Potenza-IT',
                        52.383,    13.067,  'Potsdam',
                        44.6547,   11.6236, 'San_Pietro_Capofiume',
                        54.533,     9.550,  'Schleswig',
                        67.3617,   26.6375, 'Sodankyla',
                        57.966,    33.233,  'Valday',
                        48.400,    11.700,  'Weihenstephan',
                        53.311,    11.838,  'Ziegendorf',
                       -10.08,    -61.93,   'LBA_Rondonia',
                        13.50,      2.5 ,   'Niamey',
                        36.606,   262.515,  'ARMsouthernGreatPlains',
                        71.323,   203.39,   'ARMnorthSlopeAlaskaBarrow',
                        47.419,    10.982,  'Schneefernerhaus',            !
                        78.923,    11.921,  'Nyalesund_ac3',               ! until end of 2019, ask S. Crewell
                        39.0911,  331.9703, 'ARM-Azores',
                        -7.97,    345.6,    'ARM-Ascension-Island',        ! Mobile ARM-Station, until 31.10.2017
                        -2.146,  -59.006,   'ATTO_Amazon',                 ! 300m measurment tower from MPI-Chem
                       -77.85,    166.67,   'ARM-McMurdo-Antarctica',      ! Mobile ARM-Station, until early 2017 
                        13.16,    -59.43,   'Barbados-cloud-observatory',  ! ask Daniel Klocke in August 2017 if it is still needed!
/
EOF

cat > map_file.ana << EOF2
# internal name     GRIB2 shortName
theta_v             THETA_V
rho                 DEN
vn                  VN
u                   U
v                   V
w                   W
tke                 TKE
temp                T
pres                P
qv                  QV
qc                  QC
qi                  QI
qr                  QR
qs                  QS
t_g                 T_G
qv_s                QV_S
fr_seaice           FR_ICE
t_ice               T_ICE
h_ice               H_ICE
t_snow              T_SNOW
freshsnow           FRESHSNW
snowfrac_lc         SNOWC
w_snow              W_SNOW
rho_snow            RHO_SNOW
h_snow              H_SNOW
w_i                 W_I
w_so                W_SO
w_so_ice            W_SO_ICE
t_so                T_SO
smi                 SMI
gz0                 Z0
pres_sfc            PS
z_ifc               HHL

t_mnw_lk            T_MNW_LK
t_wml_lk            T_WML_LK
h_ml_lk             H_ML_LK
t_bot_lk            T_BOT_LK
c_t_lk              C_T_LK
t_b1_lk             T_B1_LK
h_b1_lk             H_B1_LK
EOF2

cat > map_file.fc << EOF3
# Dictionary for mapping between internal names and GRIB2 shortNames
# needed by GRIB2 write procedures.
#
# GRIB2 shortName   internal name
  den               RHO
  dtke_con          DDT_TKE_PCONV
  fi                GEOPOT
  hhl               Z_IFC
  p                 PRES
# qc                QC
# qi                QI
# qr                QR
# qs                QS
# qv                QV
  relhum            RH
  t                 TEMP
# tke               TKE
# u                 U
# v                 V
# vn                VN
# w                 W

  alb_rad           ALBDIF 
  alb_seaice        ALB_SI
  apab_s            ASWFLX_PAR_SFC 
  aswdifd_s         ASODIFD_S
  aswdifu_s         ASODIFU_S
  aswdir_s          ASODIRD_S
  cape_con          CAPE
  den               RHO
  dtke_con          DDT_TKE_PCONV
  dtke_hsh          DDT_TKE_HSH
  fi                GEOPOT
  fr_ice            FR_SEAICE
  freshsnw          FRESHSNOW
  hhl               Z_IFC
  hsurf             TOPOGRAPHY_C
  p                 PRES
  pmsl              PRES_MSL
  ps                PRES_SFC
  relhum            RH
  relhum_2m         RH_2M
  snowc             SNOWFRAC_LC
  sobs_rad          SOB_S
  t                 TEMP
  t_sea             T_SEASFC
  thbs_rad          THB_S
  vmax_10m          GUST10
  z0                GZ0
EOF3

# ----------------------------------------------------------------------
# run the model!
# ----------------------------------------------------------------------

aprun  -n 960 -N 12 -j 2 -d 6 -m 3g icon

# ----------------------------------------------------------------------------
done # iterations for restart testing
# ----------------------------------------------------------------------------
