#!/bin/sh
set -ex
#
ERAystrt=$1
#
ERAylast=$2
#
#
TYP=$3
#
atm_RES=$4
#
#
#
echo QUELLE path $QUELLE
echo PLTDIR path $PLTDIR
echo ERAinDir  path $ERAinDir
echo atm_RES gleich $atm_RES

ERAdata=${ERAinDir}/ERAin_${atm_RES}_atm_2d_1979-2008.nc
ERAdata=/pool/data/ICON/post/ERA-Interim_T63/ERAinT63_zon_1979_2008.nc
ERAdata47=/pool/data/ICON/post/ERA-Interim_T63/ERAinT63L47_zon_1979_2008.nc
case $TYP in
 ANN)shift
    echo ANN
    cdo timavg -selyear,${ERAystrt}/${ERAylast} $ERAdata \
       ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 DJF)shift
    echo DJF
    date
    cdo timavg -selmon,1,2,12 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,1,2,12 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    date;;
 MAM)shift
    echo MAM
    cdo timavg -selmon,3,4,5 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,3,4,5 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 JJA)shift
    echo JJA
    cdo timavg -selmon,6,7,8 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,6,7,8 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 SON)shift
    echo SON
    cdo timavg -selmon,9,10,11 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,9,10,11 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 JAN)shift
    echo JAN
    cdo timavg -selmon,1 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,1 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 FEB)shift
    echo FEB
    cdo timavg -selmon,2 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,2 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 MAR)shift
    echo MAR
    cdo timavg -selmon,3 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,3 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 APR)shift
    echo APR
    cdo timavg -selmon,4 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,4 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 MAY)shift
    echo MAY
    cdo timavg -selmon,5 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,5 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 JUN)shift
    echo JUN
    cdo timavg -selmon,6 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,6 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 JUL)shift
    echo JUL
    cdo timavg -selmon,7 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,7 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 AUG)shift
    echo AUG
    cdo timavg -selmon,8 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,8 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 SEP)shift
    echo SEP
    cdo timavg -selmon,9 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,9 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 OCT)shift
    echo OCT
    cdo timavg -selmon,10 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,10 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 NOV)shift
    echo NOV
    cdo timavg -selmon,11 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,11 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
 DEC)shift
    echo DEC
    cdo timavg -selmon,12 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata ERAin_T63_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc
    cdo timavg -selmon,12 -selyear,${ERAystrt}/${ERAylast} \
       $ERAdata47 ERAin_T63L47_atm_3d_zon_${ERAystrt}_${ERAylast}_${TYP}.nc;;
   *)echo you have chosen any season ;;
esac

exit
