#!/bin/sh
set -ex
#
TYP=$1
#
NAME=$2
#
EXP=$3
#
YY1=$4
#
YY2=$5
#
WORKDIR=$6
#
#

echo QUELLE path $QUELLE
echo PLTDIR path $PLTDIR


atm_phy=${WORKDIR}/atm_2d_${NAME}

case `hostname` in
  mlogin*|mistral*) CDO=/pf/m/m214003/local/bin/cdo ;;
  *)               CDO=/home/zmaw/m214003/local/thunder/bin/cdo  ;;
esac


${CDO} setpartabn,${QUELLE}/partab  $atm_phy busy_atm_phy.nc
 


nclsh ${QUELLE}/tab.ncl -pltdir=${PLTDIR} -quelle=${QUELLE}
which ncl
${CDO} -r remapycon,t63grid busy_atm_phy.nc busy_atm_phy_t63.nc


${CDO} -f grb2 delete,param='255*' busy_atm_phy_t63.nc busy_atm_phy_t63.grb


  if ${CDO} -s showparam -select,param='97*' busy_atm_phy_t63.grb  > /dev/null
  then
    :
  else
    echo '##### Attention #####'
    echo 'code 97 failt'
    echo 'please add code 97' 
    exit
  fi

  if ${CDO} -s showparam -select,param='172*' busy_atm_phy_t63.grb > /dev/null
  then
    cp busy_atm_phy_t63.grb busy_atm_phy_t63
  else
    ${CDO} -f grb2 copy   F_LAND F_LAND.grb 
    ${CDO} -O merge F_LAND.grb busy_atm_phy_t63.grb busy_atm_phy_t63
  fi


cat > namelist << eon
 &exper
 expnam='${EXP}' average='$TYP' year1=$YY1 year2=$YY2 iLONG=1 landcode=172
 /
eon

if  ${CDO} -s showcode -selcode,232  busy_atm_phy_t63 > /dev/null
then
  :
else
  ${CDO} -f grb2 copy  F_GLACIER  F_GLACIER.grb 
  ${CDO} -O merge F_GLACIER.grb busy_atm_phy_t63 busy_GLACIER.grb
  mv busy_GLACIER.grb busy_atm_phy_t63 
fi

#

${CDO} -f srv -sortparam busy_atm_phy_t63 busy_atm_phy_t63.srv

#


#gfortran  -o scripts/postprocessing/amip_quickplots/table_t63.x scripts/postprocessing/amip_quickplots/table_t63.f90
#module load intel/16.0
#ifort -o table_t63_mistral.x table_t63.f90

 case `hostname` in
    mlogin*|mistral*) ${QUELLE}/table_t63_mistral.x < namelist ;;
    *)               ${QUELLE}/table_t63.x < namelist  ;;
    esac

  mv codetext.txt table_${EXP}_fldmean_${TYP}

  mv tabelle table_${EXP}_zonmean_${TYP}
#

case `hostname` in
mlogin*|mistral*)
  enscript -fCourier10 -o table_${EXP}_fldmean_${TYP}.ps table_${EXP}_fldmean_${TYP}
  enscript  -fCourier7.1 -r -o table_${EXP}_zonmean_${TYP}.ps table_${EXP}_zonmean_${TYP};;
*)
  enscript -fCourier10 -o table_${EXP}_fldmean_${TYP}.ps table_${EXP}_fldmean_${TYP}
  enscript  -fCourier8 -r -o table_${EXP}_zonmean_${TYP}.ps table_${EXP}_zonmean_${TYP};;
esac
    

set +e
rm -f F_LAND.grb F_GLACIER.grb  mo_tables.mod mo_util_string.mod
rm -f busy_atm_phy*  namelist  psl.nc global.txt

exit
