#!/bin/sh
set -ex
#
TYP=$1
#
NAME=$2
#
EXP=$3
#
YY1=$4
#
YY2=$5
#
WORKDIR=$6
#
#

echo QUELLE path $QUELLE
echo PLTDIR path $PLTDIR


atm_phy=${WORKDIR}/atm_2d_${NAME}





cdo setpartabn,${QUELLE}/partab  $atm_phy busy_atm_phy.nc


nclsh ${QUELLE}/tab.ncl -pltdir=${PLTDIR} -quelle=${QUELLE}

cdo -r remapycon,t63grid busy_atm_phy.nc busy_atm_phy_t63.nc

cdo -f grb2 copy busy_atm_phy_t63.nc busy_atm_phy_t63.grb


  if cdo -s showcode -selcode,97   busy_atm_phy_t63.grb  > /dev/null
  then
    :
  else
    echo '##### Attention #####'
    echo 'code 97 failt'
    echo 'please add code 97' 
    exit
  fi

  code=172
  if cdo -s showcode -selcode,${code}  busy_atm_phy_t63.grb > /dev/null
  then
    cp busy_atm_phy_t63.grb busy_atm_phy_t63
  else
    cdo -f grb2 copy   F_LAND F_LAND.grb 
    cdo -O merge F_LAND.grb busy_atm_phy_t63.grb busy_atm_phy_t63
  fi


cat > namelist << eon
 &exper
 expnam='${EXP}' average='$TYP' year1=$YY1 year2=$YY2 iLONG=1 landcode=172
 /
eon

if cdo -s showcode -selcode,232  busy_atm_phy_t63 > /dev/null
then
  :
else
    cdo -f grb2 copy  F_GLACIER  F_GLACIER.grb 
  cdo -O merge F_GLACIER.grb busy_atm_phy_t63 busy_GLACIER.grb
  mv busy_GLACIER.grb busy_atm_phy_t63 
fi

#

cdo -f srv -sortcode busy_atm_phy_t63 busy_atm_phy_t63.srv
#
#xlf90 -o r2b4_amip/table_blizzard.x r2b4_amip/table_blizzard.f90
#gfortran  -o r2b4_amip_ncl6.2.0/table_thunder.x r2b4_amip_ncl6.2.0/table_thunder.f90
 case `hostname` in
    blizzard*) ${QUELLE}/table_blizzard.x < namelist ;;
    thunder*)  ${QUELLE}/table_thunder.x < namelist ;;
    *)         ${QUELLE}/table_linux.x < namelist  ;;
    esac

  mv codetext.txt table_${EXP}_fldmean_${TYP}


  mv tabelle table_${EXP}_zonmean_${TYP}
#

    enscript -fCourier10 -o table_${EXP}_fldmean_${TYP}.ps table_${EXP}_fldmean_${TYP}
    gv table_${EXP}_fldmean_${TYP}.ps &
    enscript  -fCourier8 -r -o table_${EXP}_zonmean_${TYP}.ps table_${EXP}_zonmean_${TYP}
    gv  table_${EXP}_zonmean_${TYP}.ps &


set +e
rm -f F_LAND F_GLACIER  mo_tables.mod mo_util_string.mod
rm -f busy_atm_phy*  namelist  psl.nc global.txt

exit
