#!/bin/ksh


inputfolder="src"
outputfolder="src.checkstyle"

callfolder=$(dirname $0)
here=$(pwd)
srciptfolder=$here/$callfolder

sedScript=$srciptfolder/"chk.sed"
echo "#sed script" > $sedScript
sedScript=

cd $srciptfolder
cd ../..
basefolder=$(pwd)

infolder=$basefolder/$inputfolder
outfolder=$basefolder/$outputfolder

rm -rf $outfolder

cd $infolder
folderList=$(ls -d *) 
#folderList="grid_generator"

for folder in $folderList
do 
  if [ $folder == "templates" ]; then
     break
  fi
  
  echo $folder
  readFolder=$infolder/$folder
  writeFolder=$outfolder/$folder
  
  mkdir -p $writeFolder
  cd $readFolder
  sourcelist=`ls -f *.f90`
  for filename in ${sourcelist}
  do
    $srciptfolder/check_style.py $1 $2 $3 $4 $sedScript $readFolder/$filename $writeFolder/$filename
    if [ $? -ne 0 ];  then
      echo "check_style.py returned an Error. File $filename is unchanged."
      cp  $readFolder/$filename $writeFolder/$filename
    fi
  done

done


echo "============================="
echo "$outfolder is created"
echo "============================="



