MODULE mo_cdi_constants

  IMPLICIT NONE

  PUBLIC

#ifdef HAVE_CDI
  INCLUDE 'cdi.inc'
#else
  ! just a small extract for testing without CDI - it'll be mandatory to 
  ! have CDI a little bit later ...

  INTEGER, PARAMETER :: GRID_UNSTRUCTURED      =  9
  INTEGER, PARAMETER :: GRID_REFERENCE         = 15
  
  INTEGER, PARAMETER :: ZAXIS_SURFACE          =  0
  INTEGER, PARAMETER :: ZAXIS_GENERIC          =  1
  INTEGER, PARAMETER :: ZAXIS_HYBRID           =  2
  INTEGER, PARAMETER :: ZAXIS_HYBRID_HALF      =  3
  INTEGER, PARAMETER :: ZAXIS_PRESSURE         =  4
  INTEGER, PARAMETER :: ZAXIS_HEIGHT           =  5
  INTEGER, PARAMETER :: ZAXIS_DEPTH_BELOW_SEA  =  6
  INTEGER, PARAMETER :: ZAXIS_DEPTH_BELOW_LAND =  7
  INTEGER, PARAMETER :: ZAXIS_ISENTROPIC       =  8
  INTEGER, PARAMETER :: ZAXIS_TRAJECTORY       =  9
  INTEGER, PARAMETER :: ZAXIS_ALTITUDE         = 10
  INTEGER, PARAMETER :: ZAXIS_SIGMA            = 11
  INTEGER, PARAMETER :: ZAXIS_MEANSEA          = 12
  
  INTEGER, PARAMETER :: CALENDAR_PROLEPTIC     =  1
  
  INTEGER, PARAMETER :: COMPRESS_SZIP          =  1
  
  INTEGER, PARAMETER :: FILETYPE_GRB2          =  2
  INTEGER, PARAMETER :: FILETYPE_NC2           =  4
  INTEGER, PARAMETER :: FILETYPE_NC4           =  5

#endif

  INTEGER, PARAMETER :: GRID_CELL   = 1
  INTEGER, PARAMETER :: GRID_VERTEX = 2
  INTEGER, PARAMETER :: GRID_EDGE   = 3

END MODULE mo_cdi_constants
