#!/bin/ksh
#-----------------------------------------------------------------------------
# CRAY@DWD
#
#PBS -q xc_norm_b
##PBS -o /lustre2/uwork/mkoehler/wq
##PBS -e /lustre2/uwork/mkoehler/wq
#PBS -j oe                       
#PBS -l select=1:ompthreads=4
#PBS -l place=scatter            
#PBS -l walltime=00:05:00
#PBS -N SCM_LANFEX
#PBS -m ae
#-----------------------------------------------------------------------------

set -x

export ATP_ENABLED=1
# ----------------------------------------------------------------------------
# specifiy experiment (idealized simulation)
# ----------------------------------------------------------------------------
EXPNAME=LANFEX

# ----------------------------------------------------------------------------
# path definitions
# ----------------------------------------------------------------------------

# base directory for ICON sources and binary:
ICONDIR="$PWD/.."
#ICONDIR="/e/uhome/mkoehler/icon/icon-nwp-test3"
#ICONDIR="${HOME}/icon-nwp-scm-new"

# SCM data directory (grids, init data, extpar)
SCMDATA=/hpc/uwork/mkoehler/scm/data       # at DWD on NEC

# directory with input grids:
GRIDDIR=${SCMDATA}/grid

# directory with init files:
INITDIR=${SCMDATA}/init_data

# absolute path to output directory for results:
EXPDIR=${SCMDATA}/${EXPNAME}

# path to model binary, including the executable:
#MODEL=${ICONDIR}/build/x86_64-unknown-linux-gnu/bin/icon
MODEL=${ICONDIR}/bin/icon


# ----------------------------------------------------------------------------
# copy input data: grids, external parameters, model
# ----------------------------------------------------------------------------

# the directory for the experiment will be created, if not already there
if [ ! -d $EXPDIR ]; then
    mkdir -p $EXPDIR
fi
cd ${EXPDIR}

# files needed for radiation
ln -sf ${ICONDIR}/data/ECHAM6_CldOptProps.nc .
ln -sf ${ICONDIR}/data/rrtmg_lw.nc .
# needed for 2 moment microphysics
ln -sf ${ICONDIR}/data/dmin_wetgrowth_lookup.dat .

# APE BCs
ln -sf ${ICONDIR}/data/external/ape_o3_R2B04_1Pa_spr0.90-cell.nc o3_icon_DOM01.nc

# link binary
ln -sf $MODEL icon


#-----------------------------------------------------------------------------
# model timing
#-----------------------------------------------------------------------------

# 0.4 s for 70 m res., 0.5 for 100 m; 30 s for 2.5 km?
dtime=60
ndyn_substeps=3
dt_checkpoint=`expr 36 \* 3600`  # write restart file every hours (when lrestart = TRUE)
nhours=19
#nhours=1
nsteps=`expr ${nhours} \* 3600 / ${dtime}`

start_date="2014-11-24T17:00:00Z"
end_date="2014-11-25T12:00:00Z"

#-----------------------------------------------------------------------------
# output
#-----------------------------------------------------------------------------
DT_DATA=`expr 1 \* 3600`      # output each n hours
DT_DATA=${dtime}              # output every time step
#n_in_ofile=60                # number of time steps per output file 
n_in_ofile=10000                # number of time steps per output file 

# ----------------------------------------------------------------------------
# grid namelist settings
# ----------------------------------------------------------------------------

# the grid parameters
atmo_dyn_grids="Torus_Triangles_4x4_2500m.nc"
atmo_rad_grids=""

# reconstruct the grid parameters in namelist form
dynamics_grid_filename=""
for gridfile in ${atmo_dyn_grids}; do
  dynamics_grid_filename="${dynamics_grid_filename} '${gridfile}',"
done
radiation_grid_filename=""
for gridfile in ${atmo_rad_grids}; do
  radiation_grid_filename="${radiation_grid_filename} '${gridfile}',"
done

ln -sf ${GRIDDIR}/${atmo_dyn_grids} .

#forcings
#ln -sf ${INITDIR}/init_SCM_GASS_DCP_GoAmazon.nc init_SCM.nc
#ln -sf ${INITDIR}/init_SCM_GASS_DCP_GoAmazon_IOP1.nc init_SCM.nc
#ln -sf /e/uhome/mkoehler/icon/icon-nwp-test3/SCM-ideal/py/init_SCM_GASS_DCP_GoAmazon.nc init_SCM.nc
ln -sf ${INITDIR}/init_SCM_LANFEX.nc init_SCM.nc

# ----------------------------------------------------------------------------
# create ICON master namelist
# ----------------------------------------------------------------------------

cat > icon_master.namelist << EOF

! master_nml: ----------------------------------------------------------------
&master_nml
 lrestart                    =                     .FALSE.        ! .TRUE.=current experiment is resumed
/

! master_model_nml: repeated for each model ----------------------------------
&master_model_nml
 model_type                  =                          1         ! identifies which component to run (atmosphere,ocean,...)
 model_name                  =                      "ATMO"        ! character string for naming this component.
 model_namelist_filename     =       "NAMELIST_${EXPNAME}"        ! file name containing the model namelists
 model_min_rank              =                          1         ! start MPI rank for this model
 model_max_rank              =                      65536         ! end MPI rank for this model
 model_inc_rank              =                          1         ! stride of MPI ranks
/

! time_nml: specification of date and time------------------------------------
&time_nml
 ini_datetime_string         =               "$start_date"        ! initial date and time of the simulation
 end_datetime_string         =                 "$end_date"        ! initial date and time of the simulation
/

EOF


# ----------------------------------------------------------------------------
# model namelists
# ----------------------------------------------------------------------------
# For a complete list see doc/Namelist_overview.pdf

cat > NAMELIST_${EXPNAME} << EOF

&parallel_nml
 nproma         =  8
 p_test_run     = .false.
 num_io_procs   =  3         ! number of I/O processors
 l_test_openmp  = .false.
 l_log_checks   = .false.
/

&grid_nml
 !cell_type = 3            ! triangular cells
 dynamics_grid_filename = "${atmo_dyn_grids}",
 corio_lat = 52.1         ! Cardington UK, 0.42W 52.1M
 is_plane_torus = .TRUE.
 l_scm_mode = .TRUE.       ! main logical to turn on SCM mode
/


&SCM_nml
 i_scm_netcdf = 1            ! read initial profiles and forcings from netcdf
 lscm_read_tke=.False.     ! read initial tke from netcdf
 lscm_read_z0=.TRUE.       ! read initial z0 from netcdf
 scm_sfc_mom=0 !0             ! 0=TERRA,1=turb_trans,2=prescribed u*, 0
                           ! 0 , combined with inwp_surface = 0 (TERRA off) 
			   ! to let turb_trans determine u* (do not overwrite flux)  
 scm_sfc_temp=1            ! 0=TERRA,1=turb_trans+t_g,prescribed sensible heat flux at surface
 scm_sfc_qv=3              ! 0=TERRA,1=turb_trans+q_vs,prescribed latent heat flux at surface,3=qv_s at saturation

/

&io_nml
 dt_checkpoint  = ${dt_checkpoint}
 lkeep_in_sync    = .true.
 lflux_avg = .FALSE. ! use accumulated rather than averages variables where possible
/

&run_nml
 num_lev        = 90           ! number of full levels of vertical grid
 dtime          = ${dtime}     ! timestep in seconds
 nsteps         = ${nsteps}
 ldynamics      = .FALSE.      ! compute adiabatic dynamic tendencies
 ltransport     = .FALSE.
 ntracer        = 5            ! default: 0
 iforcing       = 3            ! 3: NWP forcing; 6:inhecham forcing
 ltestcase      = .TRUE.       ! run testcase
 ltimer         = .FALSE.      ! 
 msg_level      = 10 !25           ! detailed report during integration
 output         = 'nml'
/

&nwp_phy_nml
 inwp_gscp       = 4 ! 
 inwp_convection = 0 ! 1:Tiedtke/Bechtold 0:apdf
 inwp_radiation  = 1 ! 1:RRTM radiation
 inwp_cldcover   = 1 ! 3: clouds from COSMO SGS cloud scheme 0:apdf
 inwp_turb       = 1 ! 1: TKE diffusion and transfer
 inwp_satad      = 1 !
 inwp_sso        = 0
 inwp_gwd        = 0
 inwp_surface    = 0 ! 0: none; 1: TERRA
 icapdcycl	 = 3            ! apply CAPE modification to improve diurnalcycle over tropical land (optimizes NWP scores)
 latm_above_top  = .TRUE.  ! needed for radiation routine
 itype_z0        = 2 ! 1: default, 2: turn off SSO part of z0
 dt_rad				= 1800.        ! Default: 1800   ! M. Koehler: 1440
 dt_conv			= 600.         ! Default: 600    ! M. Koehler: 360
 dt_sso				= 600.         ! Default: 1200   ! M. Koehler: 720
 dt_gwd				= 600.         ! Default: 1200   ! M. Koehler: 720
/

&radiation_nml
 ecRad_data_path = '${ICONDIR}/externals/ecrad/data'
  irad_co2 = 2 ! 2         ! constant from vmr_co2
  vmr_co2 = 0.00039145 != volume mixing ration to get mass mixing ratio of 5.941E-4 kg/kg
  irad_o3 = 11 ! 0: switch off ozone and initialize in test_case setup instead
  !irad_aero = 6 ! 6: Tegen aerosol climatology in radiation (not workin with testcase?
  !izenith = 6 ! same lat lon for all grid points in zenith angle calculation, rad_lat, rad_lon set in grid_nml
  albedo_type = 1 ! 2: MODIS albedo, together with inwp_surface = 0 
                  ! 1: albedo based on soil type, see mo_phyparam_soil
/

&ls_forcing_nml
 is_subsidence_moment = .FALSE.
 is_subsidence_heat   = .FALSE.
 is_advection         = .FALSE.
 is_advection_uv      = .FALSE.
 is_advection_tq      = .FALSE.
 is_geowind           = .FALSE.
 is_rad_forcing       = .FALSE.
 is_nudging           = .FALSE.
 is_nudging_uv        = .FALSE.
 is_nudging_tq        = .FALSE.
 is_theta             = .FALSE.
/

&turbdiff_nml
 tkhmin  = 0.75  ! new default since rev. 16527
 tkmmin  = 0.75  !           " 
 pat_len = 750.
 c_diff  = 0.2
 rat_sea = 8.5  ! ** new value since rev. 25646 (reduced saturation vapor pressure over salt water) **
 ltkesso = .true.
 frcsmot = 0.2      ! these 2 switches together apply vertical smoothing of the TKE source terms
 imode_frcsmot = 2  ! in the tropics (only), which reduces the moist bias in the tropical lower troposphere
 ! use horizontal shear production terms with 1/SQRT(Ri) scaling to prevent unwanted side effects:
 itype_sher = 3    
 ltkeshs    = .true.
 a_hshr     = 2.0
 lconst_z0 = .TRUE.
 const_z0  = 0.1
/

&diffusion_nml
 lhdiff_temp  = .TRUE.
 lhdiff_vn    = .TRUE.
 lhdiff_w     = .TRUE.
 hdiff_order  = 4
/

&nonhydrostatic_nml
 ivctype        = 2          ! sleve vertical coordinate
 damp_height    = 44000.     ! top_height-damp_height should be about 15km
 ndyn_substeps  = ${ndyn_substeps}
 l_open_ubc     = .false.   ! top open upper boundary condition. might help to go higher
 rayleigh_type   = 1 
 rayleigh_coeff = 1 !0.0
 htop_moist_proc= 22500.
 hbot_qvsubstep	= 22500.    ! Default: 22500  ! M. Koehler: 19000; at leas as large as htop_moist_proc
/

&sleve_nml
 min_lay_thckn			= 20.       ! Default: 50     ! M. Koehler: 20
 max_lay_thckn			= 400.      ! maximum layer thickness below htop_thcknlimit: 400 recommended for NWP
 htop_thcknlimit		= 14000.    ! this implies that the upcoming COSMO-EU nest will have 60 levels; Default: 15000 ! M. Koehler: 14000
 top_height			= 75000.
 stretch_fac			= 0.9       ! Default: 1      ! M. Koehler: 0.9
 decay_scale_1			= 4000.
 decay_scale_2			= 2500.
 decay_exp			= 1.2
 flat_height			= 16000.
/

&extpar_nml
 itopo          = 0 ! 0: analytical topo; 1: topography/ext. data read from file
/

&dynamics_nml
 iequations     = 3       ! equation system
 idiv_method    = 1
 divavg_cntrwgt = 0.50
 lcoriolis      = .TRUE.
/

!&output_nml
! mode             = 1 ! 1: nwp mode
! output_start     = "${start_date}"
! output_end       = "${end_date}"
! output_interval  =  "PT05M" !"PT05M"
! !output_interval  = "PT60S"
! !file_interval    = "P01H"
! steps_per_file   = ${n_in_ofile}
! include_last     = .TRUE.
! output_filename  = 'prog_vars'
! filename_format  = "<output_filename>_DOM<physdom>_<levtype>_<datetime2>"
! ml_varlist       = 'group:all', 'rh' , ! 'ddt_temp_gscp'#,'ddt_tke_therm'
!                    'z_ifc','z_mc','u','v','w','temp','pres','rho','theta_v','pres_sfc','div',
!                    'qv','qc','qi','qs','qr','rh',
!                    !'ashfl_s', 'alhfl_s', 'athb_s', 'athb_t', 'asob_s', 'asob_t', 
!                    'ddt_temp_radsw', 'ddt_temp_radlw', 'ddt_temp_turb', 'ddt_temp_drag', 'ddt_temp_pconv','ddt_temp_gscp',
!                    'ddt_qv_turb','ddt_qc_turb','ddt_qv_conv','ddt_qc_conv','u_10m', 'v_10m', 't_2m', 't_g',
!                    'qv_s','z_mc','lhfl_s','shfl_s','umfl_s','vmfl_s','tcm','tch','clc','tke','rcld','qhfl_s',
!                    'sob_s', 'thb_s','sob_t', 'lwflx_dn',
!	       !'tet_flux','vap_flux','liq_flux' 
!	       'tetfl_turb', 'vapfl_turb', 'liqfl_turb',
!	       !'ddt_tke_therm', 'ddt_tke_mech', 'ddt_tke_shear','ddt_tke_pconv','ddt_tke_hsh', ! ,'edr',
!               'qnc','qnr','qni','qns','qng','qnh','ninact', ! for 2mom scheme, cnnc when aerosol?
!	       !'t_g','qv_s','t_2m'
!
! output_grid      = .TRUE.
!/


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! output SCALAR fields as demanded by Ian Boutle every minute
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
&output_nml
 mode             = 1 ! 1: nwp mode
 output_start     = "${start_date}"
 output_end       = "${end_date}"
 output_interval  =  "PT01M" !"PT05M"
 steps_per_file   = ${n_in_ofile}
 output_filename  =  'scalars_${EXPNAME}_ICON_SCM_DWD'
 output_grid      =  .TRUE.
 include_last     =  .TRUE.
 ml_varlist = 'sou_s','accsodird_s','accsodifd_s','accsodifu_s','accsob_s','accthu_s','accthd_s','t_g','accshfl_s','acclhfl_s','clct','tqv','tqc_dia','tqc','tqr','rain_gsp_rate','rain_con_rate','pres_sfc','u_10m','v_10m','t_2m','qv_2m','rh_2m','rh_2m_land','tvm', 'qv_s','accthb_s', 'accthb_t', 'accsob_s', 'accsob_t','theta_v','clc','tot_qv_dia','tot_qc_dia','tot_qi_dia','qr','qs','temp','pres','u','v','rho','z_mc','qhfl_s','qcfl_s','umfl_s','vmfl_s' !,'cloud_gsp_rate'
/
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! output PROFILES as demanded by Ian Boutle every 15 min
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
&output_nml
 filetype         =  4
 dom              = -1
 output_start     = "${start_date}"
 output_end       = "${end_date}"
 output_interval  =  "PT15M" !"PT05M"
 steps_per_file   = ${n_in_ofile}
 include_last     =  .TRUE.
 remap            =  0   ! triangular grid
 output_filename  =  'profs_${EXPNAME}_ICON_SCM_DWD'
 output_grid      =  .TRUE.
 mode             =  1      ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
  ml_varlist = 'z_mc','z_ifc','pres','exner','theta_v','temp','rh','qv','qc','qr','qi','qs','rho','tot_qv_dia','tot_qi_dia',
              'tot_qc_dia',
	      !'vfl_q01','vfl_q02','vfl_q04',
	      'clc','u','v','tkvm','tkvh','tke','ddt_qv_turb','ddt_qc_turb','ddt_tke', 
	      !,'ddt_qv_gscp','ddt_qc_gscp','ddt_qr_gscp',
	      'ddt_temp_gscp','ddt_temp_radsw','ddt_temp_radlw','ddt_temp_turb','lwflxall','trsolall','pres_sfc','t_g', !'re_diag',
               'qnc','qnr','qni','qns','qng','qnh','ninact', ! for 2mom scheme, cnnc when aerosol?
               'tetfl_turb', 'vapfl_turb', 'liqfl_turb',
	       'lwflx_up','lwflx_dn','swflx_up','swflx_dn',
	       'lwflx_up_clr','lwflx_dn_clr','swflx_up_clr','swflx_dn_clr',
	       !'tet_flux','vap_flux','liq_flux','lwup','lwdn','swup','swdn' ,
	       !'ddt_tke_therm', 'ddt_tke_mech', 'ddt_tke_shear','ddt_tke_pconv','ddt_tke_hsh' ,'edr'
/
EOF


# ----------------------------------------------------------------------------
# run the model!
# ----------------------------------------------------------------------------

#./icon > out.txt 2>out2.txt

# select=4 : Number of nodes - see header (n/N)
# -n 48    : Number of MPI Tasks (N*select)
# -N 12    : Number of MPI Tasks/Node            (12: haswell, 18: broadwell)
# -d 4     : Number of threads Threads/MPI Task
# -j 2     : Hyperthreading enabled: 24 physical cores -> 48 "virtual" cores
# -m 3g    : 3GB memory, 64GB available shared on one node (m x N < 64)

aprun -n 18 -N 18 -j 2 -d 4 -m 3g ./icon
