#!/bin/bash

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

${ICON_DIR}/config/mpim/stretch.intel --disable-yaxt --disable-openmp --enable-rte-rrtmgp --enable-claw

if test 0 -ne "$?" && test ! -z "${BB_SLAVE}"; then
  echo " ***** Configuration logs from '$(pwd)' ***** "
  for f in $(find . -name 'config.log' -print); do
    echo " ||||| '$f' ||||| "
    cat "$f"
  done
  echo " ***** End of configuration logs from '$(pwd)' ***** "
fi

MAKE_PROCS=8
make -j ${MAKE_PROCS}
