#!/bin/bash

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

${ICON_DIR}/config/mpim/stretch.intel --disable-mpi --enable-openmp --enable-rte-rrtmgp

MAKE_PROCS=8
make -j ${MAKE_PROCS}
