#!/bin/bash

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

${ICON_DIR}/config/mpim/stretch.gcc --disable-yaxt --disable-openmp --enable-rte-rrtmgp --enable-art

MAKE_PROCS=8
make -j ${MAKE_PROCS}
