#!/bin/bash

set -eu

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

BUILD_ENV=". ${MY_DIR}/build_env_init.sh; switch_for_module modules;"
BUILD_ENV="${BUILD_ENV} module use /project/d56/modules; switch_for_module craype PrgEnv-cray cce-icon/9.0.2-classic cray-mpich cray-netcdf;"

XML2_ROOT='/apps/daint/UES/jenkins/6.0.UP07/gpu/easybuild/software/libxml2/2.9.7-CrayGNU-18.08'
XML2_LDFLAGS="-L${XML2_ROOT}/lib"
XML2_CPPFLAGS="-I${XML2_ROOT}/include/libxml2"
XML2_LIBS='-lxml2'

FC=ftn
CC=cc

FCFLAGS='-hadd_paren -r am -Ktrap=divz,ovf,inv -hflex_mp=intolerant -hfp1 -O1,cache0'
CFLAGS='-g -O3'
CPPFLAGS="${XML2_CPPFLAGS}"
LDFLAGS="${XML2_LDFLAGS}"
LIBS="${XML2_LIBS}"

MPI_LAUNCH='/apps/daint/UES/xalt/production/bin/srun -p debug -C gpu'

"${ICON_DIR}/configure" \
BUILD_ENV="$BUILD_ENV" \
CC="$CC" \
CFLAGS="$CFLAGS" \
CPPFLAGS="$CPPFLAGS" \
FC="$FC" \
FCFLAGS="$FCFLAGS" \
LDFLAGS="$LDFLAGS" \
LIBS="$LIBS" \
MPI_LAUNCH="$MPI_LAUNCH" \
"$@"

MAKE_PROCS=22
make -j ${MAKE_PROCS}

# Copy runscript-related files when building out-of-source:
if test $(pwd) != $(cd "${ICON_DIR}"; pwd); then
  rsync -uavz ${ICON_DIR}/run . --exclude='*in' --exclude='.*'
  rsync -uavz ${ICON_DIR}/externals . --exclude='.git' --exclude='*.f90' --exclude='*.F90' --exclude='*.c' --exclude='*.h' --exclude='*.Po' --exclude='tests' --exclude='rrtmgp*.nc' --exclude='*.mod' --exclude='*.o'
  rsync -uavz ${ICON_DIR}/make_runscripts .
  ln -sf ${ICON_DIR}/data
fi

# Generate input file for runscript generation:
./config.status --file=run/create_target_header --file=run/exec.iconrun --file=run/add_run_routines --file=run/set-up.info

