#!/bin/bash

set -e

# set required environment variables
export MODULESHOME="/usr/share/Modules"

# this wrapper needs to build two ICON binaries
MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

# create vector engine binary
#${ICON_DIR}/config/dwd/rcl.VE.nfort --enable-openmp --prefix=${PWD}/vector
${ICON_DIR}/config/dwd/rcl.VE.nfort-3.1.0_art_oper --prefix=${PWD}/vector
MAKE_PROCS=14
make -j ${MAKE_PROCS}
make install

make distclean

# create vector host binary
#${ICON_DIR}/config/dwd/rcl.VH.gcc --prefix=${PWD}/host
${ICON_DIR}/config/dwd/rcl.VH.gcc-9.1.0_art_oper --prefix=${PWD}/host
MAKE_PROCS=14
make -j ${MAKE_PROCS}
make install

VECTOR_BINARY="${PWD}/vector/bin/icon"
HOST_BINARY="${PWD}/host/bin/icon"

set +e
find "${PWD}/vector" "${PWD}/host"
file "$VECTOR_BINARY" "$HOST_BINARY"
