#!/bin/bash

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

${ICON_DIR}/config/dkrz/mistral.nag --disable-mpi --disable-parallel-netcdf --disable-openmp

MAKE_PROCS=8
make -j ${MAKE_PROCS}
