#!/bin/bash

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

${ICON_DIR}/config/dkrz/mistral.intel-17.0.6 --enable-yaxt --enable-openmp

MAKE_PROCS=22
make -j ${MAKE_PROCS}
