#!/bin/bash

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

${ICON_DIR}/config/dkrz/mistral.intel-17.0.6  --enable-openmp --enable-mixed-precision --enable-yaxt

MAKE_PROCS=8
make -j ${MAKE_PROCS}
