#!/bin/ksh

# usage get_atmo <icon-dev full path> <atmo only full path>
#   links from the <icon-dev full path> the atmosphere only files to <atmo only full path>
set -x
icon_dev_from=$1
icon_dev_to=$2

if [ ! -d ${icon_dev_to} ] ; then
  mkdir -p ${icon_dev_to}
fi
  
# cd ${icon_dev_to}


#-----------------------------------------------------------------------------------
link_source_list()
{
  source_folder=$1
  source_files_list="$2"

  if [ ${source_folder} != "" ] ; then
    if [ ! -d ${icon_dev_to}/${source_folder} ] ; then
      mkdir -p ${icon_dev_to}/${source_folder}
    fi
  fi
  
  if [ "${source_files_list}" == "all" ] ; then
    ln -s ${icon_dev_from}/${source_folder}*  ${icon_dev_to}/${source_folder}
  else 
    for source_file in ${source_files_list}
    do
      ln -s ${icon_dev_from}/${source_folder}${source_file}  ${icon_dev_to}/${source_folder}
    done
  fi
  
}

#-----------------------------------------------------------------------------------
#link folder
#-----------------------------------------------------------------------------------
#get src
link_source_list "src/" "advection 
art_interface 
atm_dyn_icoham 
atm_dyn_iconam 
atm_phy_echam 
atm_phy_edmf 
atm_phy_les 
atm_phy_nwp
atm_phy_psrad
atm_phy_schemes 
CMakeLists.txt 
configure_model 
coupler 
diagnostics 
include 
io 
lnd_phy_jsbach 
lnd_phy_nwp 
lnd_phy_schemes 
namelists 
parallel_infrastructure 
shared 
shr_horizontal 
templates 
testcases 
drivers"
#-----------------------------------------------------------------------------------
#get externals
link_source_list "externals/" "mtime self"
#-----------------------------------------------------------------------------------



link_source_list "" "data blas lapack doc scripts support aclocal.m4 configure.ac configure make_runscripts
Makefile.in support vertical_coord_tables"

link_source_list "config/" all
link_source_list "run/" all

cat > ${icon_dev_to}/config/multiple_builds << EOF
#==============================================
# This file defines multiple builds for ICON
#==============================================

#==============================================
# Define the run scripts in run/ to be common along the following builds
run_scripts=*

exit






      
