SRC   = ["icon_plot.ncl","icon_plot_lib.ncl"]
HOSTS = ["m300064@blizzard"]
DIR   = '/pool/data/ICON/tools'
DST   = HOSTS.map {|v| v + ':' + DIR}
CP    = 'scp -p'
LS    = 'ls -crtlh'

iconPlot = lambda {|ifile,ofile,otype,varname,opts|
  libdir = FileUtils.pwd
  cmd    = "ncl #{SRC[0]} 'altLibDir = \"#{libdir}\"' 'varName = \"#{varname}\"' 'iFile = \"#{ifile}\"' 'oFile = \"#{ofile}\"' 'oType = \"#{otype}\"'"
  puts cmd
  sh cmd
}

task :default => [:check]

task :install do
  SRC.each {|src| DST.each {|dst| sh [CP,src,dst].join(' ') }}
end

task :check do
  SRC.each {|src| HOSTS.each {|host| sh ['ssh',host,['"',LS,DIR,'"'].join(' ')].join(' ') }}
end

task :test_plot do
  plot_test_file = ENV['HOME']+'/data/icon/test.nc'
  ofmt           = 'png'
  ofile          = 'test_icon_plot.' + ofmt
  varname        = 'T'
  iconPlot.call(plot_test_file,ofile,ofmt,varname,[])
  system("qiv #{ofile}")
end
