#!/bin/bash 
#==============================================================================
# Creates the ICON run scripts
# Leonidas Linardakis, MPI-M, 2011-25-1
#==============================================================================
set -x
base_folder=$(pwd)
. $base_folder/config/set-up.info
input_folder=run
use_shell=${use_shell:="/bin/bash"}
make_runscript="$use_shell ./config/make_target_runscript"
#==============================================================================


#==============================================================================
create_runscript()
{
grid_name=$1

ocean_grids="${grid_name}.nc"
exp_out_name=${exp_name}_${grid_name}
out_script=exp.${exp_out_name}.run

$make_runscript                  \
  in_folder=$input_folder        \
  in_script=exp.${exp_name}      \
  in_script=exec.iconrun         \
  out_script=${out_script}       \
  EXPNAME=${exp_out_name}        \
  nproma=$nproma                 \
  no_of_nodes=$no_of_nodes       \
  mpi_procs_pernode=$mpi_procs_pernode  \
  openmp_threads=$openmp_threads \
  cpu_time=$cpu_time \
  grids_folder="${grids_folder}"   \
  ocean_grids="${ocean_grids}" \
  dtime=$dtime

  cd run
  ./$out_script
  cd -
}
#==============================================================================


#==============================================================================
echo "-----------------------------------------------------------"
no_of_nodes=1
mpi_procs_pernode=1
openmp_threads=1
cpu_time="04:00:00"
nproma=16

exp_name="ocean_exp1_GeostrophicBalance"
grids_folder=/scratch/local1/icon/icon-grid_generator.svn/grids

#------------------------

# cd $grids_folder
# gridList=`ls -d AquaPlanet_Icos_0316km_*.nc`
# cd -
# dtime=900
# for gridFile in $gridList ; do
#   create_runscript ${gridFile%.nc}
# done
# 
# cd $grids_folder
# gridList=`ls -d AquaPlanet_Icos_0158km_*.nc`
# cd -
# dtime=600
# for gridFile in $gridList ; do
#   create_runscript ${gridFile%.nc}
# done

cd $grids_folder
gridList=`ls -d AquaPlanet_Icos_0079km_*.nc`
cd -
dtime=360
for gridFile in $gridList ; do
  create_runscript ${gridFile%.nc}
done

cd $grids_folder
gridList=`ls -d AquaPlanet_Icos_0039km_*.nc`
cd -
dtime=240
for gridFile in $gridList ; do
  create_runscript ${gridFile%.nc}
done



echo "-----------------------------------------------------------"
#==============================================================================
