#!/bin/bash

NETCDFF_ROOT='/scratch/local1/icon-bootstrap/opt/nag-6.2/netcdf-fortran-4.4.4-2yfdh7a'
NETCDFF_LIBS='-lnetcdff'

# MTIME_ROOT='/scratch/local1/icon-bootstrap/opt/nag-6.2/libmtime-1.0.8-wdvzzyy'
# MTIME_LIBS='-lmtime'

# SELF_ROOT='/scratch/local1/icon-bootstrap/opt/nag-6.2/libself-0.2-njvphit'
# SELF_LIBS='-lself'

BLAS_ROOT='/scratch/local1/icon-bootstrap/opt/nag-6.2/netlib-lapack-3.8.0-jjggoll'
BLAS_LIBS='-lblas'

LAPACK_ROOT='/scratch/local1/icon-bootstrap/opt/nag-6.2/netlib-lapack-3.8.0-jjggoll'
LAPACK_LIBS='-llapack'

CDI_ROOT='/scratch/local1/icon-bootstrap/opt/nag-6.2/libcdi-1.8.2-gcmobcg'
CDI_LIBS='-lcdi_f2003 -lcdi'

YAC_ROOT='/scratch/local1/icon-bootstrap/opt/nag-6.2/yac-1.3.2-oroacd7'
XML_ROOT='/scratch/local1/icon-bootstrap/opt/nag-6.2/libxml2-2.9.8-nssbpjs'
YAC_LIBS='-lyac -lxml2 /scratch/local1/icon-bootstrap/opt/nag-6.2/yac-1.3.2-oroacd7/lib/libmtime.a'

SCT_ROOT='/scratch/local1/icon-bootstrap/opt/nag-6.2/libsct-develop-kbhiwpt'
SCT_LIBS='-lsct'

MPI_FC="/scratch/local1/icon-bootstrap/opt/nag-6.2/mpich-3.2.1-wr3cmft/bin/mpif90"

######################

CC=/sw/jessie-x64/gcc/gcc-6.2.0/bin/gcc
FC=$MPI_FC
#
# FCFLAGS="-mismatch -I${MTIME_ROOT}/include -I${SELF_ROOT}/include -I${NETCDFF_ROOT}/include -I${CDI_ROOT}/include -I${YAC_ROOT}/include -I${SCT_ROOT}/include"
# FCFLAGS="-mismatch -I${MTIME_ROOT}/include -I${NETCDFF_ROOT}/include -I${CDI_ROOT}/include -I${YAC_ROOT}/include -I${SCT_ROOT}/include"
FCFLAGS="-mismatch -I${NETCDFF_ROOT}/include -I${CDI_ROOT}/include -I${YAC_ROOT}/include -I${SCT_ROOT}/include"

# LDFLAGS="-L${MTIME_ROOT}/lib -L${SELF_ROOT}/lib -L${BLAS_ROOT}/lib -L${LAPACK_ROOT}/lib -L${NETCDFF_ROOT}/lib -L${CDI_ROOT}/lib -L${YAC_ROOT}/lib -L${XML_ROOT}/lib -L${SCT_ROOT}/lib"
# LDFLAGS="-L${MTIME_ROOT}/lib -L${BLAS_ROOT}/lib -L${LAPACK_ROOT}/lib -L${NETCDFF_ROOT}/lib -L${CDI_ROOT}/lib -L${YAC_ROOT}/lib -L${XML_ROOT}/lib -L${SCT_ROOT}/lib"
LDFLAGS="-L${BLAS_ROOT}/lib -L${LAPACK_ROOT}/lib -L${NETCDFF_ROOT}/lib -L${CDI_ROOT}/lib -L${YAC_ROOT}/lib -L${XML_ROOT}/lib -L${SCT_ROOT}/lib"

# LDFLAGS and LIBS provided to ICON configure script are meant for the
# Fortran compiler and might not be understood by the C compiler,
# like in this case: CC=gcc FC=nagfor LDFLAGS='-Wl,-Wl,,-rpath -Wl,-Wl,,/path'.
# The bundled libraries, e.g. mtime, might use the C compiler for linking
# (at least at the configure time), which means that we have to provide -rpath
# linking flags not as LDFLAGS but as CFLAGS and FCFLAGS:
FCFLAGS="$FCFLAGS $(echo ${LDFLAGS} | sed 's%-L\s*\(\S\+\)%-Wl,-Wl,,-rpath -Wl,-Wl,,\1%g')"
CFLAGS=$(echo ${LDFLAGS} | sed 's%-L\s*\(\S\+\)%-Wl,-rpath -Wl,\1%g')

# LIBS="${MTIME_LIBS} ${SELF_LIBS} ${BLAS_LIBS} ${LAPACK_LIBS} ${NETCDFF_LIBS} ${CDI_LIBS} ${YAC_LIBS} ${SCT_LIBS}"
# LIBS="${MTIME_LIBS} ${BLAS_LIBS} ${LAPACK_LIBS} ${NETCDFF_LIBS} ${CDI_LIBS} ${YAC_LIBS} ${SCT_LIBS}"
LIBS="${BLAS_LIBS} ${LAPACK_LIBS} ${NETCDFF_LIBS} ${CDI_LIBS} ${YAC_LIBS} ${SCT_LIBS}"

NAG_KUSARI_FILE='license.zmaw.de:' $(cd "$(dirname "$0")"; pwd)/../../configure FC="$FC" CC="$CC" FCFLAGS="$FCFLAGS" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" LIBS="$LIBS" --disable-openmp --enable-sct "$@"
