#!/bin/bash
  #=======================================================
  # input folders
  # define the ocean location. 
  #  ocean_location="local" means the local grids folders
  #  ocean_location="buildbot" means the standard buildbot oes path: ${icon_data_MainFolder}/oes} 
  #  ocean_location="" means user defined path in ocean_data_MainFolder, or if undefined the standard buildbot oes path: ${icon_data_MainFolder}/oes} 
  #  in other cases where 
  #    ocean_location/="" then ocean_data_MainFolder=/pool/data/ICON/oes/${ocean_location}
  
  ocean_location=${ocean_location:="fluent"}
  get_file=${get_file:='add_link_file'} # 'add_required_file'


  if [[ "x$ocean_location" = "buildbot" ]] ; then
    ocean_data_MainFolder=${icon_data_MainFolder}/oes  
  elif [[ "x$ocean_location" = "xlocal" ]] ; then
    ocean_data_MainFolder=${ICON_BASE_PATH}/grids   
  elif [[ "x$ocean_location" != "x" ]] ; then
    case "$target" in
      thunder|blizzard|mpipc)
        ocean_data_MainFolder=/pool/data/ICON/oes/${ocean_location}
# 	ocean_data_MainFolder=/scratch/mpi/CC/mh0287/oes/${ocean_location}
      ;;
#       blizzard) 
# 	ocean_data_MainFolder=/work/mh0287/oes/${ocean_location}
#       ;;
    esac
  fi 
   
  ocean_data_MainFolder=${ocean_data_MainFolder:=${icon_data_MainFolder}/oes}
  grid_name=${ocean_grids%.nc}
  ocean_data_InputFolder=${ocean_data_InputFolder:=${ocean_data_MainFolder}/${grid_name}}
  grids_folder=${grids_folder:=${ocean_data_InputFolder}}
  
  ocean_forcing_folder=${ocean_forcing_folder:=${ocean_data_InputFolder}}
  ocean_init_folder=${ocean_init_folder:=${ocean_data_InputFolder}}
  ocean_relax_folder=${ocean_relax_folder:=${ocean_data_InputFolder}}

  #=======================================================
  # input file names  
  #pre/postfixes of input files
  file_vertical_levels="${ocean_vertical_levels}levels"
  init_DataType=${init_DataType:="omipInitialState-AnnualAverage"}  # needs to be changed to phc3.0 30 year climatology
  relax_DataType=${relax_DataType:="omipRelaxSurface"}  
  forcing_DataType=${forcing_DataType:="omipForcing-mpiom"}
  if [[ "x$forcing_timescale" = "x1" ]] ; then
    forcing_FileFrequence=${forcing_FileFrequence:="Annual"}
  elif [[ "x$forcing_timescale" = "x12" ]] ; then
    forcing_FileFrequence=${forcing_FileFrequence:="MonthlyMean"}
  elif [[ "x$forcing_timescale" = "x365" ]] ; then
    forcing_FileFrequence=${forcing_FileFrequence:="Daily"}
  fi
 
  ocean_forcing_filename=${ocean_forcing_filename:=${forcing_DataType}${forcing_FileFrequence}-${grid_name}.nc}
  ocean_forcing_InputFilename=${ocean_forcing_folder}/${ocean_forcing_filename}

  ocean_initialState_filename=${ocean_initialState_filename:=${init_DataType}-${grid_name}-${file_vertical_levels}.nc}
  ocean_initialState_InputFilename=${ocean_init_folder}/${ocean_initialState_filename}

  ocean_relax_filename=${ocean_relax_filename:=${relax_DataType}-${grid_name}.nc}
  ocean_relax_InputFilename=${ocean_relax_folder}/${ocean_relax_filename}

  #=======================================================
  # re-naming of the input files when copying to the experiment folder
  ocean_forcing_outputFilename="ocean-flux.nc"
  ocean_initialState_outputFilename="initial_state.nc"
  ocean_relax_outputFilename="ocean-relax.nc"
   
  #=======================================================
  # add required files if this is not post processing
  case "x$RUNSCRIPT_NAME" in
    *post*)
      # for postprocessing we do not need files
    ;;
    #-------------------------------------------------
    *)
      # add files for runing the ocean  
      if [[ "x$iforc" = "x12" ]] ; then
        ls -l $ocean_forcing_InputFilename
        if [ $? -eq 0 ]; then
          $get_file ${ocean_forcing_InputFilename}     $ocean_forcing_outputFilename
        else
          echo "WARNING: $ocean_forcing_InputFilename does not exist - proceed from local disk"
        fi
      fi

      #--------------------------------------------------
      if [[ "x$iforc" = "x12" ]] ; then
        use_file_initialConditions=".true."
      fi
      if [[ "x$use_file_initialConditions" = "x.true." ]] ; then
        ls -l $ocean_initialState_InputFilename
        if [ $? -eq 0 ]; then
          $get_file ${ocean_initialState_InputFilename}          $ocean_initialState_outputFilename
        else
          echo "WARNING: $ocean_initialState_InputFilename does not exist - proceed from local disk"
        fi
      fi

      #--------------------------------------------------
      if [[ "x$init_relax" = "x1" ]] ; then
        ls -l $ocean_relax_InputFilename
        if [ $? -eq 0 ]; then
          $get_file ${ocean_relax_InputFilename} $ocean_relax_outputFilename
        else
          echo "WARNING: Cannot find restart file: ${ocean_relax_InputFilename}"
        fi

      fi
    ;;
  esac

  #===============================================================================================
