#!/bin/ksh
add_required_file ${basedir}/data/rrtmg_lw.nc           ./
add_link_file     ${basedir}/data/rrtmg_sw.nc           ./
add_link_file     ${basedir}/data/lsdata.nc             ./
add_required_file ${basedir}/data/ECHAM6_CldOptProps.nc ./

# APE BCs
if [ x$ozon_file != "x" ] ;  then
  add_required_file ${icon_data_rootFolder}/external/ape_ozone/$ozon_file ./o3_icon_DOM01.nc
else
  add_required_file ${icon_data_rootFolder}/external/ape_ozone/ape_o3_R2B04_1Pa_spr0.90-cell.nc ./o3_icon_DOM01.nc
fi

# vertical grid
if [[ $atmo_model_equations = 3 ]] ; then
  add_required_file ${basedir}/vertical_coord_tables/atm_hyb_sz_${nlev} ./
else
  add_required_file ${basedir}/vertical_coord_tables/atm_hyb_sp_${nlev} ./
fi

#-----------------------------------------------------------------------------
