#!/bin/ksh
add_required_file ${basedir}/data/rrtmg_lw.nc               ./
add_link_file     ${basedir}/data/rrtmg_sw.nc               ./
add_link_file     ${basedir}/data/lsdata.nc                 ./
add_required_file ${basedir}/data/ECHAM6_CldOptProps.nc     ./
add_required_file ${basedir}/data/dmin_wetgrowth_lookup.nc  ./   #for inwp_gscp==4
add_required_file ${basedir}/data/sound_rce                 ./
add_required_file ${basedir}/data/pmod.txt                  ./

#-----------------------------------------------------------------------------
