#! /bin/ksh
#=============================================================================
#
# This section of the run script containes the specifications of the experiment.
# The specifications are passed by namelist to the program.
# For a complete list see Namelist_overview.pdf
#
# J. Foerstner, DWD, 2008-11
# P. Ripodas,   DWD, 2010-09-15
# M. Koehler,   DWD, 2011-02-01
# J. Foerstner, DWD, 2011-03-06
#
#-----------------------------------------------------------------------------
#
# nec at DWD
# 
# submit: 
#   qsub run_ICONAM_R2B4_APE
#   qstat | grep mkoehler
#   nqstat
#   dayfile #hpcjob-id ("F" updating)
#   nqcat -n 200 -o #hpcjob-id
#   l ~/wq/.
#
# 4 OpenMP threads (max.=)
# 16 CPUs on one NODE (OpenMP)
#--------------------------------------------------

#### BATCH_SYSTEM=PBS ####

#PBS -N icon
#PBS -S /bin/ksh
#PBS -q lang
#PBS -m n
#PBS -r n
#PBS -l walltime=48:00:00
#PBS -o /e/uhome/mkoehler/wq
#PBS -j oe
#PBS -W umask=0027

# for PBS change to directory where job was submitted
# (without this job is started in HOME)
if [[ -n ${PBS_O_WORKDIR} ]] ; then
  cd ${PBS_O_WORKDIR}
fi

PATH=${PATH}:/SX/usr/bin:.
PATH=${PATH}:/e/rhome/routfor/routfox/abs     #CDO netcdf operators
PATH=${PATH}:/e/uhome/for1han/bin             #various scripts
export PATH

USER="mkoehler"
DATA_DIR="/e/uwork/"${USER}"/icon"     #/e/uwork, /e/uscratch, /e/gtmp
#DATA_DIR="/e/uscratch/"${USER}"/icon" #/e/uwork, /e/uscratch, /e/gtmp
                                      #or transfer data to oflxs04:/uwork1

# Directories:
EDIR="exp16"                          # working directory
EXPNAME="APE"                         # experiment identifier
IDIR="GRIDR2"                         # input directory

# absolute path to directory with plenty of space:
EXPDIR=${DATA_DIR}/experiments/${EDIR}
mkdir -p ${EXPDIR}


#-----------------------------------------------------------------------------
# Basic specifications of the simulation
# --------------------------------------

# These values need to be stored in variables, which are needed to
# construct filenames  or directories:

RR=2              # nroot (division of icosahedron edges)
BB=4              # number of bisections applied for the global grid
NLEV=90           # nlev = number of full levels
OPT="spr0.90"     # grid optimization
ICELL=3           # cell grid type, 3 triangles, 6 hexagons

IEQ=3             # equation system
#                     1=hydrost. atm. T
#                     1=hydrost. atm. theta dp
#                     3=non-hydrost. atm.,
#                     0=shallow water model
#                    -1=hydrost. ocean

IFORCING=3        # forcing to the equation system
#                     0 = no external forcing
#                     1 = Held-Suarez forcing
#                     2 = ECHAM6 physics
#                     3 = NWP forcing

# Here the length of the integration is converted from number of days
# to number of timesteps.

DTIME=225                     # time step in seconds (150, 180, 225, 300)
DT_DATA=`expr 12 \* 3600  `   # output each 12 hours
DT_DIAG=`expr 24 \* 3600  `   # ascii diagnostic output each 24 hours
DT_FILE=`expr 10 \* 86400 `   # 10 days per file
#DT_FILE=`expr 1  \* 3600 `   # 10 days per file
NDAYS=400                     # number of days to run


#-----------------------------------------------------------------------------
# ICON namelist parameters
# ------------------------
# For a complete list see Namelist_overview and Namelist_overview.pdf

cat > NAMELIST_ICON << EOF_NL
&run_ctl
 nproma      = 1024         ! array blocking length
 nlev        = ${NLEV}      ! number of full levels of vertical grid
 run_day     = ${NDAYS}     ! run length in days
 dtime       = ${DTIME}     ! timestep in seconds
 iequations  = ${IEQ}       ! equation system   1:T, 2:theta, -1:SW
 i_cell_type = ${ICELL}     ! 3 triangular cells, 6 hexagonal dells
 ldynamics   = .TRUE.       ! dynamics
 ltransport  = .TRUE.       ! tracer transport
 ntracer     = 6            ! 6 plus 1 for ozone
 iforcing    = ${IFORCING}  ! 3 NWP forcing
 ltestcase   = .TRUE.       ! run testcase
 msg_level   = 15           ! detailed report during integration
/
&nwp_phy_ctl
 inwp_gscp       = 1
 inwp_convection = 1
 inwp_cldcover   = 3        ! 0: no cld, 1: grid scale, 3: COSMO, 4: new diagnostic
 inwp_radiation  = 1        ! 1: RRTM, 2: Ritter-Geleyn
 inwp_turb       = 2        ! 1: Raschendorfer, 2: ECHAM, 3: EDMF-DUALM
 inwp_sso        = 0
 inwp_surface    = 0
 dt_conv         = 900
 dt_rad          = 1800
 dt_sso          = 900
/
&radiation_nml
 irad_o3         = 6        ! 0: no ozone, 6: ozone, attention: increase ntracer by one
 izenith         = 3        ! 4: NWP default, 3: no annual cycle
 dt_rad          = 1800
/
&sleve_ctl                  ! vertical grid standard output for message level >= 15
 min_lay_thckn   = 20.      ! lowest level thickness (between half-levels)
 top_height      = 50000.
 flat_height     = 20000.
 stretch_fac     = 0.6      ! stretching towards model top (1.0 default; smaller - bigger top level thickness)
 decay_scale_1   = 4000.    ! decay scales for topography
 decay_scale_2   = 2500.
 decay_exp       = 1.2
/
&nonhydrostatic_ctl
 iadv_rhotheta   = 2
 ivctype         = 2        ! set vertical grid automatically using sleve_ctl
 igradp_method   = 2        ! new default
 iadv_rcf        = 2        ! microphysics and turb and sat adj every 2 dynamic steps (2 or 4)
 exner_expol     = 0.60     ! exner function extrapolation?
 rayleigh_coeff  = 0.05     ! Rayleigh coefficient for damping in upper levels
 damp_height     = 35000.   ! damping height (set about 10km below top, 5-10 levels)
 vwind_offctr    = 0.2      ! off-centering for time differencing (like alpha in turb)
 l_open_ubc      = .TRUE.   ! top open upper boundary condition. might help to go higher
/
&nh_testcase_ctl
 nh_test_name      = 'APE_nh'     ! test case identifier
 ape_sst_case      = 'sst1'
/
&parallel_ctl
 p_test_run        = .FALSE.
 division_method   = 1
 n_ghost_rows      = 1
 l_log_checks      = .FALSE.
/
&io_ctl
 out_expname       = '${EXPNAME}' ! file name base
 dt_data           = ${DT_DATA}   ! daily output
 dt_file           = ${DT_FILE}   ! 30 days per file
 dt_diag           = ${DT_DIAG}
 lwrite_surface    = .TRUE.
 lwrite_cloud      = .TRUE.
 lwrite_precip     = .TRUE.
 lwrite_vorticity  = .TRUE.
 lwrite_pres       = .TRUE.
 lwrite_z3         = .TRUE.
 lwrite_omega      = .TRUE.
 lwrite_divergence = .TRUE.
/
&grid_ctl
 nroot       = ${RR}        ! root division of icosahedron edges
 start_lev   = ${BB}        ! number of bisections applied for the base grid
/
&dynamics_ctl
 idiv_method     = 1
 itime_scheme    = 5        ! default 4; 5: modified Matsuno for better numerical stability of sound waves
 divavg_cntrwgt  = 0.50
/
&transport_ctl
 ihadv_tracer  = 2,2,2,2,2,0
 ivadv_tracer  = 3,3,3,3,3,0
 igrad_c_miura = 1
 ctracer_list  = '123456'   ! '12345'  (123456 mit ozone)
 lvadv_tracer  = .TRUE.
 lstrang       = .FALSE.
 itype_hlimit  = 3
 itype_vlimit  = 1
 iord_backtraj = 1          ! default: 1
/
&diffusion_ctl
 hdiff_order      = 5
 hdiff_efdt_ratio = 4.0
 lhdiff_vn        = .TRUE.
 lhdiff_temp      = .FALSE.
 hdiff_multfac    = 1.0
 hdiff_tv_ratio   = 1.0
/
&lnd_ctl
    nlev_soil       = 7     ! 7 = default value for number of soil layers
    nztlev          = 2     ! 2 = default value for time integration scheme
    nlev_snow       = 1     ! 0 = default value for number of snow layers
    nsfc_subs       = 2     ! 1 = default value for number of TILES
    lseaice    = .FALSE.
    llake      = .FALSE.
    lmulti_snow= .FALSE.
/
&hydrostatic_ctl
/
&interpol_ctl
/
&gridref_ctl
/
&regularization_ctl
/
&ocean_ctl
/
EOF_NL

mv -f NAMELIST_ICON ${EXPDIR}


#-----------------------------------------------------------------------------
# job on NEC
#-----------

cat > /e/uhome/${USER}/wq/job.nec_tmp.$$ <<EOF_NEC
#### BATCH_SYSTEM=NQS2 ####

#PBS -N icon
#PBS -q normal@sx9esiox1
#PBS -j o
#PBS -o /e/uhome/${USER}/wq/o.icon_model.$$
#PBS -l cpunum_job=16
#PBS -b 1
#PBS -l elapstim_req=86400
#PBS -m n

set -x

export ICON_THREADS=16
export OMP_NUM_THREADS=16
export OMP_STACKSIZE=50M
export OMP_SCHEDULE="static"
export OMP_DYNAMIC="false"

# for PBS change to directory where job was submitted
# (without this job is started in HOME)
if [[ -n \${PBS_O_WORKDIR} ]] ; then
  cd \${PBS_O_WORKDIR}
fi
export F_PROGINF=DETAIL

# determine architecture
#arch=sx9-nec-superux-sx9ftr 
#arch=sx9-nec-superux-sx9debug 
arch=sx9-nec-superux-sx9omp
#arch=sx9-nec-superux-sx9mpiomp

# determine base directory (../icon-dev)
dir=\$(pwd -P)
WORK_DIR=\${dir%/*}

# absolute path to model binary, including the executable
MODEL=\${WORK_DIR}/build/\${arch}/bin/control_model

# horizontal grid file
#ln -sf ${DATA_DIR}/${IDIR}/iconR2B04-grid_spr0.90.nc ${EXPDIR}/iconR2B04_DOM01-grid.nc
#cp /e/uhome/dreinert/icon-dev/experiments/graphs/GRIDR2B4/iconR2B04-grid.nc ${EXPDIR}
cp /e/uhome/gzaengl/icon-dev/experiments/${IDIR}/iconR2B04-grid_spr0.90.nc  ${EXPDIR}/iconR2B04-grid.nc

# external parameters
ln -sf /e/uwork/hasensio/epresult/ICON/v1_0/R2B04/extpar_R2B04-DOM01.nc external_parameter_icon.nc

# vertical grid file (optional input)
cp \${WORK_DIR}/hyb_params/HYB_PARAMS_${NLEV}.nh   ${EXPDIR}

# radiation input files
cp /e/uhome/treinhar/ICON/ECHAM6_CldOptProps.nc    ${EXPDIR}
cp /e/uhome/treinhar/ICON/rrtmg_lw.nc              ${EXPDIR}

# start experiment
cd ${EXPDIR}
cp -p \${MODEL} ./hydro_atmos
./hydro_atmos

# check return code
rc=\${?}
if [[ ":\${rc}" != ':0' && ":\${rc}" != ':' ]] ; then
  print "QSUBW_ERROR: JOB_%HOSTNAME%_%PID%: RC = \${rc}"
fi

EOF_NEC


#-----------------------------------------------------------------------------
# submit and plot
#----------------

# copy plotting files
PLOTDIR=/e/uhome/${USER}/ncl
cp ${PLOTDIR}/iconplot.zonal.parallel.s    \
   ${PLOTDIR}/iconplot.zonal-vert.ncl      \
   ${PLOTDIR}/iconplot.zonal-time.ncl      \
   ${PLOTDIR}/iconplot.maps.ncl    ${EXPDIR}

cat > ${EXPDIR}/iconplot.zonal.list << EOF_LIST
iconplot.zonal.parallel.s -v T
iconplot.zonal.parallel.s -v U
iconplot.zonal.parallel.s -v V
iconplot.zonal.parallel.s -v W
iconplot.zonal.parallel.s -v CC
iconplot.zonal.parallel.s -v QV
iconplot.zonal.parallel.s -v QC
iconplot.zonal.parallel.s -v QI
iconplot.zonal.parallel.s -v Q1
iconplot.zonal.parallel.s -v Q2
iconplot.zonal.parallel.s -v Q3
iconplot.zonal.parallel.s -v Q4
iconplot.zonal.parallel.s -v Q5
EOF_LIST

# submit job to NEC and wait
qsubw /e/uhome/${USER}/wq/job.nec_tmp.$$
rc=${?}
if [[ ":${rc}" != ':0' ]] ; then
   exit 201
fi

# plotting on HPC
cd ${EXPDIR}
/e/uhome/for1han/bin/pshell -p7 -f iconplot.zonal.list
./iconplot.zonal.parallel.s
ncl iconplot.maps.ncl

# save data to ecfs
emkdir dwd:/${USER}/icon-exp/{EDIR}
ecp {EXPNAME}_R{RR}B0{BB}L{NLEV}_*.nc dwd:/${USER}/icon-exp/{EDIR}


#-----------------------------------------------------------------------------
exit 0
#-----------------------------------------------------------------------------
