#! /usr/bin/env python
# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_builders import *
#from model_paths import *
import argparse

parser = argparse.ArgumentParser(description='Add a builder to a machine.')
parser.add_argument('builder_name', type=str,  help='builder name')
parser.add_argument('--configureflags', dest="configureflags", type=str, help='the configure flags for the buildber', required=True)
parser.add_argument('--builderflags', dest="builderflags", type=str, help='the builder flags', required=True)
parser.add_argument('--machine', dest="machine_name", type=str, help='the machine name to add the builder', required=True)
parser.add_argument('--list', dest="list_name", type=str, help='the list', required=True)

args = parser.parse_args()
  
thisList  = buildbot_experiments_list(args.list_name)
thisList.add_builder(args.builder_name, args.machine_name, args.configureflags, args.builderflags)
thisList.write()
print("Builder "+args.builder_name+" is added to the Machine "+ args.machine_name+".")

quit()


