#!/bin/ksh
#------------------------------------------------------------------------------
#
# This script is called on all Buildbot slaves and should be used to call
# 	./target_confmake.ksh $BB_SLAVE
#
# First version by Walter Sauf (MPI-M, 2009-10-22)
#
# $Rev: 1601 $:     Revision of last commit
# $Author: walter.sauf $:  Author of last commit
# $Date: 2010-03-30 16:28:38 +0200 (Tue, 30 Mar 2010) $:    Date of last commit
#
#==============================================================================
#
# For each slave the Buildbot server sets two environment variables 
# BB_SYSTEM and BB_SLAVE:
# - BB_SYSTEM = name of the system, on which the test shall run
# - BB_SLAVE  = name of the specific build configuration
#
# The variables are defined in the ICON.cfg configuration file for Buildbot. 
# Following the "c['builders'] = " statement, the two environment variables are 
# defined in the 'env':{'BB_SYSTEM': '...', 'BB_SLAVE':'...' statement.
# 
#==============================================================================

check_error()
{

# Check if the first parameter (return status) is not OK 

  if [ $1 -ne 0 ] 
  then

# Stop running this script and return the error status
    echo "ERROR: $2"
    exit $1
  fi
}

#------------------------------------------------------------------------------
# temorary disable squall
if [ x$BB_SYSTEM = "xsquall" ] ; then
  echo "Squall is disabled for the moment"
  exit 1
fi
#------------------------------------------------------------------------------

#==============================================================================

# configure the Makefile and make the executables
./target_confmake.ksh ${BB_SLAVE}

# stop if not ok
check_error $? "bb_make: ./target_confmake.ksh  ${BB_SLAVE}"

#==============================================================================

# Create "setting" file for bb_run script and ".status.file" for Buildbot

STATUS_FILE=${PWD}/.status.file
echo "1" >  ${PWD}/.status.file

SETTING_FILE=${PWD}/setting
rm -f ${SETTING_FILE}

#------------------------------------------------------------------------------

# set environment variables
echo "export SETTING_FILE=${SETTING_FILE}"               > ${SETTING_FILE}
echo "export STATUS_FILE=${STATUS_FILE}"                >> ${SETTING_FILE}
echo "export BB_SYSTEM=${BB_SYSTEM}"                    >> ${SETTING_FILE}
echo "export BB_SLAVE=${BB_SLAVE}"                      >> ${SETTING_FILE}

# working directory
echo "export WORKING_PATH=${PWD}"                       >> ${SETTING_FILE}

# load environment variables
case ${target} in
    blizz* )
        echo ". /client/etc/profile.blizzard"           >> ${SETTING_FILE}
        ;;
    mpipc* | squall* | tornado* )
        echo ". /client/etc/profile.zmaw"               >> ${SETTING_FILE}
        ;;
esac

# load fortran module
if [ "$loadmodule" != "" ]
then
    echo ". module load $loadmodule" >> ${SETTING_FILE}
fi

#==============================================================================

# finish script with OK status
#
exit 0
