#!/bin/ksh
#------------------------------------------------------------------------------
# This script is called on all buildbot slaves and should be used 
# to build doxygen generated source code documentation
# First version by Walter Sauf (MPI-M, 2011-05-05)
#
# $Rev: -1 $:     Revision of last commit
# $Author: $:  Author of last commit
# $Date: $:    Date of last commit
#------------------------------------------------------------------------------


. /client/etc/profile.zmaw

module load graphviz doxygen
./configure
make doc

