#! /usr/bin/env python
# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_builders import *
from model_paths import *
import argparse

parser = argparse.ArgumentParser(description='Build a builder; compile and create the runscripts of the builder.')
parser.add_argument('builder_name', type=str, help='the builder')
parser.add_argument('--list', dest="list_name", type=str, help='buildbot list', required=True)
args = parser.parse_args()

#print(args.name)
paths = model_paths()
if not paths.thisListExists(args.list_name):
  print("This list does not exist.")
  quit(1)
  
thisList       = buildbot_experiments_list(args.list_name)
status         = thisList.make_binaries(args.builder_name)
if not status == 0: quit(1)
runscriptsList = thisList.make_runscripts(args.builder_name)


#write runscripts
listfile = open(paths.get_runpath()+"/runscripts_list", 'w')
for runscript in runscriptsList:
  listfile.write(runscript+" ")
listfile.close()


#print(runscriptsList)

