#!/bin/bash

addexp="./addexp"
#############################################################################
##
## create icon-dev list
##
#############################################################################
listname=nec
./rmlist $listname
# ./mklist $listname
./create_all_builders $listname

# deactivate all builders except DWD_cray
./set_builder_flags Inactive --builders MISTRAL_gcc                  --list $listname
./set_builder_flags Inactive --builders MISTRAL_intel17              --list $listname
./set_builder_flags Inactive --builders MISTRAL_intel17_hybrid       --list $listname
./set_builder_flags Inactive --builders MISTRAL_intel17_openmp       --list $listname
./set_builder_flags Inactive --builders MISTRAL_intel17_hybrid_mixed --list $listname
./set_builder_flags Inactive --builders MISTRAL_intel18              --list $listname
./set_builder_flags Inactive --builders MISTRAL_intel18_hybrid       --list $listname
./set_builder_flags Inactive --builders MISTRAL_intel18_openmp       --list $listname
./set_builder_flags Inactive --builders MISTRAL_intel18_hybrid_mixed --list $listname
./set_builder_flags Inactive --builders MISTRAL_nag                  --list $listname
./set_builder_flags Inactive --builders MISTRAL_nag_serial           --list $listname
./set_builder_flags Inactive --builders BREEZE_gcc                   --list $listname
./set_builder_flags Inactive --builders BREEZE_gcc_openmp            --list $listname
./set_builder_flags Inactive --builders BREEZE_intel                 --list $listname
./set_builder_flags Inactive --builders BREEZE_intel_openmp          --list $listname
./set_builder_flags Inactive --builders BREEZE_nag                   --list $listname
./set_builder_flags Inactive --builders DAINT_CPU_cce                --list $listname
./set_builder_flags Inactive --builders DAINT_CPU_pgi                --list $listname
./set_builder_flags Inactive --builders DAINT_GPU_pgi                --list $listname
./set_builder_flags Inactive --builders DWD_cray                     --list $listname
./set_builder_flags Active   --builders DWD_nec                      --list $listname

# run only some nwp checks on DWD-site and have some tea meanwhile
$addexp checksuite.rcnl.dwd.de/exp.run_ICON_15_R19B7-ID2_ass.run --list $listname

#lets see the list
./lslist $listname
#-----------------------------------------------------------

