#!/bin/bash

addexp="./addexp"
#############################################################################
##
## create icon-dev list
##
#############################################################################
listname=problems
./rmlist $listname
# ./mklist $listname
./create_all_builders $listname

#-----------------------------------------------------------
# this once fail
$addexp checksuite.icon-dev/check.atm_amip_update --list $listname
$addexp exp.test_nwp_R02B04N06_multifile_restart --without-configureflags without-mpi --runflags "cpu_time=00:30:00 no_of_nodes=2" --builders MISTRAL_nag --list $listname
$addexp exp.test_nwp_R02B04N06multi2 --without-configureflags without-mpi with-openmp --runflags "cpu_time=00:45:00 no_of_nodes=2" --builders MISTRAL_nag --list $listname
$addexp checksuite.icon-dev/check.atm_icoles_nested --runflags "cpu_time=00:30:00" --builders MISTRAL_nag --list $listname
$addexp exp.aloy_pre04_bb --without-configureflags without-mpi --runflags "cpu_time=00:30:00 no_of_nodes=4" --builders MISTRAL_nag --list $listname

#-----------------------------------------------------------
#lets see the list
./lslist $listname
#-----------------------------------------------------------

