#!/bin/bash

addexp="./addexp"
#############################################################################
##
## create icon-dev list
##
#############################################################################
listname=icon-dev
./rmlist $listname
# ./mklist $listname
./create_all_builders $listname

#-----------------------------------------------------------
# AES
# add amip tests to all builders
$addexp "checksuite.icon-dev/check.atm_amip*"                --list $listname
$addexp "checksuite.icon-dev/check.atm_heldsuarez"           --list $listname
$addexp "checksuite.icon-dev/check.atm_ape"                  --list $listname
$addexp "checksuite.icon-dev/check.atm_sma"                  --list $listname
$addexp "checksuite.icon-dev/check.atm_2mom_bubble_rceTorus" --list $listname
# add concurrent ps_rad test
$addexp "aes/exp.test_concurrent_psrad_model" --without-configureflags without-mpi --machines mistral  --list $listname
#-----------------------------------------------------------
# in case reference data are not available uncomment this line
#./rmexp checksuite.icon-dev/check.atm_amip_update  --list $listname

#-----------------------------------------------------------
# OES
# add omip technical tests only with mpi parallelization
$addexp checksuite.ocean_internal/technical/exp.ocean_omip_ptest checksuite.ocean_internal/technical/exp.test_ocean_omip_technical \
  --without-configureflags without-mpi enable-mixed --runflags "cpu_time=00:30:00 mpi_procs_pernode=5"  --list $listname
# add omip binary-identical test on mistral
$addexp checksuite.ocean_internal/omip/exp.test_ocean_omip_10days checksuite.ocean_internal/ShallowWater/exp.ocean_WilliamsonTestCase2_Hex \
 --machines mistral --machines mistral --without-configureflags enable-mixed --runflags "cpu_time=00:30:00 queue=compute" --list $listname
$addexp checksuite.ocean_internal/hamocc/exp.test_concurrent_hamocc_omip_10days  \
--machines mistral --without-configureflags without-mpi enable-mixed --runflags "cpu_time=00:30:00 no_of_nodes=2 queue=compute" --list $listname
$addexp checksuite.ocean_internal/technical/exp.test_multioutput_model_40km \
--machines mistral --without-configureflags without-mpi with-openmp enable-mixed --runflags "cpu_time=00:30:00 no_of_nodes=2 queue=compute" --list $listname



#-----------------------------------------------------------
# communication
$addexp checksuite.infrastructure/testbed/exp.icon-testbed_communication_orig --builders MISTRAL_intel17 --list $listname
$addexp checksuite.infrastructure/testbed/exp.icon-testbed_communication_yaxt --builders MISTRAL_intel17 --list $listname
$addexp checksuite.infrastructure/testbed/exp.atm_amip_yaxt    --builders MISTRAL_intel17 --list $listname
$addexp checksuite.infrastructure/testbed/exp.ocean_omip_yaxt  --builders MISTRAL_intel17 --list $listname
$addexp checksuite.infrastructure/testbed/exp.icon-testbed_read-netcdf --builders MISTRAL_intel17 --list $listname


#-----------------------------------------------------------
# CSCS
# Additional tests for GPU
# Some AMIP tests fail with extremely small differences in some Physics fields; investigation ongoing

# CCE-CPU and NVIDIA-CPU/GPU: remove traditional tests which use PSrad

./rmexp checksuite.icon-dev/check.atm_ape                  --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
./rmexp checksuite.icon-dev/check.atm_amip                 --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
./rmexp checksuite.icon-dev/check.atm_amip_update          --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
./rmexp checksuite.icon-dev/check.atm_amip_diagparams_constbc_nojsb_notransport_nodynamics --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
./rmexp checksuite.icon-dev/check.atm_sma                  --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
./rmexp checksuite.icon-dev/check.atm_2mom_bubble_rceTorus --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname

# But add the RTE-RRTMGP based tests
$addexp checksuite.icon-dev/check.atm_rte_rrtmgp_ape  --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
$addexp checksuite.icon-dev/check.atm_rte_rrtmgp_amip --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
$addexp checksuite.icon-dev/check.atm_rte_rrtmgp_amip_update --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
$addexp checksuite.icon-dev/check.atm_rte_rrtmgp_amip_diagparams_constbc_nojsb_notransport_nodynamics --builders DAINT_CPU_cce DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname

# NVIDIA for GPU: failing currently because:
#              mo_ice_interface:ice_fast_interface: This part has not been ported to GPU.
./rmexp checksuite.ocean_internal/technical/exp.ocean_omip_ptest                  --builders DAINT_GPU_pgi DAINT_GPU_nvidia --list $listname
./rmexp checksuite.ocean_internal/technical/exp.test_ocean_omip_technical         --builders DAINT_GPU_pgi DAINT_GPU_nvidia --list $listname

# add tolerance check to daint builders
$addexp checksuite.icon-dev/check.mch_ch_lowres                                   --builders DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
$addexp "checksuite.icon-dev/check.mch_opr_r04b07*"                               --builders DAINT_CPU_pgi DAINT_GPU_pgi DAINT_CPU_nvidia DAINT_GPU_nvidia --list $listname
# $addexp "checksuite.icon-dev/check.mch_opr_r19b07_midnight"                       --builders DAINT_GPU_pgi DAINT_CPU_pgi --list $listname

# NVIDIA for GPU: nesting fails with NVIDIA 21.3. It has, however successfully been tested on a linux workstation with NVIDIA 21.2
# ==> temporarily disable test for DAINT_GPU_NVIDIA
./rmexp checksuite.icon-dev/check.mch_opr_r04b07_nest                             --builders DAINT_GPU_nvidia --list $listname

# add tracer only test to DAINT builders (for checking equivalence of vertical transport code for GPU vs CPU)
$addexp checksuite.icon-dev/check.atm_tracer_Hadley                                  --builders DAINT_CPU_pgi DAINT_CPU_nvidia --list $listname
#$addexp checksuite.icon-dev/check.atm_tracer_Hadley                                  --builders DAINT_GPU_pgi DAINT_GPU_nvidia --list $listname

#-----------------------------------------------------------
# DWD
#
# builder: mistral
# tests for nwp
$addexp exp.test_nwp_R02B04N06multi exp.test_nwp_R02B04_R02B05_nest  --without-configureflags without-mpi --runflags "cpu_time=00:30:00"  --machines mistral --list $listname
$addexp exp.test_nwp_R02B04N06_multifile_restart  --without-configureflags without-mpi --runflags "cpu_time=00:30:00 no_of_nodes=2"  --machines mistral --list $listname
# this experiment runs only with-mpi and without openmp
$addexp exp.test_nwp_R02B04N06multi2 --machines mistral --without-configureflags without-mpi with-openmp \
--machines mistral --runflags "cpu_time=00:45:00 no_of_nodes=2" --list $listname
#
# builders at DWD
for builder in DWD_nec DWD_nec_yac2; do
  $addexp checksuite.rcnl.dwd.de/exp.run_ICON_02_R2B13_lam.run                       --builders ${builder} --list $listname
  $addexp checksuite.rcnl.dwd.de/exp.run_ICON_07_R02B04N06M_restarttest.run          --builders ${builder} --list $listname
  $addexp checksuite.rcnl.dwd.de/exp.run_ICON_08_R19B7-ID2_oper.run                  --builders ${builder} --list $listname
  $addexp checksuite.rcnl.dwd.de/exp.run_ICON_11_R3B08_lam_initmode7_restarttest.run --builders ${builder} --list $listname
  $addexp checksuite.rcnl.dwd.de/exp.run_ICON_14_R2B6N7_oper_IAU_and_restarttest.run --builders ${builder} --list $listname
  $addexp checksuite.rcnl.dwd.de/exp.run_ICON-SCM_02_REAL.run                        --builders ${builder} --list $listname
done
for builder in DWD_nec DWD_nec_yac2 DWD_nec_hybrid; do
  # remove non-dwd tests
  ./rmexp checksuite.ocean_internal/technical/exp.ocean_omip_ptest               --builders ${builder} --list $listname
  ./rmexp checksuite.ocean_internal/technical/exp.test_ocean_omip_technical      --builders ${builder} --list $listname
  ./rmexp checksuite.icon-dev/check.atm_amip*                                    --builders ${builder} --list $listname
  ./rmexp checksuite.icon-dev/check.atm_heldsuarez                               --builders ${builder} --list $listname
  ./rmexp checksuite.icon-dev/check.atm_ape                                      --builders ${builder} --list $listname
  ./rmexp checksuite.icon-dev/check.atm_sma                                      --builders ${builder} --list $listname
  ./rmexp checksuite.icon-dev/check.atm_2mom_bubble_rceTorus                     --builders ${builder} --list $listname
done
# only DWD_nec
$addexp checksuite.rcnl.dwd.de/exp.run_ICON_09_R2B6N7_oper_EPS.run               --builders DWD_nec --list $listname
# DWD_nec_hybrid
$addexp checksuite.rcnl.dwd.de/exp.run_ICON_11_R3B08_lam_initmode7_restarttest.run --builders DWD_nec_hybrid --list $listname
$addexp checksuite.rcnl.dwd.de/exp.run_ICON_14_R2B6N7_oper_IAU_and_restarttest.run --builders DWD_nec_hybrid --list $listname

#-----------------------------------------------------------
# Ruby0 coupled tests, only with mpi
$addexp exp.esm_bb_ruby0 --without-configureflags without-mpi --machines mistral --runflags "cpu_time=00:20:00 no_of_nodes=4" --list $listname

#-----------------------------------------------------------
# Other tests
#   torus test from Anurag : red, move to problems list
$addexp checksuite.icon-dev/check.atm_rce_les  --machines mistral  --runflags "cpu_time=00:30:00" --list $listname
#   old test from Anurag
$addexp checksuite.icon-dev/check.atm_icoles_nested --machines mistral  --runflags "cpu_time=00:30:00 queue=compute" --list $listname
#   old test from Levi
$addexp exp.nat_rce_cbl_120km_nwp  --machines mistral  --runflags "cpu_time=00:30:00" --list $listname
#   very old test from Pilar
$addexp exp.nat_jww_nwp_mpiomp --without-configureflags without-mpi  --machines mistral --runflags "cpu_time=00:30:00" --list $listname

# test memory loggin in amip setup
$addexp checksuite.infrastructure/memLog/exp.atm_memLog         --builders MISTRAL_intel18_hybrid MISTRAL_intel17_hybrid MISTRAL_gcc --runflags "cpu_time=00:10:00 no_of_nodes=8" --list $listname
$addexp checksuite.infrastructure/memLog/exp.atm_memLog_AsyncIO --builders MISTRAL_intel18_hybrid MISTRAL_intel17_hybrid MISTRAL_gcc --runflags "cpu_time=00:10:00 no_of_nodes=8" --list $listname
$addexp checksuite.infrastructure/memLog/exp.oce_memLog         --builders MISTRAL_intel18_hybrid MISTRAL_intel17_hybrid MISTRAL_gcc --runflags "cpu_time=00:10:00 no_of_nodes=8" --list $listname
#-----------------------------------------------------------
#remove red setups
./rmexp exp.test_nwp_R02B04N06_multifile_restart exp.test_nwp_R02B04N06multi2 --builders MISTRAL_nag --list $listname
./rmexp checksuite.icon-dev/check.atm_icoles_nested --builders MISTRAL_intel17_openmp --list $listname
#-----------------------------------------------------------

# activate runs for the CDI-PIO builder on mistral
./set_builder_flags Active --builders MISTRAL_intel18_pio --list $listname
for builder in MISTRAL_intel18_pio; do
  $addexp checksuite.infrastructure/output/exp.atm_amip_R2B4_1day_pio --builders ${builder} --list $listname
  $addexp checksuite.infrastructure/output/exp.atm_amip_R2B4_1day     --builders ${builder} --list $listname
  $addexp exp.esm_bb_ruby0_pio      --builders ${builder} --list $listname --runflags "cpu_time=00:20:00 no_of_nodes=4"
  $addexp exp.esm_bb_ruby0          --builders ${builder} --list $listname --runflags "cpu_time=00:20:00 no_of_nodes=4"
  $addexp checksuite.infrastructure/output/exp.hamocc_omip_10days  --builder ${builder} --list $listname
done

# activate experiments for the Mac builder and breeze
for builder in MPIMAC_gcc BREEZE_gcc BREEZE_nag BREEZE_intel; do
  ./set_builder_flags Active --builders ${builder}  --list $listname
  $addexp exp.atm_amip_test --builders ${builder} --list $listname --runflags "mpi_procs_pernode=4"
  $addexp checksuite.ocean_internal/omip/exp.ocean_omip_short_r2b4 --builders ${builder} --list $listname --runflags "mpi_procs_pernode=4"
done


# add tests for checking yaxt and yac stand-alone; this needs yaxt/yac to be enabled
$addexp  checksuite.infrastructure/checkExternals/exp.check_externals_MISTRAL.run --builders MISTRAL_gcc --list ${listname}
$addexp  checksuite.infrastructure/checkExternals/exp.check_externals_DWD.run --builders DWD_nec_yac2 --list ${listname}

#lets see the list
./lslist $listname
#-----------------------------------------------------------

