#!/bin/bash

addexp="./addexp"
#############################################################################
##
## create icon-dev list
##
#############################################################################
listname=icon-dev
./rmlist $listname
# ./mklist $listname
./create_all_builders $listname

#-----------------------------------------------------------
# this one fails
$addexp checksuite.icon-dev/check.atm_amip_update      --list $listname

#-----------------------------------------------------------
#lets see the list
./lslist $listname
#-----------------------------------------------------------

