#!/bin/bash

addexp="./addexp"
#############################################################################
##
## create aes-ref list
##
#############################################################################
list=aes-ref
./rmlist $list
./mklist $list
machine=mistral
./addmachine $machine --list $list
./addbuilder MISTRAL_gcc            --machine $machine --configureflags="--with-fortran=gcc --with-yaxt"                  --builderflags="Active"  --list $list

./addbuilder MISTRAL_intel          --machine $machine --configureflags="--with-fortran=intel --with-yaxt"                --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel_hybrid   --machine $machine --configureflags="--with-fortran=intel --with-openmp --with-yaxt"  --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel_openmp   --machine $machine --configureflags="--with-fortran=intel --without-mpi --with-openmp"  --builderflags="Active"  --list $list

./addbuilder MISTRAL_intel17        --machine $machine --configureflags="--with-fortran=intel17 --with-yaxt"                --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel17_hybrid --machine $machine --configureflags="--with-fortran=intel17 --with-openmp --with-yaxt"  --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel17_openmp --machine $machine --configureflags="--with-fortran=intel17 --without-mpi --with-openmp"  --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18        --machine $machine --configureflags="--with-fortran=intel18 --with-yaxt"                --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18_hybrid --machine $machine --configureflags="--with-fortran=intel18 --with-openmp --with-yaxt"  --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18_openmp --machine $machine --configureflags="--with-fortran=intel18 --without-mpi --with-openmp"  --builderflags="Active"  --list $list

./addbuilder MISTRAL_intel17_hybrid_mixed --machine $machine --configureflags="--with-fortran=intel17 --with-openmp --with-yaxt --enable-mixed" --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18_hybrid_mixed --machine $machine --configureflags="--with-fortran=intel18 --with-openmp --with-yaxt --enable-mixed" --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel_hybrid_mixed   --machine $machine --configureflags="--with-fortran=intel --with-openmp --with-yaxt --enable-mixed" --builderflags="Active"  --list $list

./addbuilder MISTRAL_nag            --machine $machine --configureflags="--with-fortran=nag --with-yaxt"                  --builderflags="Active"  --list $list

#CSCS builders
machine=daint
./addmachine $machine --list $list
./addbuilder DAINT_CPU_cce        --machine $machine --configureflags="--with-fortran=cray" --builderflags="Active"      --list $list
./addbuilder DAINT_GPU_cce        --machine $machine --configureflags="--with-fortran=cray_gpu" --builderflags="Active"  --list $list

#-----------------------------------------------------------
# AES
# add amip binary-identical test on mistral
$addexp checksuite.icon-dev/check.atm_amip_update \
 --machines mistral --machines mistral --runflags "queue=compute" --list $list

#-----------------------------------------------------------
#lets see the list
./lslist $list
#-----------------------------------------------------------

