#!/bin/bash

addexp="./addexp"
#############################################################################
##
## create icon-dev list
##
#############################################################################
listname=icon-dev
./rmlist $listname
./mklist $listname

#-----------------------------------------------------------
# add amip tests to all builders
$addexp "checksuite.icon-dev/check.atm_amip*" --list $listname

#-----------------------------------------------------------
# add omip technical tests only for builders with mpi parallelization
$addexp checksuite.ocean_internal/omip/exp.ocean_omip_ptest checksuite.ocean_internal/technical/exp.test_ocean_omip_technical \
  --without-configureflags without-mpi --runflags "cpu_time=00:30:00"  --list $listname
# add omip binary-identical test and Hex test to all builders
$addexp checksuite.ocean_internal/omip/exp.test_ocean_omip_10days checksuite.ocean_internal/ShallowWater/exp.ocean_WilliamsonTestCase2_Hex \
--runflags "cpu_time=00:30:00" --list $listname
# add ocean tests to the restricted builder MISTRAL_ocean
./set_builder_flags Active             --builders MISTRAL_ocean  --list $listname
$addexp checksuite.ocean_internal/omip/exp.ocean_omip_ptest checksuite.ocean_internal/technical/exp.test_ocean_omip_technical \
checksuite.ocean_internal/omip/exp.test_ocean_omip_10days checksuite.ocean_internal/ShallowWater/exp.ocean_WilliamsonTestCase2_Hex \
--builders MISTRAL_ocean --runflags "cpu_time=00:30:00" --list $listname
./set_builder_flags Ocean             --builders MISTRAL_ocean  --list $listname

#-----------------------------------------------------------
# tests for nwp
$addexp exp.test_nwp_R02B04N06multi  exp.test_nwp_R02B04_R02B05_nest  --without-configureflags without-mpi --runflags "cpu_time=00:30:00" --list $listname
# this experiment runs only with-mpi and without openmp
$addexp exp.test_nwp_R02B04N06multi2 --machines mistral daint_cpu --without-configureflags without-mpi with-openmp --runflags "cpu_time=00:45:00 no_of_nodes=2" --list $listname

#-----------------------------------------------------------
# test coupled run, only with mpi
$addexp exp.couple_atmo-ocean --without-configureflags without-mpi --runflags "cpu_time=00:30:00" --list $listname


#-----------------------------------------------------------
# Other tests
#   torus test from Anurag
$addexp checksuite.icon-dev/check.atm_rce_les --runflags "cpu_time=00:30:00" --list $listname
#   old test from Anurag
$addexp checksuite.icon-dev/check.atm_icoles_nested --runflags "cpu_time=00:30:00" --list $listname
#   old test from Levi
$addexp exp.nat_rce_cbl_120km_nwp --runflags "cpu_time=00:30:00" --list $listname
#   very old test from Pilar
$addexp exp.nat_jww_nwp_mpiomp --without-configureflags without-mpi --runflags "cpu_time=00:30:00" --list $listname
#   obsolete test from Leonidas, will be deleted
$addexp checksuite.ocean_internal/other/exp.oce_testbed_read --runflags "cpu_time=00:30:00" --list $listname


#-----------------------------------------------------------
#lets see the list
./lslist $listname

#commit the list
# svn add experiment_lists/$listname
# svn commit experiment_lists/$listname -m "[buildbot_scripts] update $listname"

#############################################################################
##
## create build_only list
##
#############################################################################
listname=build_only
./rmlist $listname
./mklist $listname
./set_builder_flags build_only --builders "*" --list $listname
#lets see the list
./lslist $listname

#############################################################################
