#!/bin/bash

addexp="./addexp"
#############################################################################
##
## create icon-dev list
##
#############################################################################
listname=icon-dev
./rmlist $listname
# ./mklist $listname
./create_all_builders $listname

#-----------------------------------------------------------
# AES
# add amip tests to all builders
$addexp "checksuite.icon-dev/check.atm_amip*"      --list $listname
$addexp "checksuite.icon-dev/check.atm_heldsuarez" --list $listname
$addexp "checksuite.icon-dev/check.atm_ape"        --list $listname
# add concurrent ps_rad test 
$addexp "aes/exp.test_concurrent_psrad_model" --without-configureflags without-mpi --machines mistral  --list $listname
#-----------------------------------------------------------
# in case reference data are not available uncomment this line
#./rmexp checksuite.icon-dev/check.atm_amip_update  --list $listname

#-----------------------------------------------------------
# OES
# add omip technical tests only with mpi parallelization
$addexp checksuite.ocean_internal/technical/exp.ocean_omip_ptest checksuite.ocean_internal/technical/exp.test_ocean_omip_technical \
   --without-configureflags without-mpi enable-mixed --runflags "cpu_time=00:30:00"  --list $listname
# add omip binary-identical test on mistral
$addexp checksuite.ocean_internal/omip/exp.test_ocean_omip_10days checksuite.ocean_internal/ShallowWater/exp.ocean_WilliamsonTestCase2_Hex \
 --machines mistral --machines mistral --without-configureflags enable-mixed --runflags "cpu_time=00:30:00 queue=compute" --list $listname

# add ocean tests to the restricted builder MISTRAL_ocean incl. its intel17 version
./set_builder_flags Active             --builders MISTRAL_ocean  --list $listname
./set_builder_flags Active             --builders MISTRAL_ocean_intel17  --list $listname
$addexp checksuite.ocean_internal/technical/exp.ocean_omip_ptest checksuite.ocean_internal/technical/exp.test_ocean_omip_technical \
checksuite.ocean_internal/omip/exp.test_ocean_omip_10days checksuite.ocean_internal/ShallowWater/exp.ocean_WilliamsonTestCase2_Hex \
--builders MISTRAL_ocean MISTRAL_ocean_intel17 --runflags "cpu_time=00:30:00 queue=compute" --list $listname
./set_builder_flags Ocean             --builders MISTRAL_ocean  --list $listname
./set_builder_flags Ocean             --builders MISTRAL_ocean_intel17  --list $listname

#-----------------------------------------------------------
# CSCS
# Additional tests for GPU 
# Some AMIP tests fail with extremely small differences in some Physics fields; investigation ongoing

./rmexp "checksuite.icon-dev/check.atm_amip"                        --builders DAINT_GPU_cce --list $listname
./rmexp "checksuite.icon-dev/check.atm_amip_update"                 --builders DAINT_GPU_cce --list $listname
./rmexp "checksuite.icon-dev/check.atm_amip_noparams"               --builders DAINT_GPU_cce --list $listname
$addexp exp.atm_amip_noforcing_validate_test --builders DAINT_GPU_cce --runflags "cpu_time=00:10:00" --list $listname
$addexp exp.nh35_tri_jws_validate --builders DAINT_GPU_cce --runflags "cpu_time=00:10:00 no_of_nodes=5" --list $listname

# PGI for CPU: failing currently are atm_amip_update (missing reference data) and
# atm_heldsaurez (z_at_plevels:: Error in computing interpolation coefficients)
./rmexp "checksuite.icon-dev/check.atm_amip_update"                 --builders DAINT_CPU_pgi --list $listname
./rmexp "checksuite.icon-dev/check.atm_heldsaurez"                  --builders DAINT_CPU_pgi --list $listname

#-----------------------------------------------------------
# DWD
# tests for nwp
$addexp exp.test_nwp_R02B04N06multi exp.test_nwp_R02B04_R02B05_nest  --without-configureflags without-mpi --runflags "cpu_time=00:30:00"  --machines mistral --list $listname
$addexp exp.test_nwp_R02B04N06_multifile_restart  --without-configureflags without-mpi --runflags "cpu_time=00:30:00 no_of_nodes=2"  --machines mistral --list $listname
# this experiment runs only with-mpi and without openmp
$addexp exp.test_nwp_R02B04N06multi2 --machines mistral --without-configureflags without-mpi with-openmp \
--machines mistral --runflags "cpu_time=00:45:00 no_of_nodes=2" --list $listname

#-----------------------------------------------------------
# ESM2 coupled tests, only with mpi
# test fully coupled run - gcc excluded due to error
$addexp exp.aloy_pre04_bb --without-configureflags without-mpi --machines mistral --runflags "cpu_time=00:30:00 no_of_nodes=4" --list $listname

#-----------------------------------------------------------
# Other tests
#   torus test from Anurag : red, move to problems list
$addexp checksuite.icon-dev/check.atm_rce_les  --machines mistral  --runflags "cpu_time=00:30:00" --list $listname
#   old test from Anurag
$addexp checksuite.icon-dev/check.atm_icoles_nested --machines mistral  --runflags "cpu_time=00:30:00" --list $listname
#   old test from Levi
$addexp exp.nat_rce_cbl_120km_nwp  --machines mistral  --runflags "cpu_time=00:30:00" --list $listname
#   very old test from Pilar
$addexp exp.nat_jww_nwp_mpiomp --without-configureflags without-mpi  --machines mistral --runflags "cpu_time=00:30:00" --list $listname

# test memory loggin in amip setup
$addexp checksuite.infrastructure/memLog/exp.atm_memLog         --builders MISTRAL_intel_hybrid MISTRAL_intel17_hybrid MISTRAL_gcc --runflags "cpu_time=00:10:00 no_of_nodes=8" --list $listname
$addexp checksuite.infrastructure/memLog/exp.atm_memLog_AsyncIO --builders MISTRAL_intel_hybrid MISTRAL_intel17_hybrid MISTRAL_gcc --runflags "cpu_time=00:10:00 no_of_nodes=8" --list $listname
$addexp checksuite.infrastructure/memLog/exp.oce_memLog         --builders MISTRAL_intel_hybrid MISTRAL_intel17_hybrid MISTRAL_gcc --runflags "cpu_time=00:10:00 no_of_nodes=8" --list $listname
#-----------------------------------------------------------
#remove red setups
./rmexp exp.test_nwp_R02B04N06_multifile_restart exp.test_nwp_R02B04N06multi2 checksuite.icon-dev/check.atm_icoles_nested exp.aloy_pre04_bb --builders MISTRAL_nag --list $listname
#-----------------------------------------------------------

#lets see the list
./lslist $listname
#-----------------------------------------------------------

