#!/bin/bash

#############################################################################
##
## create build_only list
##
#############################################################################
listname=build_only
./rmlist $listname
./create_all_builders $listname
./set_builder_flags build_only --builders "*" --list $listname
#lets see the list
./lslist $listname

#############################################################################
