#!/bin/bash
set -x
# create all builders for a given list
list=$1
if [ x$list == x ]; then
  echo "Builbot list name missing"
  exit 1
fi

./mklist $list

# mistral builders
machine=mistral
./addmachine $machine --list $list
#---------------------------------------------------------------
./addbuilder MISTRAL_gcc            --machine $machine       --build_script="./config/buildbot/mistral_gcc"                         --configureflags="--with-mpi --with-openmp"                --builderflags="Active"  --list $list

./addbuilder MISTRAL_intel17          --machine $machine     --build_script="./config/buildbot/mistral_intel17"              --configureflags="--with-mpi --without-openmp"             --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel17_hybrid   --machine $machine     --build_script="./config/buildbot/mistral_intel17_hybrid"       --configureflags="--with-mpi --with-openmp"                --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel17_openmp   --machine $machine     --build_script="./config/buildbot/mistral_intel17_openmp"       --configureflags="--without-mpi --with-openmp"             --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel17_hybrid_mixed --machine $machine --build_script="./config/buildbot/mistral_intel17_hybrid_mixed" --configureflags="--with-mpi --with-openmp --enable-mixed" --builderflags="Active"  --list $list

./addbuilder MISTRAL_intel18        --machine $machine       --build_script="./config/buildbot/mistral_intel18"              --configureflags="--with-mpi --withoutout-openmp"          --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18_hybrid --machine $machine       --build_script="./config/buildbot/mistral_intel18_hybrid"       --configureflags="--with-mpi --with-openmp"                --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18_openmp --machine $machine       --build_script="./config/buildbot/mistral_intel18_openmp"       --configureflags="--without-mpi --with-openmp"             --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18_hybrid_mixed --machine $machine --build_script="./config/buildbot/mistral_intel18_hybrid_mixed" --configureflags="--with-mpi --with-openmp --enable-mixed" --builderflags="Active"  --list $list

./addbuilder MISTRAL_nag            --machine $machine       --build_script="./config/buildbot/mistral_nag"        --configureflags="--with-mpi    --without-openmp"          --builderflags="Active"  --list $list
./addbuilder MISTRAL_nag_serial     --machine $machine       --build_script="./config/buildbot/mistral_nag_serial" --configureflags="--without-mpi --without-openmp"          --builderflags="build_only"  --list $list

./addbuilder MISTRAL_ocean_intel17  --machine $machine       --build_script="./config/buildbot/mistral_intel17_ocean"        --configureflags="--with-openmp --with-mpi --disable-atmo --disable-jsbach --disable-psrad  --with-yac=no" --builderflags="build_only"  --list $list
./addbuilder MISTRAL_ocean_intel18  --machine $machine       --build_script="./config/buildbot/mistral_intel18_ocean"        --configureflags="--with-openmp --with-mpi --disable-atmo --disable-jsbach --disable-psrad  --with-yac=no" --builderflags="build_only"  --list $list
#---------------------------------------------------------------
./addbuilder MISTRAL_intel18_pio    --machine $machine       --build_script="./config/buildbot/mistral_intel18_pio"          --configureflags="--with-mpi --withoutout-openmp"          --builderflags="Inactive"  --list $list

./addbuilder MISTRAL_pgi_cpu        --machine $machine       --build_script="./config/buildbot/mistral_pgi_cpu"          --configureflags="--with-mpi --withoutout-openmp"          --builderflags="Inactive"  --list $list
./addbuilder MISTRAL_pgi_gpu        --machine $machine       --build_script="./config/buildbot/mistral_pgi_gpu"          --configureflags="--with-mpi --withoutout-openmp"          --builderflags="Inactive"  --list $list
# testing for CDI-PIO

# breeze builders
machine=breeze
./addmachine $machine --list $list
./addbuilder BREEZE_gcc           --machine $machine --build_script="./config/buildbot/breeze_gcc"          --configureflags="--with-fortran=gcc"                  --builderflags="build_only"  --list $list
./addbuilder BREEZE_gcc_openmp    --machine $machine --build_script="./config/buildbot/breeze_gcc_openmp"   --configureflags="--with-fortran=gcc --with-openmp"    --builderflags="build_only"  --list $list
./addbuilder BREEZE_intel         --machine $machine --build_script="./config/buildbot/breeze_intel"        --configureflags="--with-fortran=intel"                --builderflags="build_only"  --list $list
./addbuilder BREEZE_intel_openmp  --machine $machine --build_script="./config/buildbot/breeze_intel_openmp" --configureflags="--with-fortran=intel --with-openmp"  --builderflags="build_only"  --list $list
./addbuilder BREEZE_nag           --machine $machine --build_script="./config/buildbot/breeze_nag"          --configureflags="--with-fortran=nag"                  --builderflags="build_only"  --list $list

#CSCS builders
machine=daint
./addmachine $machine --list $list
./addbuilder DAINT_CPU_cce        --machine $machine --build_script="./config/buildbot/daint_cpu_cray"  --configureflags="--with-fortran=cray" --builderflags="Active"      --list $list
./addbuilder DAINT_CPU_pgi        --machine $machine --build_script="./config/buildbot/daint_cpu_pgi" --configureflags="--with-fortran=pgi" --builderflags="Active"      --list $list
./addbuilder DAINT_GPU_pgi        --machine $machine --build_script="./config/buildbot/daint_gpu_pgi"  --configureflags="--with-fortran=pgi_gpu --enable-gpu --enable-claw=std" --builderflags="Active"  --list $list

#DWD machines
machine=dwd_nec
./addmachine $machine --list $list
./addbuilder DWD_nec             --machine $machine  --build_script="./config/buildbot/dwd_nec"       --builderflags="Active"  --list $list
./addbuilder DWD_nec_yac2        --machine $machine  --build_script="./config/buildbot/dwd_nec_yac2"  --builderflags="Active"  --list $list

