#!/bin/bash
addexp="./addexp"
#############################################################################
##
## create ocean list
##
#############################################################################
listname=ocean
./rmlist $listname
./mklist $listname

# add some virtual builders for ocean local building
./addmachine ocean       --list $listname
./addbuilder ocean_gcc   --configureflags="--with-fortran=gcc"                 --builderflags Active --machine ocean --list $listname
./addbuilder ocean_intel --configureflags="--with-fortran=intel --with-openmp" --builderflags Active --machine ocean --list $listname
./addbuilder ocean_nag   --configureflags="--with-fortran=nag"                 --builderflags Active --machine ocean --list $listname

# add omip technical tests only for builders with mpi parallelization
$addexp checksuite.ocean_internal/omip/exp.ocean_omip_ptest checksuite.ocean_internal/technical/exp.test_ocean_omip_technical \
  --without-configureflags without-mpi --runflags "cpu_time=00:30:00"  --list $listname
# add omip binary-identical test only to the ocean builder
./set_builder_flags Active             --builders MISTRAL_ocean  --list $listname
$addexp checksuite.ocean_internal/omip/exp.test_ocean_omip_10days --builders MISTRAL_ocean --runflags "cpu_time=00:30:00" --list $listname
# set all builders to Ocean
./set_builder_flags Ocean --builders "*" --list $listname
# deactivate special builders
./set_builder_flags Inactive --builders MISTRAL_nag_mtime MISTRAL_nag_serial --list $listname
#lets see the list
./lslist $listname

#############################################################################
