#!/bin/bash
set -x
# create all builders for a given list
list=$1
if [ x$list == x ]; then
  echo "Builbot list name missing"
  exit 1
fi

./mklist $list

# mistral builders
machine=mistral
./addmachine $machine --list $list
#---------------------------------------------------------------
./addbuilder MISTRAL_gcc            --machine $machine       --build_script="./config/dkrz/mistral.gcc"                         --configureflags="--with-mpi --with-openmp"                --builderflags="Active"  --list $list

./addbuilder MISTRAL_intel17          --machine $machine     --build_script="./config/dkrz/mistral.intel-17.0.6"              --configureflags="--with-mpi --without-openmp"             --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel17_hybrid   --machine $machine     --build_script="./config/dkrz/mistral.intel-17.0.6.hybrid"       --configureflags="--with-mpi --with-openmp"                --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel17_openmp   --machine $machine     --build_script="./config/dkrz/mistral.intel-17.0.6.openmp"       --configureflags="--without-mpi --with-openmp"             --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel17_hybrid_mixed --machine $machine --build_script="./config/dkrz/mistral.intel-17.0.6.hybrid.mixed" --configureflags="--with-mpi --with-openmp --enable-mixed" --builderflags="Active"  --list $list

./addbuilder MISTRAL_intel18        --machine $machine       --build_script="./config/dkrz/mistral.intel-18.0.4"              --configureflags="--with-mpi --withoutout-openmp"          --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18_hybrid --machine $machine       --build_script="./config/dkrz/mistral.intel-18.0.4.hybrid"       --configureflags="--with-mpi --with-openmp"                --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18_openmp --machine $machine       --build_script="./config/dkrz/mistral.intel-18.0.4.openmp"       --configureflags="--without-mpi --with-openmp"             --builderflags="Active"  --list $list
./addbuilder MISTRAL_intel18_hybrid_mixed --machine $machine --build_script="./config/dkrz/mistral.intel-18.0.4.hybrid.mixed" --configureflags="--with-mpi --with-openmp --enable-mixed" --builderflags="Active"  --list $list

./addbuilder MISTRAL_nag            --machine $machine       --build_script="./config/dkrz/mistral.nag"        --configureflags="--with-mpi    --without-openmp"          --builderflags="Active"  --list $list
./addbuilder MISTRAL_nag_serial     --machine $machine       --build_script="./config/dkrz/mistral.nag.serial" --configureflags="--without-mpi --without-openmp"          --builderflags="build_only"  --list $list

./addbuilder MISTRAL_ocean_intel17  --machine $machine       --build_script="./config/dkrz/mistral.intel-17.0.6.ocean"        --configureflags="--with-openmp --with-mpi --disable-atmo --disable-jsbach --disable-psrad  --with-yac=no" --builderflags="build_only"  --list $list
./addbuilder MISTRAL_ocean_intel18  --machine $machine       --build_script="./config/dkrz/mistral.intel-18.0.4.ocean"        --configureflags="--with-openmp --with-mpi --disable-atmo --disable-jsbach --disable-psrad  --with-yac=no" --builderflags="build_only"  --list $list
#---------------------------------------------------------------

# breeze builders
machine=breeze
./addmachine $machine --list $list
./addbuilder BREEZE_gcc           --machine $machine --build_script="./config/mpim/stretch.gcc"          --configureflags="--with-fortran=gcc"                  --builderflags="build_only"  --list $list
./addbuilder BREEZE_gcc_openmp    --machine $machine --build_script="./config/mpim/stretch.gcc.openmp"   --configureflags="--with-fortran=gcc --with-openmp"    --builderflags="build_only"  --list $list
./addbuilder BREEZE_intel         --machine $machine --build_script="./config/mpim/stretch.intel"        --configureflags="--with-fortran=intel"                --builderflags="build_only"  --list $list
./addbuilder BREEZE_intel_openmp  --machine $machine --build_script="./config/mpim/stretch.intel.openmp" --configureflags="--with-fortran=intel --with-openmp"  --builderflags="build_only"  --list $list
./addbuilder BREEZE_nag           --machine $machine --build_script="./config/mpim/stretch.nag"          --configureflags="--with-fortran=nag"                  --builderflags="build_only"  --list $list

#CSCS builders
machine=daint
./addmachine $machine --list $list
./addbuilder DAINT_CPU_cce        --machine $machine --build_script="./config/cscs/daint.cpu.cray"  --configureflags="--with-fortran=cray" --builderflags="Active"      --list $list
./addbuilder DAINT_CPU_pgi        --machine $machine --build_script="./config/cscs/daint.cpu.pgi" --configureflags="--with-fortran=pgi" --builderflags="Active"      --list $list
./addbuilder DAINT_GPU_pgi        --machine $machine --build_script="./config/cscs/daint.gpu.pgi"  --configureflags="--with-fortran=pgi_gpu --enable-gpu --enable-claw=std" --builderflags="Active"  --list $list

#DWD machines
machine=dwd_cray
./addmachine $machine --list $list
./addbuilder DWD_cray               --machine $machine       --build_script="./config/dwd/xce.cray"   --configureflags="--with-fortran=cray"   --builderflags="build_only"  --list $list

