#!/bin/bash
set -x

addexp="./addexp"
#############################################################################
##
## create ocean list
##
#############################################################################
listname=ocean
./rmlist $listname
# ./mklist $listname
./create_ocean_builders $listname
#-----------------------------------------------------------
# OES
# add omip technical tests only with mpi parallelization

$addexp checksuite.ocean_internal/technical/exp.ocean_omip_ptest checksuite.ocean_internal/technical/exp.test_ocean_omip_technical \
   --without-configureflags without-mpi enable-mixed --runflags "cpu_time=00:30:00"  --list $listname

# add omip binary-identical test on mistral
$addexp checksuite.ocean_internal/omip/exp.test_ocean_omip_10days \
 checksuite.ocean_internal/omip/exp.test_hamocc_omip_10days       \
 checksuite.ocean_internal/ShallowWater/exp.ocean_WilliamsonTestCase2_Hex \
 --machines mistral --without-configureflags enable-mixed --runflags "cpu_time=00:30:00 queue=compute" --list $listname

#-----------------------------------------------------------
# Other tests
# $addexp checksuite.infrastructure/memLog/exp.oce_memLog         --builders MISTRAL_intel_hybrid MISTRAL_intel17_hybrid MISTRAL_gcc --runflags "cpu_time=00:10:00 no_of_nodes=8" --list $listname
#-----------------------------------------------------------
#lets see the list
./lslist $listname
#-----------------------------------------------------------

