#!/bin/bash
addexp="./addexp"
#############################################################################
##
## create ocean list
##
#############################################################################
listname=ocean
./rmlist $listname
./mklist $listname

# add omip technical tests only for builders with mpi parallelization
$addexp checksuite.ocean_internal/omip/exp.ocean_omip_ptest checksuite.ocean_internal/technical/exp.test_ocean_omip_technical \
  --without-configureflags without-mpi --runflags "cpu_time=00:30:00"  --list $listname
# add omip binary-identical test to all builders
$addexp checksuite.ocean_internal/omip/exp.ocean_omip_short --runflags "cpu_time=00:30:00" --list $listname
./set_builder_flags Ocean --builders "*" --list $listname
#lets see the list
./lslist $listname

#############################################################################
