#! /usr/bin/env python
# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_builders import *
from model_paths import *
import argparse

parser = argparse.ArgumentParser(description='List builders ofor experiments in a list.')
parser.add_argument('experiment_names', type=str, nargs='+', help='experiment names')
parser.add_argument('--list', dest="list_name", type=str, help='buildbot list', required=True)

args = parser.parse_args()


thisList  = buildbot_experiments_list(args.list_name)
thisList.print_ExperimentsBuilders(args.experiment_names)

quit()


