#! /usr/bin/env python
# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_builders import *
from model_paths import *
import argparse

parser = argparse.ArgumentParser(description='List builders for experiments in a list.')
parser.add_argument('builder', type=str, help='builder name')
parser.add_argument('--list', dest="list_name", type=str, help='buildbot list', required=True)

args = parser.parse_args()

thisList  = buildbot_experiments_list(args.list_name)
builder_flags, configure_flags, experimentList =  thisList.get_BuilderProperties(args.builder)
if not "Inactive" in builder_flags:
  for exp in experimentList:
      print(exp)

quit()
