#! /usr/bin/env python
# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_builders import *
from model_paths import *
import argparse

parser = argparse.ArgumentParser(description='Create an experiment list.')
parser.add_argument('name', type=str, help='the name of the list')
args = parser.parse_args()

#print(args.name)
name=args.name
paths = model_paths()
if paths.thisListExists(name):
  print("This list exists.")
  quit()
  
myList  = buildbot_experiments_list(name)
myList.write()
print("Experiment list "+name+" is created.")

