#! /bin/ksh
#-----------------------------------------------------------------------------
#
# README file for Buildbot tests
#
# ========================================
#
# Walter Sauf,     MPI-M, 2009-10-22
# Marco Giorgetta, MPI-M, 2010-04-09
#
# Valid for icon-dev
#
# $Rev$:     Revision of last commit
# $Author$:  Author of last commit
# $Date$:    Date of last commit
#
#-----------------------------------------------------------------------------
#
# The Buildbot system is used to launch tests on different computer systems, 
# the so-called "slaves". The slaves used here for ICON are listed in the 
# configuration file ICON.cfg following the "c['slaves'] =" statement.
#
# On each slave Buildbot starts different tests, which differ in the choice 
# of the parallelization method or in the compiler. These are the so-called 
# "builders", which are listed in the  configuration file ICON.cfg 
# after the "c['builders'] =" statement.
#
# Each builder defines its specific environment variables BB_XYZ, as listed 
# in the list of 'builders' in after the 'env' keyword. These environment 
# variables are available for evaluation in scripts executed in the Buildbot test.
#
# Buildbot tests, as used here for ICON, do the following steps:
# 1 delete old contents
# 2 obtain the latest revision from trunk/icon-dev/ in the ICON SVN repository
# 3 run the "target_confmake.ksh" script to make the ICON executables
# 4 run the "bb_run"  script to run the grid generators and models
#
