#!/usr/bin/env python
# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_builders import *
from model_paths import *
import argparse

parser = argparse.ArgumentParser(description='Delete experiments from an experiment list.')
parser.add_argument('experiment_names', type=str, nargs='+', help='experiment names')
parser.add_argument('--list', dest="list_name", type=str, help='buildbot list', required=True)
parser.add_argument('--builders', dest="builder_names", nargs='*', help='buildbers', required=False)
parser.add_argument('--machines', dest="machine_names", nargs='*', help='machine name', required=False)
parser.add_argument('--with-configureflags', dest="withConfigureFlags",       nargs='*', help='with build flag', required=False)
parser.add_argument('--without-configureflags', dest="withoutConfigureFlags", nargs='*', help='without build flag', required=False)

args = parser.parse_args()

#print(args.experiment_names)
#print(args.list_name)
#print(args.builder_names)
#print(args.machine_names)
#print(args.withConfigureFlags)
#print(args.withoutConfigureFlags)


if args.builder_names and (args.machine_names or args.withConfigureFlags or args.withoutConfigureFlags):
  print("You cannot specify a builder with additional options.")
  quit()

paths = model_paths()
experiment_names = paths.get_experimentsNames_inPaths(args.experiment_names)
#print(experiment_names)
if not paths.thisListExists(args.list_name):
  print("The list "+args.list_name+" does not exist.")
  quit()

thisList  = buildbot_experiments_list(args.list_name)
#thisList.print_list()

if args.builder_names:
  thisList.delete_experimentsByNameFromBuildersByName(experiment_names, args.builder_names)
else:
  thisList.delete_experimentsByNameFromBuildersWithOptions(experiment_names, args.machine_names, args.withConfigureFlags, args.withoutConfigureFlags)

thisList.write()
#thisList.print_list()
print("Experiment list "+args.list_name+" is updated.")

quit()


