#ifdef HAVE_FC_ATTRIBUTE_CONTIGUOUS
#define CONTIGUOUS_TARGET CONTIGUOUS, TARGET
#define CONTIGUOUS_POINTER CONTIGUOUS, POINTER
#define CONTIGUOUS_ARGUMENT(intent) CONTIGUOUS, INTENT(intent)
#else
#define CONTIGUOUS_TARGET TARGET
#define CONTIGUOUS_POINTER POINTER
#define CONTIGUOUS_ARGUMENT(intent) INTENT(intent)
#endif
